lib/oxidized/model/aosw.rb
Also fix the boilerplate comment to reflect the OEM relationship
the first run will look like:
```
commit b24802fde6fa55548eb425f489478b9a0951c39c
Author: Oxidized <oxidized@XXX.com>
Date:   Tue Jan 20 04:36:44 2015 -0800
update ldnwifi-ctl.corp.XXX.com
---
ldnwifi-ctl.corp.XXX.com | 33 +++++++++------------------------
1 file changed, 9 insertions(+), 24 deletions(-)
diff --git a/ldnwifi-ctl.corp.XXX.com b/ldnwifi-ctl.corp.XXX.com
index c0233f1..28bc7b4 100644
--- a/ldnwifi-ctl.corp.XXX.com
+++ b/ldnwifi-ctl.corp.XXX.com
@@ -15,30 +15,15 @@
-# 
-# Supervisor Card slot      	: 0
-# System Serial#            	: AK0019269
-# SC      Assembly#         	: 2010051C (Rev:06.00) 
-# SC      Serial#           	: F02169535 (Date:03/09/12) 
-# SC      Model#            	: Aruba3400
-# HW MAC Addr …
```
=> stop Aruba changing the diff each 'show inventory'

README.md, lib/oxidized/model/comware.rb
Added support for Comware based devices from HP (A-series), H3C and
3Com.
=> Added model for Comware based devices

extra/oxidized.init
Adding an init script for sysv init. Tested with Debian/Wheezy.
=> Adding an Init Script

CHANGELOG.md, README.md, lib/oxidized/model/mikrotik.rb
Can probably be improved, but at least it backs up config.
=> Added support for Mikrotik RouterOS

lib/oxidized/model/powerconnect.rb
Some PowerConnect models were skipping fine as "Uptime" for example is shown across one line. Some models show this as a heading, and then lines for each stack member and so this was being included in the configuration. This will skip that "section" which is terminated by the next blank line.
=> PowerConnect Model not skipping some details

lib/oxidized/model/ironware.rb
I added a prompt because for my brocade, the default don't work, so I add a prompt less strict.
I also added comments if someone want to handle pager without enable mode.
I modified the line in " cmd :all ... " because in some commands (show chassis for example) the last line was deleted.
I removed the current temperatures lines and the uptime system line, because this values change everytime and provoc unwanted commit.
I added flash and module config.
At the end, when I tried to get "show run" there was a loop because "skip-page-display" need to be run in enable mode, so I added it.
=> ironware model improvement

lib/oxidized/model/cumulus.rb
I added the Cumulus feature, where I run all the commands in the same block thanks to "launch", because the is lot of command to run.
For the same reason, I added comment for a clearer config file.
=> Add the Cumulus feature

lib/oxidized/model/ironware.rb
=> Added a less strict prompt

lib/oxidized/model/ironware.rb
=> Delete more uptime line, temp line, speed line, for few ironware models

lib/oxidized/output/git.rb, lib/oxidized/worker.rb
Add update for a node in log file
=> Add log for update at /var/log/oxidized-update for git output

lib/oxidized/model/ironware.rb
fix regexp error with ruby 2.1
=> fix regexp error with ruby 2.1

lib/oxidized/nodes.rb, lib/oxidized/output/git.rb
this pull request is for this pull request in oxidized-web : https://github.com/ytti/oxidized-web/pull/11
=> add feature about versions and diffs for oxidized-web

lib/oxidized/model/ironware.rb
=> Remove more uptime lines

README.md
Add version and diff in the list
=> Add version and diff in the list

README.md
Never gonna ytt you up
Never gonna let you down
=> README.md: Introduce docs for output types

lib/oxidized/model/edgeos.rb
Adds support for #115.
Only been able to test this on ER-X but these are just based on Vyatta so taken the code from that model.
=> Added support for EdgeOS

extra/syslog.rb
Forgot to remove the argument from being used, will cause some issues as it seems to listen on a random port otherwise!
=> Fix Listening on Port

lib/oxidized/output/git.rb
Add Author and Message from a commit to a nodes version list
=> Add Author and Message

lib/oxidized/model/aosw.rb
This adds support for non-enabled users in Aruba OS. Also "show slots" is now commented out.
=> Added support for non-enabled users. Also comment out "show slots"

lib/oxidized/model/xos.rb
this is a better fix for 3c1c510
=> fix white space and CR problems on xos model

lib/oxidized/model/asa.rb
Otherwise "show run" is sandwiched in between commands which produce comments.  This is a bit messy.
=> move "show inventory" up

README.md
this closes  oxidized-web issue#32
=> Add documentation note about API URI

lib/oxidized/model/dnos.rb
Dell Force10 has changed model name from FTOS to DNOS
=> add support for Dell networking OS, dnos

README.md
Added a couple missing models. Fixed a typo in one of the names for the os. Restructured the list to separate models and brands. Updated the names to match the model names.
=> Updated Readme to match model names

lib/oxidized/model/powerconnect.rb
Change how we identify stackable switches using the word "Unit" to identify this. This is more reliable than identifying the Model number.
Fixed #195
=> Identify Stackable Switches

extra/rvm.oxidized.upstart
Upstart config file for ubuntu with an RVM install version of ruby.
=> Added upstart job for ubuntu RVM installs

lib/oxidized/config/vars.rb
Fixes ytti/oxidized#242.
Fixes ytti/oxidized-web#38.
Might fix a group issue in ytti/oxidized#171.
Added a check to verify the key exists for a group before returning.
=> Fix groups vars.

oxidized.gemspec
=> Update net-ssh version dependecy.

README.md, lib/oxidized/source/http.rb
This adds support for passing a username / password over to a http source that support basic auth.
=> Added support for using basic auth in http source

lib/oxidized/model/model.rb
=> do not include executed command name in output

lib/oxidized/input/ssh.rb
=> option to use ssh proxy command

extra/oxidized-report-git-commits
=> fix typo in example section of oxidized-report-git-commits

lib/oxidized/model/powerconnect.rb
I left the fix for #228 out for this pull request.
=> Powerconnect sflow timeout

lib/oxidized/model/edgeswitch.rb
Add model file to suit Ubiquiti EdgeSwitch. Assumes enable password is disabled via SSH.
=> EdgeSwitch Model

lib/oxidized/model/fortios.rb
=> strip the value of conf_file_ver

lib/oxidized/model/fortios.rb
To make this work, the timeout must be high as well. About 120 sec in my tests.
This is the fix for pull #298
=> Fix fortios more prompt

lib/oxidized/input/ssh.rb
As suggested in pull #328. Tested and works nicely.
=> Made the vars strings

README.md, lib/oxidized/model/ipos.rb, lib/oxidized/model/redback.rb
=> Add support for Ericsson Redback

lib/oxidized/model/ipos.rb, lib/oxidized/model/mtrlrfs.rb, lib/oxidized/model/xos.rb
This fixes the telnet 'hang' reported in issue #320
=> Fix telnet 'wait for prompt' bug

lib/oxidized/model/fortios.rb
Before the config dump needed a full privileged user.
=> Fixed the fortios prompt to support a read-only user

lib/oxidized/model/edgeswitch.rb
=> Edgeswitch remove commands from the config

README.md, lib/oxidized/model/netscaler.rb
=> add citrix netscaler support

README.md, lib/oxidized/model/datacom.rb
http://www.datacom.ind.br/en/products/product?familia-dm3000
=> add DataCom support

README.md, lib/oxidized/model/supermicro.rb
Resulting config:
```
Building running configuration. Please wait...
!<stackingDB>00</stackingDB>
!<stackingMac>01_00-25-90-40-c9-a0_02</stackingMac>
!
!
!
!---<InitPhaseConfig>
!---</InitPhaseConfig>
!
!
!
!
prompt sw02.lw.phx
hostname sw02.lw.phx
!
!
!
!
!
!
!
                                                                     !
!
snmp-server community <hidden> rw
snmp-server community <hidden> rw
!
snmp-server enable traps authentication
!
!
username ADMIN access-level 15
username ADMIN <secret removed>
username admin access-level 0
username admin <secret removed>
username lswadmin access-level 15
username lswadmin <secret removed>
enable <secret …
```
=> Add supermicro support tested on a SuperMicro SSE-G2252

lib/oxidized/model/asa.rb
Cisco ASA module changes:
-  Ignore lines containing "days" when running "show version", avoiding unnecessary commits due to time-based licenses.
-  Add support for backing up xml files referenced in the configuration, mainly used for Anyconnect.
-  Detect if DAP is configured, and backup the "dap.xml" file.
=> asa.rb enhancements

lib/oxidized/model/tmos.rb
Hi, here's the other fixes for this issue.
=> Fix for issue 359

README.md
I think now its clear how the groups repositories works.
=> fix the docs for groups repositories

lib/oxidized/output/git.rb
* make sure to expand the paths of all repositories
* get the right group repository path
=> fix the git group path config

README.md, lib/oxidized/cli.rb, lib/oxidized/config.rb
Talked to @Exhar about resubmitting #332 since he doesn't have the time to do it. So, here's a new pull which closes pull #332 .
=> Support setting pidfile location

README.md, lib/oxidized/model/mlnx.rb, lib/oxidized/model/mlnxos.rb
Tested with SX60xx but it should work with other "MELLANOX-OS" Devices to.
=> Adds support for Mellanox Switch devices

README.md, lib/oxidized/model/quanta.rb, lib/oxidized/model/quantaos.rb
Added model for Quanta Switches.
Tested on LB4M switches.
This is my first attempt, perhaps not the best one. Feedback appreciated.
FYI: I had to strip out the comments and the prompt from the `show run` output, I'm uncertain if I did it the right way however it does work.
=> Added Quanta OS

lib/oxidized/model/procurve.rb
Match entire control sequence after 'Press any key to continue'.
=> Fix issue #401

lib/oxidized/output/git.rb
ooooops! :stuck_out_tongue_closed_eyes:
=> remove puts

lib/oxidized/node.rb, spec/githubrepo_spec.rb, spec/node_spec.rb
=> only resolve the repository path when the output is `git`

lib/oxidized/model/asa.rb
Tested on 
```
! Cisco Adaptive Security Appliance Software Version 9.6(1)5
! Device Manager Version 7.6(1)
!
! Compiled on Fri 03-Jun-16 00:07 PDT by builders
! System image file is "(hd0,1)/asa961-5-smp-k8.bin"
! Config file at boot was "startup-config"
!
!
! Hardware:   ASAv, 2048 MB RAM, CPU Xeon 5600 series 2397 MHz,
! Model Id:   ASAv10
```
=> ASA secret filters for ikev2 IPSEC pre-shared-key

lib/oxidized/model/datacom.rb
I was unable to receive the prompt in any of the versions , but with this change now I'm getting .
=> Added support for the DM2104 and DM4100

CHANGELOG.md, lib/oxidized/model/cumulus.rb, lib/oxidized/version.rb
Right now cumulus prompt regex is broken out of the box, I've put in this fix, as well as added in more cumulus specific 'show commands'
=> This PR is to fix the cumulus

lib/oxidized/model/acos.rb, lib/oxidized/model/asa.rb
- Remove secrets from the A10 config
- Fix the regex for tacacs secret on ASA
- The A10 that I have doesn't have the key 'all-partitions' for show running-config. Maybe I should add two commands?
=> A10 and ASA fixes

lib/oxidized/model/routeros.rb
Addesses issue #544 
https://github.com/ytti/oxidized/issues/544
=> Add more extensive pattern matching

extra/rest_client.rb
Pull request to fix [https://github.com/ytti/oxidized/issues/466](https://github.com/ytti/oxidized/issues/466)
=> Update rest_client.rb to support 'rest' parameter

lib/oxidized/output/file.rb
in commit `de2a9d1` I changed the `#fetch` method to pass the
`Node` object instead of the node name.
=> fix the node variable from `#fetch`

README.md, lib/oxidized/input/tftp, lib/oxidized/input/tftp.rb, lib/oxidized/model/alvarion
=> Add Alvarion support

README.md
=> Update README.md SQL

Dockerfile
Updated, tested in our environment and seems to work fine.
=> Updated Dockerfile to use ruby 2.3

lib/oxidized/model/alvarion
wrongly removed in 56bac9722fe26ce8e0af54ec52ca0b17aa7c9fa1 from #560
=> rollback `alvarion` model

README.md, lib/oxidized/model/apc_aos.rb
Here is the clean pull request for the APC Module.
Thanks.
=> Added APC model to oxidized

extra/oxidized.nginx
Simple nginx example as requested by #550
=> Add nginx reverse proxy example

README.md, lib/oxidized/model/casa.rb
This will probably work for the other Casa CMTS as well.
=> This adds support for the Casa C1G CMTS

README.md, lib/oxidized/model/trango.rb
I only have the Trangolink-45 so I'm not sure which other radios this
might support.
=> Added support for Trango/Trangolink-45

README.md, lib/oxidized/model/dlink.rb
This specifically supports DES-3526/3550 series switches.
=> This adds support for D-Link switches

lib/oxidized/model/ciscosmb.rb
Adapted for SG series, not sure about SF. Tested on SG200 with default config. 
Please test.
=> Added SG support to ciscosmb.rb model

lib/oxidized/model/aosw.rb
=> [AOWS] Remove trailing whitespace and enable prompt detection

README.md
hi ytti!
like we discussed on gitter -> here is the PR regarding the debug-parameter.
kind regards,
Matt
=> documention: debug inside input is now boolean

lib/oxidized/model/ios.rb
=> Hide remaining passwords

README.md, lib/oxidized/model/zhoneolt.rb
=> adding zhone OLT/MX GPON/MetroE/DSL gear

lib/oxidized/model/nxos.rb
Per: [https://github.com/ytti/oxidized/issues/660](url)
=> Add support for telnet

lib/oxidized/model/fortios.rb
added secret removal for fortiOS,
I found both variants: "set password" and "set passwd",
so put them togheter in a single regex.
=> added secret removal for fortiOS

lib/oxidized/model/aosw.rb
Update the aosw model to support Aruba IAP, Instant Controller and Mobility Access Switch. Updated the notes with about the supported and tested devices. Tested as best I could with the equipment I have access to.
=> Aruba IAP MAS

lib/oxidized/model/procurve.rb
=> Procurve convert next line (NEL) to new line

lib/oxidized/model/nxos.rb
Took config from our local setup.
Adding since it does not have it
Thanks
dave
=> nxos.rb: Add secret block

README.md
Adding notes on when you might want to set:
```
next_adds_job: true
```
Docs as suggested by @laf
=> Update documentation to include next_adds_job

lib/oxidized/model/timos.rb
so it doesn't look like a new config each time to crawls the box.
=> Updated timos.rb to ignore "Generated" and "Finished" lines

README.md, lib/oxidized/model/tplink.rb
reopening pull request #703 from a clean branch. Sorry got my fork a little messed up.
- changed back to cmd instead of send for enable (had problems with it in the first place but sind my line-break cleanup method cmd seems to work as expected, too)
- added tplink to README
=> Tplink model

lib/oxidized/model/routeros.rb
=> add software version

README.md, lib/oxidized/model/saos.rb
I've added another ignore line for SAOS7 devices. And fixed a typo in readme.md for saos
=> Ciena saos7 fixes

README.md, lib/oxidized/model/oneos.rb, oxidized.gemspec
Slight modifications to gemspec for newer ssh gem and correct telnet syntax
=> added model for OneAccess OneOS Voice Gateways/Routers

lib/oxidized/input/ssh.rb
@ytti this was blocking our backups. It's not pretty to do it this way, but I don't know a better way to fix it.
=> Ignore the host key checking

README.md, lib/oxidized/model/cisconga.rb
Fixes https://github.com/ytti/oxidized/issues/772
=> Support for Cisco NGA.

extra/oxidized.init
Making it more obvious to users what needs to happen
=> Edit init script

lib/oxidized/model/ios.rb
let me know if you want these squashed into one commit.  I think I'm done messing with IOS for now.
=> more changes to ios.rb

lib/oxidized/model/ios.rb
- Fixed IOS model to redact only secrets
- Added IPSEC keys to IOS secret config
=> Improve IOS secret handling

lib/oxidized/model/fortios.rb
Values changed for every show command and versioning was not possible.
=> fortios Added secret and key statements to secret removal

lib/oxidized/model/firewareos.rb
=> Support for Watchguard Logon Disclaimer

README.md, lib/oxidized/model/voltaire.rb
Add support for this Mellanox IB switches:
http://www.mellanox.com/related-docs/voltaire_ib_switch_systems/Grid-Director-4036-WEB-071510.pdf
=> Added support for Mellanox voltaire switch to the list of supported devices

README.md
I have been using this software with FreeBSD without any issues for a while now.
=> Add support for FreeBSD

README.md, lib/oxidized/model/netgear.rb
tested with netgear m5300 series switch
unfortunately reading config requires enable..
=> add support for netgear switch

lib/oxidized/model/pfsense.rb
Fix closing /pfsense tag.
Closes #825.
=> Fix closing /pfsense tag

README.md, lib/oxidized/hook/exec.rb
Added OX_NODE_IP to access the IP address for exec commands. Sry for PR #842, started this one from a clear branch.
=> Added OX_NODE_IP for hook type: exec

README.md
Update for Avaya VSP switches that run voss
=> Update for Avaya VSP Switches

lib/oxidized/model/voss.rb
Adding support Avaya VSP Operating System Software(VOSS).  Tested both ssh and telnet.
=> Add support for Avaya VSP

lib/oxidized/model/routeros.rb
This includes the list of changes from the history on who made a change. This can then be tied up with the changes in the diff of the configuration retrieved.
=> Included the changelog for RouterOS

lib/oxidized/model/voss.rb
every config update was making a diff because temperature was included in "show sys-info".  Used more specific commands so temperature is not included now.
=> Update voss.rb because of git diff

lib/oxidized/model/boss.rb
Add support for Avaya Baystack Operating System Software(BOSS)
=> Add support for Avaya BOSS

README.md, lib/oxidized/model/hirschmann.rb
Tested on Hirschmann RS20, Hirschmann MAR1040 and a Schneider Electric TCSESM (Hirschmann base model).
=> Add support for Hirschmann model

lib/oxidized/model/procurve.rb
Thought this might be useful to make as default.
We use this
The radius key part is extra :)
=> Procurve: Adding More 'show' commands

lib/oxidized/model/asa.rb
work in progress - please do not merge yet, still testing with new 0.20.0 release
=> u/panzerfly's patch for 'Cisco ASA - Added support for multiple contexts' with fixes

lib/oxidized/model/dlink.rb
fixes #878 
added this for @Turbid
=> remove Uptime from dlink "show switch"

README.md
=> Add explicit advert for additional maintainers

README.md, lib/oxidized/model/audiocodes.rb
Follow up of #906 with cleaner commits.
=> Create audiocodes.rb for AudioCodes devices

lib/oxidized/input/ssh.rb, oxidized.gemspec
Follow up of #889 with cleaner commits.
=>  Use newer net-ssh as default requirement 

README.md
Fixes: #877 
is this what you had in mind @ytti?
=> Added DCN and indicated to map this to IOS

lib/oxidized/model/ipos.rb
I will be needed enable mode support, but 'by-default' that is impossible. I make a patch for enable mode. Please add to master tree.
Thanks.
=> Added enable mode support for Ericsson SE100

README.md, lib/oxidized/model/ucs.rb
Added support for Cisco UCS
#913
@danilopopeye Sorry, I had difficulties with my previous pull request
=>  Add support for Cisco UCS model 

README.md, lib/oxidized/model/hpemsa.rb
tested with hp msa 2040 storage system
=> add support for hp msa storage

README.md, lib/oxidized/model/alteonos.rb, lib/oxidized/model/radware.rb
Added support for Radware/Alteon Application Switch
=> Create alteonos.rb for radware/alteon 

lib/oxidized/model/ciscosmb.rb
also added radius key redaction
=> Add show command

README.md, lib/oxidized/model/ironware.rb
The space after Password is not present in the prompt on all devices I checked.
=> no space after password

README.md, lib/oxidized/model/acsw.rb
=> Create acsw.rb for Cisco Ace

README.md, lib/oxidized/model/sgos.rb
Add sgos.rb to models and to README
=> support for SGOS

docs/Supported-OS-Types.md
=> docs: Fixed the links to the OS files

lib/oxidized/model/fiberdriver.rb
Configuration includes a generation timestamp.
=> Fixed ever-changing output in fiberdriver model

README.md
Added a help section directing users to the various locations.
Hope this is ok.
=> Added help section to docs

Dockerfile, docs/Hooks.md, lib/oxidized/hook/xmppdiff.rb
We're using XMPP instead of Slack. So I've rewritten the hook for XMPP
=> Added hook for XMPP MUC

docs/Supported-OS-Types.md, lib/oxidized/model/opnsense.rb
This is just a very small change to the pfsense model to make it compatible with opnsense (which is a fork of pfsense - https://opnsense.org/)
=> Add support for Opnsense

lib/oxidized/model/ios.rb
Community is displayed next to this line (old ios versions)
=> Hide snmp community

lib/oxidized/model/routeros.rb
=> Remove system comment on time based rules.

lib/oxidized/hook/slackdiff.rb
If there are no diffs then do not try to post to Slack.
Fixes #1150
=> Don't post diff to Slack if there are no diffs

lib/oxidized/model/ciscosmb.rb
=> Add show commands to ciscosmb

lib/oxidized/model/edgeos.rb, lib/oxidized/model/vyatta.rb
=> Add "commands" flag to "show configuration" on VyOS/Vyatta/EdgeOS

README.md
In #1207, @yeled and @laf expressed some desire for better documentation of docker container usage and build options. This PR delivers.
=> Refresh docker section in readme

README.md, docs/Creating-Models.md, docs/Model-Notes/VRP-Huawei.md
* Rewords and restructures README to move plea for maintainer below the introduction so that Github's mobile view contains at least some description of the project.
* Introduces a caveat section to the Huawei VRP model notes (addresses and closes #1218)
* Minor miscellaneous fix-ups.
=> documentation touch-ups and issue #1218

lib/oxidized/model/fortios.rb
Pull request as per issue #1199
=> Add fortios fields to be masked by remove_secret flag

lib/oxidized/model/dcnos.rb
Premature PR with faults mistakenly considered tested. Regrets were had. Correcting.
=> unspeakable things took place in original PR, correcting model

spec/input/ssh_spec.rb
=> Update ssh_spec.rb to pass successfully

spec/githubrepo_spec.rb
Adapts tests to take into account changes introduced in #1257
=> Update githubrepo_spec.rb to pass successfully

.rubocop_todo.yml, lib/oxidized/hook/xmppdiff.rb
Untested, but introduces no functionality-modifying elements. @mortzu could you verify?
=> restructure xmppdiff.rb to comply with rubocop

.rubocop_todo.yml, lib/oxidized/hook/slackdiff.rb
Untested, but introduces no functionality-modifying elements. @natm could you verify?
=> restructure slackdiff.rb to comply with rubocop

.rubocop_todo.yml, lib/oxidized/hook/awssns.rb
Cosmetics only, not functionality affecting.
=> restructure awssns.rb to comply with rubocop

docs/Configuration.md, docs/Creating-Models.md, docs/Hooks.md, docs/Model-Notes/ArbOS.md, docs/Model-Notes/Comware.md, docs/Model-Notes/Netgear.md, docs/Outputs.md, docs/Ruby-API.md, docs/Sources.md
Some misc doc fixups in various files that fix various small items/clarity.
No code changes - all .md files / documentation. Individual commits for each file have a little more information - but most changes are simply clarity/style/readability adjustments.
=> Misc docfixes

lib/oxidized/worker.rb
This small adjustment changes to only increment `@jobs_done` for a successful pull of a node or when the retries are exceeded and the node is abandoned for that cycle.
Previously `@jobs_done` was incremented as soon as `process()` was called.
The problem is that this incremented `@jobs_done` before knowing if the node completes OK or fails (And requires a retry).
During a retry - the node to be requeued for processing - which would increment `@jobs_done` multiple times per node (up to the configured retries count per node for a downed node).
This causes `@jobs_done` to become out of sync with reality. One of the main impacts of this is when the `:nodes_done` hook gets called. This could cause the hook to fire mid-cycle and then not fire at the 'real' end of the interval which is the …
=> Quick-fix: repair some logic for @jobs_done.

lib/oxidized/model/pfsense.rb
Added removal of secrets to pfsense
=> Added removal of secrets to pfsense

docs/Supported-OS-Types.md, lib/oxidized/model/comnetmicrosemiswitch.rb
Related to https://github.com/ytti/oxidized/pull/1183
=> Comnet Microsemi Switch support

CHANGELOG.md, docs/Supported-OS-Types.md, lib/oxidized/model/edgecos.rb
=> falsepositives edgecos memory and uptime (closes #1364)

CHANGELOG.md, docs/Model-Notes/Cumulus.md, docs/Model-Notes/README.md, docs/Model-Notes/cumulus.md, lib/oxidized/model/cumulus.rb
@User4574 originally submitted a PR #1089 , but seems to have abandoned it without making the requested updates. I have created this PR to try and get the changes proposed merged in.
This PR closes #1087 
I am not quite sure about the testing piece. I am still investigating if updates / changes are required due to my ruby noobiness.
=> Add support for frr in new versions of cumulus - Issue 1087 

CHANGELOG.md, docs/Configuration.md, docs/Model-Notes/Cumulus.md, docs/Model-Notes/EOS.md, docs/Model-Notes/Netgear.md, docs/Model-Notes/XGS4600-Zyxel.md
Updated documentation on ssh auth method configuration, misc. additional linting.
Closes #1379
=> ssh auth docs and misc documentation fixups, closes #1379

CHANGELOG.md, docs/Hooks.md, docs/Outputs.md, docs/Sources.md, docs/Supported-OS-Types.md
Corrects minor typos and markdown lint
=> fix minor typos and docs lint

README.md
Validated installation instructions for version 0.23.0 on the following docker containers:
* debian:stretch
* centos:6
* centos:7
Updated installation instructions where applicable.
Closes ytti/oxidized-web#171
=> update installation instructions for latest version

.rubocop.yml, lib/oxidized/source/http.rb, spec/source/http_spec.rb
=> Feature string navigation

lib/oxidized/model/model.rb
=> Model callback enhancement

CHANGELOG.md, docs/Creating-Models.md
Documented model callback enhancements from #1390
=> Document model callback enhancements from #1390

lib/oxidized/model/dlink.rb
Corrects regexp typo in dlink.rb
=> Correct typo in D-Link model

lib/oxidized/input/telnet.rb, lib/oxidized/version.rb
=> Fix 1385 telnet

CHANGELOG.md, Dockerfile
bump docker to phusion/baseimage:0.10.1
=> bump docker to phusion/baseimage:0.10.1

CHANGELOG.md, docs/Model-Notes/AireOS.md, docs/Model-Notes/ArbOS.md, docs/Model-Notes/Comware.md, docs/Model-Notes/EOS.md, docs/Model-Notes/JunOS.md, docs/Model-Notes/Netgear.md, docs/Model-Notes/README.md, docs/Model-Notes/VRP-Huawei.md, docs/Model-Notes/XGS4600-Zyxel.md
Lint and standardize use of markdown in model notes
=> lint model notes markdown

docs/Ruby-API.md
Documents monkey patching in Ruby API
=> add monkey patching to ruby API docs

docs/Ruby-API.md
Document extended string class and convenience methods in API
=> document convenience methods

lib/oxidized/input/ssh.rb, lib/oxidized/node.rb, lib/oxidized/output/http.rb, lib/oxidized/source/csv.rb, lib/oxidized/source/http.rb, lib/oxidized/worker.rb
=> Refactor smells

CHANGELOG.md, docs/Model-Notes/README.md, docs/Model-Notes/Viptela.md, lib/oxidized/model/viptela.rb
Add model for Viptela devices.
Closes #1376
=> Add Viptela model Issue (closes #1376)

CHANGELOG.md, docs/Supported-OS-Types.md, lib/oxidized/model/eciapollo.rb
Added support for the ECI Telecom Apollo platform
=> Added support for the ECI Telecom Apollo platform

CHANGELOG.md
=> Added to details to CHANGELOG for #1444

docs/Supported-OS-Types.md
Just adding Calix AXOS to supported devices list.
=> Update for Calix AXOS Devices

docs/Configuration.md, lib/oxidized/config.rb, lib/oxidized/node.rb
=> adding ability to specify crashfile directory and naming using hostnames

lib/oxidized/node.rb
=> fix reference to old 'file' variable

CHANGELOG.md, docs/Supported-OS-Types.md, lib/oxidized/model/comtrol.rb, lib/oxidized/model/dellx.rb
=> Added model dellx.rb for Dell X-series switches.

docs/Configuration.md
=> added 'username: nil' in Advanced Config

lib/oxidized/model/powerconnect.rb
added support for config mode to regex, this enable oxidized-script to make config mode changes to powerconnect devices without breaking existing support.
=> added support for config mode to prompt regex

lib/oxidized/model/procurve.rb
=> add support to space in hostname in procurve prompt

lib/oxidized/model/tplink.rb
https://github.com/ytti/oxidized/issues/1574
=> model/tplink.rb: remove password in clear text for older TPLink models (#1574)

CHANGELOG.md, docs/Supported-OS-Types.md, lib/oxidized/model/firebrick.rb
Added support for Firebrick devices
=> Add Firebrick support

CHANGELOG.md, lib/oxidized/model/ios.rb
Improved secret filtering for ios
=> Improved secret filtering for ios

CHANGELOG.md, lib/oxidized/model/asa.rb
Improved secret filtering for asa.
=> Improved secret filtering for asa

CHANGELOG.md
Bump the changelog now that 0.25.0 is released.
=> bump changelog post 0.25.0 release

lib/oxidized/model/siklu.rb
Some Siklu's have a few ^M's at the beginning of their prompt we have to match. In addition to quotes, etc
Some Siklu's have a few ^M's at the beginning of their prompt we have to match. In addition to quotes, etc
=> Siklu Model Prompt Update

.travis.yml
https://docs.travis-ci.com/user/languages/ruby/#bundler-20
=> fix up travis config for legacy bundler

CHANGELOG.md
=> changelog corrections

CHANGELOG.md, Dockerfile, oxidized.gemspec
Make the Docker container do more out of the box:
* Added `pg` gem and libraries to enable pgsql support for sequel and sql source
* Added `net-http-persistent` and `mechanize` for http input
* Added `net-tftp` for tftp input
Closes #1737
=> make docker do more out of the box

CHANGELOG.md
=> correct CHANGELOG.md

CHANGELOG.md, oxidized.gemspec
Fixes dependencies for net-ssh when using ssh keys.
Closes issue #1742
=> Fixed dependencies for net-ssh (#1742)

CHANGELOG.md, lib/oxidized/model/routeros.rb
This PR fixes the configuration backup via telnet.
=> routeros: fix configuration backup via telnet input

docs/Model-Notes/README.md, docs/Model-Notes/ios.md
=> Documentation to add feature to list unsaved changes to a Cisco switch

docs/Configuration.md
=> Docs: SSH public-key authentication

CHANGELOG.md, lib/oxidized/model/aos.rb
In order to track what devices support 10G uplinks, a "show license" has been added.
=> As for license info

CHANGELOG.md, docs/Supported-OS-Types.md, lib/oxidized/model/icotera.rb
Adding support for [Icotera](https://icotera.com/products) devices.
=> Add support for Icotera

CHANGELOG.md, docs/Supported-OS-Types.md, lib/oxidized/model/firelinuxos.rb
Refactor FirePower model from PR #950 by @rgnv
Closes #1781
=> refactor firelinuxos model from PR #950

README.md
Bump number of supported models in `README.md`
=> proudly supporting over 120 models

CHANGELOG.md, docs/Supported-OS-Types.md, lib/oxidized/model/purity.rb, lib/oxidized/model/purityos.rb
Add support for Pure Storage
Add support for Pure Storage systems running PurityOS
=> Add support for Pure Storage systems running PurityOS

docs/Supported-OS-Types.md
Remove stray whitespace introduced in #1823
=> stray whitespace introduced in #1823

docs/Supported-OS-Types.md
- doc change, tested with github preview.
- doc change, no test needed.
- is a doc change.
- not needed i think.
make link to fastiron.rb work in [docs/Supported-OS-Types.md](docs/Supported-OS-Types.md)
=> stray whitespace

lib/oxidized/model/c4cmts.rb
Remove stray tab in c4cmts model
=> remove stray tab in c4cmts model

CHANGELOG.md, lib/oxidized/model/aosw.rb
Propose this prompt instead:
^([\w\(.@-]+(\)?\s?)[#>]\s?)$
https://rubular.com/r/kTbM6HlCeBxPiu
Possible fix for https://github.com/ytti/oxidized/issues/1254
=> aosw.rb - Update prompt 

lib/oxidized/model/procurve.rb
Revert prompt simplification from #1869
=> revert procurve prompt simplification

CHANGELOG.md, lib/oxidized/model/linuxgeneric.rb
See: 
https://github.com/ytti/oxidized/pull/1820#issuecomment-515677075
=> Remove snmpd lines from linuxgeneric.rb 

CHANGELOG.md, lib/oxidized/model/ios.rb
Originally PR #1889, generalized to include both pap and chap secrets of any type.
=> remove ppp password from ios model

FAQ.md
Adds a very basic, initial FAQ.md. Closes #1933
=> add basic FAQ, closes #1933

docs/Creating-Models.md, docs/Troubleshooting.md
Refactor documentation to be more intuitively located.
=> Refactor  documentation

CHANGELOG.md, lib/oxidized/model/ciscosmb.rb
Added support for privilege escalation on ciscosmb platform. Closes issue #1797
=> Fixes #1797

CHANGELOG.md, lib/oxidized/model/edgecos.rb
add support for transceiver details in the EdgeCOS model
=> EdgeCOS: include transceiver details

CHANGELOG.md, docs/Supported-OS-Types.md, lib/oxidized/model/os10.rb
This is an attempt to create a file to enable support for Dell OS10 based devices.
I am currently doing an internship in a place which uses "Dell PowerSwitch S4148U-ON" devices and therefore could only try this config on this particular equipment. The file is based on the dnos.rb and can probably be improved. Hopefully this can be useful.
=> Add support for Dell OS10

CHANGELOG.md, lib/oxidized/model/edgecos.rb
include the commands in the output and update patterns for minor software version dependent differences in the EdgeCOS model
=> EdgeCOS: improve model

CHANGELOG.md
Stylize `CHANGELOG.md` to [Keep a Changelog](https://keepachangelog.com/en/1.1.0/) style.
Closes #2066
=> Stylize changelog to keepachangelog style

README.md
Bump the number of models mentioned in the readme file to reflect current development state.
=> mention increase in supported models

CHANGELOG.md, docs/Supported-OS-Types.md, lib/oxidized/model/edgecos.rb
=> Fix EdgeCOS model

CHANGELOG.md, docs/Troubleshooting.md, lib/oxidized/model/enterasys.rb
Small fix in the documentation and in the enterasys model to allow connection when the user
has rw access only - previously the backup user needed super-user access.
=> Enhance model enterasys

CHANGELOG.md, docs/Sources.md, lib/oxidized/source/http.rb
Add read_timeout to http source to handle case of big list of nodes
Closes issue #2232
=> Add read_timeout to http source to handle case of big list of nodes

CHANGELOG.md, lib/oxidized/model/enterasys.rb
Does two things:
* Fixes telnet for some Enterasys switches
* Adds "show version" as comment to the output, as it is done for many other models
=> Enterasys improvements

lib/oxidized/source/http.rb
Simple one line change to make rubocop happy.
=> Fix rubocop by using if modifier for single statement

spec/input/ssh_spec.rb
The behavior was changed in 8179f485, but the tests weren't updated.
=> Fix ssh_spec tests

README.md
Added something i use with RVM, cause the ruby on centos 7 is 2.0.0 and managed to make it work with RVM
Feedback is welcomed.
=> A proper install documentation for Centos 7 via RVM

README.md
=> Update useradd to "useradd -m" and ubuntu startup service installation steps in README.md

lib/oxidized/model/casa.rb
Updated handling of (up)time in show system command. Original not working on Casa C100G v7.2.4 . And prefer modify than drop line.
=> Update casa.rb (up)time fix

CHANGELOG.md, lib/oxidized/model/sonicos.rb
sonicos - added scrubbing for hashed values: sslvpn password, administrator password, ftp password, shared-key
=> Add scrubbing for SonicOS

CHANGELOG.md, docs/Model-Notes/LenovoNOS.md, docs/Model-Notes/README.md, docs/Supported-OS-Types.md, lib/oxidized/model/lenovonos.rb
Add Lenovo Network OS support. Tested on EN4093R.
=> Lenovo Network OS support

Dockerfile, README.md
=> Correct dockerfile to not mount Volume

CHANGELOG.md, lib/oxidized/model/comware.rb
adds enable(super) login password support for comware devices
=> Comware enable support

CHANGELOG.md, docs/Supported-OS-Types.md, lib/oxidized/model/yamaha.rb
Add YAMAHA network devices support.
I just tested my YAMAHA NVR500 only. But it's possible to work other YAMAHA devices.
=> Add YAMAHA devices support

CHANGELOG.md, lib/oxidized/model/aoscx.rb
=> Improve regex for aoscx

CHANGELOG.md, docs/Supported-OS-Types.md, lib/oxidized/model/h3c.rb
add simple model for h3c network switches
=> h3c device model

CHANGELOG.md, docs/Supported-OS-Types.md, lib/oxidized/model/truenas.rb
Adding a new model file for TrueNAS devices.
Closes issue #2607
I didn't include any rubocop test results because it seems the tests in this repo are failing right now, and I'm not well equipped to repair that.
=> Adding new TrueNAS model support

CHANGELOG.md, docs/Sources.md, lib/oxidized/source/sql.rb
Extended mysql source configuration to include TLS options
Close the issue #2096
=> Extended mysql source (TLS support) 

CHANGELOG.md, lib/oxidized/model/mlnxos.rb
This adds some more pager handling, as needed for MIS5030Q.
=> mlnxos: More pager handling

CHANGELOG.md, lib/oxidized/model/nxos.rb
This PR adds an additional regex to mask tacacs+ host keys
=> Mask NX-OS tacacs+ host keys

CHANGELOG.md, oxidized.gemspec
Follow-up to #2570 
This just updates to latest non-beta release so it's not as scary from a stability perspective. All seems to work well.
=> Update net-ssh to 7.0.1

lib/oxidized/hook/githubrepo.rb, lib/oxidized/jobs.rb, lib/oxidized/model/adva.rb, lib/oxidized/model/pfsense.rb, lib/oxidized/model/yamaha.rb
=> Run rubocop command to auto correct syntax

CHANGELOG.md, Dockerfile
Install rugged with ssh support when building docker image
=> Install rugged with ssh in docker

CHANGELOG.md, lib/oxidized/model/sonicos.rb
=> updated system-uptime regex

.github/workflows/publishdocker.yml, CHANGELOG.md
=> build(Docker): only build docker images on pushes to master

README.md
=> fixed docker-compose.yml in README

.github/dependabot.yml, .github/workflows/stale.yml
=> ci: dependabot and stale update

README.md
if libyaml-dev is not installed, oxidized fails to run.
=> fixes documentation

CHANGELOG.md, docs/Supported-OS-Types.md, lib/oxidized/model/dlinknextgen.rb
model for D-Link cisco like CLI (@mirackle-spb)
=> New model for D-Link cisco like CLI

CHANGELOG.md, lib/oxidized/model/aoscx.rb
Removes fan speed from Aruba CX output. Build on the work by @vppencilsharpener and @steveneppler
Before:
```
! Fan information
! ------------------------------------------------------------------------------
! Location-      Product  Serial Number  Speed   Direction      Status  RPM
! Mbr/Slot/Fan   Name
! ------------------------------------------------------------------------------
! Tray-1/1/1     N/A      N/A            slow    front-to-back  ok      3961   
! Tray-1/1/2     N/A      N/A            slow    front-to-back  ok      3987   
! Tray-1/2/1     N/A      N/A            slow    front-to-back  ok      4016   
! Tray-1/2/2     N/A      N/A            slow    front-to-back  ok      3998   
! Tray-2/1/1     N/A      N/A            slow    front-to-back  ok      3973   
! …
```
=> aoscx: Fix fan RPM speeds included in environment output

README.md
- [ N/A ] Changes are reflected in the documentation
- [ N/A ] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)
- [ N/A ] Tests added or adapted (try `rake test`)
- [ N/A ] Passes rubocop code analysis (try `rubocop --auto-correct`)
1- I made a small grammatical change to the description
2- and removed incomplete sentence
=> Made grammatical change to description and removed incomplete sentence

CHANGELOG.md, lib/oxidized/model/tplink.rb, lib/oxidized/model/zynosgs.rb
tp-link: fixed enable mode port login entrance
=> tp-link: fixed enable mode port login entrance

CHANGELOG.md, docs/Supported-OS-Types.md, lib/oxidized/model/asternos.rb
model for Asterfusion Network Operating System (@avl-dev)
=> New model for Asterfusion Network Operating System

CHANGELOG.md, docs/Supported-OS-Types.md, lib/oxidized/model/ml66.rb
Added support for Ericsson Minilink 6600 series LOS equipment
=> Ericsson Minilink 6600 support

CHANGELOG.md, lib/oxidized/model/adva.rb
Change collected configuration file from current (show run current) to delta (show run delta) for making the config usable for device restoring.
=> fix adva config for restore

CHANGELOG.md, lib/oxidized/output/gitcrypt.rb
=> Gitcrypt refinements

CHANGELOG.md, docs/Supported-OS-Types.md, lib/oxidized/model/mimosab11.rb
Added model support for mimosa b11 devices
Closes issue #2858
=> added model mimosab11

CHANGELOG.md, lib/oxidized/model/iosxr.rb
Include Last config change by in backup.
=> Tweak iosxr model

README.md
=> docs(README): update link to youtube

CONTRIBUTING.md, README.md, docs/Supported-OS-Types.md
- [] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)
Closes issue #3023
@ytti proposed to create the function of "model maintainers" as possibility to have a low entry barrier and low effort way for people to take responsibility for "their" model for "their" favorite hardware.
This PR aims to document the function of "model maintainers", but also documents how to contribute to Oxidized.
=> Introducing model maintainers / document how to contribute to Oxidized

CHANGELOG.md, lib/oxidized/model/vyatta.rb
Adds version info to vyatta.rb like ios.rb, junos.rb etc.
=> Add Vyatta / VyOS version info

CHANGELOG.md, lib/oxidized/model/sonicos.rb
=> Add 'wpa passphrase' as secret, fixes #3036

CHANGELOG.md, docs/Supported-OS-Types.md, lib/oxidized/model/ocnos.rb
Add support for IP Infusion OcNOS
=> Add support for IP Infusion OcNOS

lib/oxidized/cli.rb, lib/oxidized/config.rb, lib/oxidized/worker.rb
Implement https://github.com/ytti/oxidized/issues/3087
Thank you!
=> [FEATURE REQUEST] Allow users to run oxidized from CLI with a custom config

docs/Model-Notes/FortiOS.md, docs/Supported-OS-Types.md
- [ N] Passes rubocop code analysis (try `rubocop --auto-correct`)
- [ N] Tests added or adapted (try `rake test`)
- [Y ] Changes are reflected in the documentation
- [ N] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)
Add FortiOS notes.
=> Add FortiOS notes

lib/oxidized/model/truenas.rb
=> TrueNAS model: update ignore pattern for SCALE

lib/oxidized/model/fsos.rb
=> remove uptime from devices like S5860-20SQ

CHANGELOG.md, docs/Supported-OS-Types.md, lib/oxidized/model/onefinity.rb
I added basic support for the Fujitsu 1finity switches. They ship without telnet enabled so I did not implement it.
=> Initial implementation of the Fujistu 1Finity

CHANGELOG.md, docs/Release.md
- Update CHANGELOG.md after 0.30.0 release
- Document the release process in docs/Release.md
=> Update Changelog & document release process

docs/Configuration.md
- ~~Passes rubocop code analysis (try `rubocop --auto-correct`)~~
- ~~Tests added or adapted (try `rake test`)~~
- ~~Changes are reflected in the documentation~~
- ~~User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)~~
Add two examples for how to configure the web-server to listen on the an IPv6 Public address and the IPv6 Link Local address.
=> Docs: [Configuration] Add IPv6 Rest API example

CHANGELOG.md, lib/oxidized/model/fortios.rb
- [?] Passes rubocop code analysis (try `rubocop --auto-correct`)
- [N] Tests added or adapted (try `rake test`)
- [N] Changes are reflected in the documentation
- [Y] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)
filter date in comment when using acme
```
config vpn certificate local
..
edit "fgvm-fw.customer.domain"
set password <configuration removed>
-       set comments "Error (No order found for account ID 1713433947) on Tue May 14 06:17:32 2024 (UTC)"
+       set comments "Error (No order found for account ID 1713433947) on <stripped>
set range global
set enroll-protocol acme2
set acme-domain "fgvm-fw.customer.domain"
set acme-email "nospam@domain.tld"
next
end
```
=> Systeembeheerder patch fortios acme

CHANGELOG.md, lib/oxidized/model/dlinknextgen.rb
Stripped uptime and ntp sync time from running config
Closes issue #3177
=> Dlinknextgen strip1

CHANGELOG.md, docs/Supported-OS-Types.md, lib/oxidized/model/nsxdfw.rb
Added a new model for VMWare NSX DFW, this is different to NSX-T
=> Add NSW DFW support

CHANGELOG.md, Dockerfile
container-image: install x25519 gem package to add extra net-ssh kex
Closes issue #3070
=> container-image: install x25519 gem package to add extra net-ssh kex

CHANGELOG.md, lib/oxidized/model/uplinkolt.rb
=> removing time command from the uplinkolt model

examples/device-simulation/cmdsets/routeros, examples/device-simulation/yaml/routeros_L009UiGS_7.15.2.yaml, spec/model/routeros_spec.rb
Add device simulation and unit test for MikroTik L009UiGS
=> device2yaml for MikroTik L009UiGS

docs/Troubleshooting.md
Small PR - removes extra "d" in the table of contents of `Troubleshooting.md`.
=> Fix table of contents of `Troubleshooting.md`

CHANGELOG.md, examples/device-simulation/cmdsets/junos, examples/device-simulation/yaml/junos_srx300_22.4.yaml, spec/model/junos_spec.rb
=> D2y srx300

CHANGELOG.md, docs/Supported-OS-Types.md, lib/oxidized/model/aos7.rb, spec/model/data/aos7:generic:prompt.yaml
=> 3351 fix aos7 prompt

CHANGELOG.md, lib/oxidized/model/enterprise_sonic.rb, lib/oxidized/model/enterprisesonic.rb
Adds support for Enterprise SONiC
=> Add Enterprise SONiC support

CHANGELOG.md, lib/oxidized/version.rb, spec/refinements_spec.rb
- Warning for ruby 3.5
- Simplify version.rb
=> Fix frozen string  literal

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/support-request.md, CHANGELOG.md, CONTRIBUTING.md, docs/Issues.md
Working on issues is taking a lot of time, I hope introducing templates and rules will help to increase efficiency.
=> Add issue templates to Oxidized

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/support-request.md
Update the URL in issue templates
=> Update URL in issue templates

CHANGELOG.md, docs/Supported-OS-Types.md, lib/oxidized/model/ingate.rb
=> New model for Ingate

CHANGELOG.md, docs/Model-Notes/EatonNetwork.md, docs/Supported-OS-Types.md, lib/oxidized/model/eatonnetwork.rb
=> New model for Eaton Gigabit Network Card M3

CHANGELOG.md, lib/oxidized/model/awplus.rb
bugfix: skip enable password in awplus
=> bugfix: skip enable password in awplus

CHANGELOG.md, lib/oxidized/input/cli.rb, lib/oxidized/input/ssh.rb
=> feat: ssh config block method 'newline'

CHANGELOG.md, lib/oxidized/model/asa.rb, spec/model/data/asa:5512_9.12-4-67_single-context:output.txt, spec/model/data/asa:5512_9.12-4-67_single-context:secret.yaml, spec/model/data/asa:5512_9.12-4-67_single-context:simulation.yaml
Fixes Code scanning alert #5 and #6
=> asa: remove Inefficient regular expression

lib/oxidized/model/junos.rb, spec/model/data/junos:srx300_22.4:output.txt, spec/model/data/junos:srx300_22.4:simulation.yaml, spec/model/data/junos:srx300_22.4_wo_cluster:output.txt, spec/model/data/junos:srx300_22.4_wo_cluster:simulation.yaml
Fix error message introduced by PR #3495
Applying the fix proposed by @systeembeheerder
Closes: #3512
Note - `cfg = cfg.cut_both if screenscrape` does not seam to work correctly. resulting in the prompt being spread through the output. But this is not the topic of this fix.
=> Fix error message introduced by PR #3495

CHANGELOG.md, lib/oxidized/model/edgeos.rb
=> fix edgeOS uri secret

CHANGELOG.md, lib/oxidized/model/model.rb, lib/oxidized/version.rb, oxidized.gemspec
=> Release 0.34.3
