- lib/oxidized/output/file.rb
If we try to fetch a config and no output file can be found, return nil.
Previously, it would try to find the output file by doing a recursive glob search in the config dir.  It would then try to open the file for reading regardless of whether any file was found.
I ran into this when I fired up oxidized for the first time and tried to access a switch config on oxidized-web before it had a chance to collect it.
In this scenario, you get a stack trace on the switch config page (e.g. `http://oxidized.example.com:8888/node/fetch/switch-001.example.com`):
```
Puma caught this error: undefined method `join' for #<String:0x007f3a3c4283f8> (NoMethodError)
/usr/lib64/ruby/gems/2.2.0/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:37:in `rescue in call' …
```
> Fix: Handle missing output file

- lib/oxidized/model/eos.rb
This commit adds the ability to go into Privileged EXEC mode when no password is required by setting `enable: true`.
By default, in Arista EOS you aren't prompted for a password when entering Privileged EXEC (or privilege mode 15) mode. In PR #86, oxidized began always expecting a password.
An unquoted `true` in YAML is a boolean. So when `var(:enabled)` is `TrueClass`, we interpret this as meaning that the user wishes to go into Privileged EXEC mode and does not require a password.
> Add back ability to use passwordless enable on EOS

- lib/oxidized/model/powerconnect.rb
Fixes the issue mentioned in #89 by sending both commands and allowing one of them to fail.
> Fix terminal length issues with older powerconnect switches

- lib/oxidized/model/asa.rb
At the old version it didn't backup things like ldap passwords, which ended up in output marked as '****'.
pre: ldap-login-password *****
now: ldap-login-password wBGqqqCY5SjZ8hY
> Backup full ASA configuration (include passwords)

- extra/syslog.rb
Devices with VSS enabled log Configuration Changes as "%SYS-SW1-5-CONFIG_I" where "SW1" is an identifier of the device in the stack that it came from. (Also added a bit of information of port numbers)
> Add Support for Cisco Devices with VSS

- lib/oxidized/output/git.rb
Using some libraries, in this case pygit2 the initial commit cannot be seen, a change and new commit fixes this.
Adding index.write appears to be a simple fix, as confirmed in this rugged issue:
https://github.com/libgit2/rugged/issues/441
> Some Git libraries cant see initial commit

- lib/oxidized/model/powerconnect.rb
Added a check for 35xx switches
Also extract only on the model number, not the suffix (P or F) as we dont need that.
> Add match for 35xx Switches, tidy up regex

- lib/oxidized/model/ironware.rb
On an ironware device, 'logout' is not recognized, but also with just one " pre_logout 'exit' " it doesn't work.
I don't know if add two pre_logout is the best way to handle it, but actually I don't see an other way to do it.
Added an other post_login to handle pager.
> Add a pre_logout for some devices

- lib/oxidized/model/comware.rb
Some SMB HP switches (V1910, V1920) run Comware, but have the CLI hidden behind a "secret" toggle - it needs to be activated by _cmdline-mode on. The password to enable it varies per model, so this patch introduces a new var, comware_cmdline to contain the password.
Unfortunately we cannot easily autodetect this, as only the "summary" command can give us the model number, but this command is paged and we cannot disable the pager until we are in the full CLI.
Tested on HP V1910-24G-POE.
> Add support for HP Comware SMB switches

- lib/oxidized/model/powerconnect.rb
The pager prompt on the PowerConnect 62xx family does not have a leading space; fixed the expect regex. Also added 6224/6248 to the block ignore regex.
> Add support for PowerConnect 62xx

- lib/oxidized/model/ironware.rb
For some devices, prompt is too strict (the begin of the prompt could be BR-SSH@ ... for example)
> Changed prompt (too strict)

- README.md
- lib/oxidized/source/http.rb
This is my first experience with Ruby so I'm sure this won't be correct so any feedback is appreciated :)
Adds support for http as a source so that lookups of devices can be done against an API. Maintains all the mappings as per other sources (I hope).
> Added support for http as a source

- lib/oxidized/input/ssh.rb
On some Arista devices, Net::SSH will return authentication failure even though command-line ssh works fine. Need to add keyboard-interactive to auth_methods when calling Net::SSH to fix this.
> Add keyboard-interactive SSH auth to fix Arista login failures

- extra/oxidized.service
Oxidized as a service for systemd (Tested on Debian 8)
> Oxidized as a service for systemd

- lib/oxidized/output/git.rb
https://github.com/ytti/oxidized/issues/143
> fix fetching when groups are used and single_repo: true

- lib/oxidized/model/masteros.rb
This model adds support for MRV Master-OS on Opti-Driver with software release 5.5.1.  I don't have access to other platforms running Master-OS to check, but it should probably work there as well.
> Add support for MRV Master-OS

- lib/oxidized/model/routeros.rb
Fixing Regex Warning on Console:
/var/lib/gems/2.1.0/gems/oxidized-0.7.2/lib/oxidized/model/routeros.rb:10: warning: nested repeat operator '+' and '?' was replaced with '*' in regular expression: /\[(?:\d+)?(/
> Fix Regex Warning

- lib/oxidized/model/ironware.rb
The current ironware prompt regexp ```^.+[>#]\s?$``` will match the following line:
```
snmp-server contact The NOC <noc@example.com>
```
This causes the ironware model to truncate the configuration to whatever chunk ssh has returned.  The attached commit is guaranteed to work if the input connection is telnet or ssh. It won't work on a console link, but that's not supported by oxidised anyway.
> ironware prompt matches normal config

- lib/oxidized/model/ironware.rb
the ironware cli is pretty broken and occasionally swallows text without trace. In this instance, when oxidised is run against ironware 7.4 on TIX24 platform with no autoenable, ironware swallows the initial ```skip-page-display``` and then ```show running-configuration``` fails as it hangs on the pager.
this patch should be an effective nop in all other instances where the ironware model is called.
> broken ironware cli occasionally swallows text

- lib/oxidized/model/ironware.rb
ironware occasionally outputs trash.  the gsub to delete \xFF from the input stream breaks ruby.  Better to fix the encoding for the input stream rather than delete arbitrary octets
> smooth over ironware broken encoding

- lib/oxidized/output/git.rb
... otherwise only git write will work; http read still pulls off the unexpanded path name.
> cfg.repo needs to be fixed up with File.expand_path on init

- lib/oxidized/model/comware.rb
Our switch (model comware) contains the line uptime twice (with different case). This patch will ignore both lines correctly.
Example output from switch:
```
#
#
```
> model/comware: ignore lines with uptime (ingore case!) for real

- lib/oxidized/input/telnet.rb
Some of my switches don’t expect any username on telnet. This change
allows me to leave the username field effectively empty for a switch.
> only send username when username is set at all

- lib/oxidized/model/ironware.rb
general expectation that "show run" is at the bottom, and other interesting stuff is on top?
> put "show run" at the bottom of oxidized output

- lib/oxidized/model/ironware.rb
without this patch, ironware stackables show this text at the bottom:
```
Invalid input -> module
Type ? for a list
```
> some ironware devices are fixed config => no modules

- lib/oxidized/model/xos.rb
With the current code Oxidized will get stuck at exit and timeout if there are unsaved configuration in XOS. This will ignore the warning and exit without saving the running configuration.
> Ignore save-config warning after exit in XOS

- lib/oxidized/model/ironware.rb
The behaviour appears to be random.  This patch normalises the output so that git isn't spammed with whitespace commits.
> occasionally ironware randomly inserts extraneous blank lines

- lib/oxidized/model/c4cmts.rb
Support for Arris C4 cable modem boxes.  This works, assuming that the ``remove_secret`` var is expected to remove snmp communities and all other security tokens.
> Add support for Arris C4 CMTS

- lib/oxidized/input/ftp.rb
- lib/oxidized/input/ssh.rb
- lib/oxidized/input/telnet.rb
When I try to run oxidized as a different user, I get permission errors
for oxidized tries to write debug logs (e.g. true-telnet) in current
working directory which in my case is not writable for the
non-privileged user. I think this can be improved by this change.
1) Why would you use CFG.input.debug?.to_s (which in this case will
always be ‘true’) as a prefix at all
2) let’s use the crash directory for the debug output, as we know this
is available and choose a more descriptive name
> use different path for debug logging

- extra/nagios_check_failing_nodes.rb
- lib/oxidized/node.rb
We're migrating to Oxidized at work (from Rancid) and I've made some minor changes to the code. Perhaps they can be useful for others as well.
- It seemed like Oxidized was hanging when we started it, after some troubleshooting we figured it was resolving DNS names (some of the DNS names were not available in the dev environment where we were testing). This patch ads optional debug output when resolving the DNS names.
- ~~Log crashes on hostname instead of on IP (in my opinion more easy to correlate, we manage >1000 devices)~~
- Changes Nagios plugin to prefer CRITICAL state if any critical hosts were found. It used to prefer PENDING (warning) even though there could be both, in which case CRITICAL should win.
I'm not very familiar with Ruby so please let me know if I could improve …
> Some minor tweaks for Oxidized

- README.md
- extra/oxidized-report-git-commits
- lib/oxidized/hook/exec.rb
- lib/oxidized/node.rb
- lib/oxidized/output/file.rb
- lib/oxidized/output/git.rb
- lib/oxidized/worker.rb
this patch exposes the git repo name and the commit ID of the relevant commit in the hook mechanism.  The information is subsequently presented as environment variables.
> expose git repo name and commit oid in hook mechanism and env-vars

- lib/oxidized/model/aosw.rb
On a 6000 series `show inventory` contains a line like `M3mk1 CPU Fan Speed       6490 RPMs`
- this should be stripped
> Strip CPU Fan Speed

- lib/oxidized/jobs.rb
- lib/oxidized/nodes.rb
Several bug fixes:
* Durations array size not being updated when nodes size changes
* Use the ceiling on number of threads, so we overestimate instead of not collecting fast enough
* Sort nodes on reload, to prevent collection stalling
> Improve job queuing

- lib/oxidized/model/opengear.rb
```
~$ cat /etc/version
OpenGear/IM42xx Version 3.16.2 50b5a369 --  Mon Nov 9 12:01:41 EST 2015
```
The physical model is an IM4248 - so I'm using OpenGear as the OS name, for lack of a better choice.
This is the product: http://opengear.com/products/specs/im4200-specs
> Add OpenGear model

- lib/oxidized/model/edgeswitch.rb
Addition of line reject to remove SNTP sync and uptime codes that
change consistently into EdgeSwitch model file
> Removal of SNTP and Uptime comments

- lib/oxidized/model/masteros.rb
- Fixes configuration timestamps in config; "! Configuration saved on", "! Configuration generated on"
> MRV master-os: Ignore configuration timestamps

- lib/oxidized/model/airos.rb
Usually the config is sorted, but sometimes modifying the config moves things around.
Using sort makes for nicer diffs.
> Sort the config for AirOS

- .travis.yml
- Gemfile.lock
- lib/oxidized.rb
- lib/oxidized/cli.rb
- spec/cli_spec.rb
```
$ oxidized -h
Usage: oxidized [options]
-d, --debug          turn on debugging
--daemonize      Daemonize/fork the process
-v, --version        show version
-h, --help           Display this help message.
$ oxidized --version
0.12.2
```
---
There's also 2 commits not exactly related to this feature. If you think I should remove those, just let me know. :smiley:
> show version option

- lib/oxidized/input/ssh.rb
Some network equipment exists that does not want to play nice with ssh.
This adds the vars ssh_encryption and ssh_kex which can be used to tell oxidized to use certain encryption and key exchange parameters so it can connect to these devices.
Fixes #319.
> Add support to specify cipher and kex for ssh connections

- README.md
- extra/oxidized.init.d
- lib/oxidized/config.rb
- spec/cli_spec.rb
this provides a way to isolate the oxidized without touching the user home directory, useful for init.d scripts and others.
```
OXIDIZED_HOME=/etc/oxidized
$ tree -L 1 /etc/oxidized
/etc/oxidized/
├── config
├── log-router-ssh
├── log-router-telnet
├── pid
├── router.db
└── repository.git
```
There is also a `init.d` script template for CentOS and friends. :smiley:
> config root env var

- README.md
- lib/oxidized/hook/githubrepo.rb
- lib/oxidized/node.rb
- spec/cli_spec.rb
- spec/githubrepo_spec.rb
- spec/node_spec.rb
While was possible to create a repository per group, I couldn't find a way to configure a specific `remote` for each group.
~~So, this was the best way I found to configure it:~~
Thanks to @ElvinEfendi this is the config now:
``` yaml
---
output:
default: git
git:
user: Oxidized
email: oxidized@example.com
repo:
routers: /var/lib/oxidized/routers.git
firewalls: /var/lib/oxidized/firewalls.git
hooks:
push_to_remote:
remote_repo:
routers: git@git.intranet:oxidized/routers.git
firewalls: git@git.intranet:oxidized/firewalls.git
```
``` yaml
---
output:
default: git
git:
user: Oxidized
email: oxidized@example.com
repo: /var/lib/oxidized/repository.git
hooks:
push_to_remote:
remote_repo: git@git.intranet:oxidized/repository.git
```
Note also that you can still use the `single_repo` with groups.
> multiple remotes for groups in GithubRepo hook

- lib/oxidized/input/ssh.rb
Newer versions of ssh (>=5.4) support the -W option which makes the
use of netcat obsolete. The -W flag is useful is you want to hop
through a router/switch since they rarely have netcat support.
To use, the ssh_tunnel var needs to be set:
ie:
vars:
ssh_encryption: "blowfish-cbc,3des-cbc"
ssh_kex: "diffie-hellman-group1-sha1"
ssh_tunnel: yes
Some distro's (like RHEL6) have the -W flag backported to their ssh
implementation.
> Add support for ssh tunnel

- lib/oxidized/model/tmos.rb
The configuration pull was missing the config for the different partitions.
> Added function to get configuration of all partitions running on a F5

- README.md
Added libssh2-devel as dependency because otherwise rugged throws following error:
Hook push_to_remote (#<GithubRepo:0x0000000223c5d8>) failed (#<Rugged::NetworkError: Unsupported URL protocol>) for event :node_success
> Added needed dependency for GIT remote functionality via SSH

- README.md
- lib/oxidized/hook/githubrepo.rb
Adds the functionality to provide a ssh public and privatekey to use for SSH GIT connect.
> Ssh key support

- lib/oxidized/model/edgeswitch.rb
The prompt detection was not working on my edgeswitch.  The old regex was a little odd, so I don't know if there is some corner case I'm not accounting for.
My prompts
```
(palmer-elevator.sw) >
```
```
(palmer-elevator.sw) #
```
> Edgeswitch prompt detect not working

- lib/oxidized/model/tmos.rb
If the devices have the pager enabled, the `tmsh list` commands never finish waiting for the pager.
```
config # tmsh -h
usage: tmsh <options ...> <commmand>
-q the shell will not ask the user any questions, this option
does not have an affect in interactive mode
```
> force the F5 TMOS shell to do not ask questions

- lib/oxidized/model/procurve.rb
Fixes #356.
Noticed that `show system-information` works on 2510 and 2610, but you need to use `show system information` on 2900/2910/3800/5400.
The carriage return (`\r`) only appears on 2510 and 2610, and only as the first character of a line -> added `^` to existing `cfg.gsub`.
> Procurve filter control sequences and run `show system information`

- lib/oxidized/model/ipos.rb
This patch normalizes output from various SEOS/IPOS releases to reduce or eliminate (depends on model/release) diff noise. "detail" has been removed from "show hardware detail" as it adds a large amount of constantly changing values. The other changes are explained in the patch.
There are also some minor changes to give each section a more consistent title in form of the show command used and removal of uncommented non-config lines printed by "show configuration".
The resulting output is attached below. Everything that may be sensitive like versions, serials, dates and actual config has been retracted.
ios.rb and junos.rb has been used as a reference but I don't have experience with Ruby, so comments on the code if anything looks weird are welcome.
```
! show chassis
! Current platform is …
```
> IPOS model improvements to fix superfluous diffs

- lib/oxidized/model/ironware.rb
Patch Oxidized ironware.rb to remove another uptime line.
In version 07.2.02, Ironware OS updates this line by 2 or 3 second randomly...
In production, I have 183 version with this kind of diff:
> -! The system started at 08:10:25 GMT+01 Thu Oct 02 2014
> +! The system started at 08:10:27 GMT+01 Thu Oct 02 2014
>
> Patch for ironware 07.2.02kT3e3 version

- lib/oxidized/output/git.rb
When using git output with machine groups, only 'per group git repo' method was managed when trying to access WebUI to get diff or version.
> Fix exception when using git, groups, and single_repo method

- README.md
Hopefully this addresses https://github.com/ytti/oxidized/issues/362
I too had a difficult time figuring out how to enable this feature and felt added documentation would be helpful.
My concern is more about making the configs more widely viewable (via librenms and github), but I did not feel comfortable putting reversible password hashes (ios type 7) in a more shared context.
> Document remove_secret

- lib/oxidized/model/procurve.rb
```
AMS01.LI17.RM.SW01(config)# hostname "AMS01.LI17.RM.SW01"
Note: To be compliant with RFC 1123, the hostname must contain only letters,
numbers and hyphens, and must not start or end with a hyphen.
```
> Dot's in hostnames are frowned upon, but allowed

- lib/oxidized/model/nos.rb
With my version of NOS, I have not 'skip-page-display' like ironware models.
> Add 'nomore' to NOS model for sh run command

- Dockerfile
This describes the exposed ports and the volume according to the `README.md` documentation. 
Though it is possible to mount volumes and expose ports using `docker run`, for several docker management tools it is not possible to expose ports or mount volumes when they are not defined in the `Dockerfile`.
> Added EXPOSE and VOLUME directives

- lib/oxidized/model/acos.rb
Strip out  random value from 
#show version
- Memory
- Current time is
- The system has been up
- Last configuration saved at
#show running-config all-partitions
- Current configuration
- Configuration last updated at
- Configuration last saved at
- Configuration last synchronised at
Another add in cmd 
#show bootimage
it's similar to show version it is more readable
refer to #446
> Strip out  dynamic  value from CLI

- lib/oxidized/jobs.rb
- lib/oxidized/worker.rb
Set 'interval' to '0' to disable polling based on interval. Useful if you only want to poll based on external api requests. 
Solves ytti/oxidized#433
> Added feature to disable polling based on interval

- README.md
- lib/oxidized/model/br6910.rb
The Brocade 6910 switch has a significantly different CLI to Ironware/Fastiron and requires different treatment to pull config.
Major differences are:
1. Not possible to disable paging prior to show running-config. Using expect and looking for "--- [Space] Next page, [Enter] Next line, [A] All, Others to exit ---" then sending "a".
2. No show flash command. Closest is "dir" which shows OS bin files plus config filenames.
3. No separate elevated command prompt.
> Add support for Brocade 6910 (br6910)

- lib/oxidized/model/aosw.rb
Our Aruba controllers have bkup-passwords in the configuration, which seem to change often.  This treats them like the other secret config items on Aruba and redacts the secret.
> Add secret removal for bkup-passwords on Aruba

- lib/oxidized/model/fortios.rb
The FortiOS device will truncate the hostname if it exceeds 24 characters. It will place a tilde (~) in the hostname, either at the end or before a hyphen. This causes a failure with prompt recognition and causes the backup to fail. This change adds a tilde as an identifying character in the prompt.
> FortiOS Issue identifying prompt with truncated hostname

- lib/oxidized/model/junos.rb
- lib/oxidized/model/model.rb
logic was the wrong way around, oops
> strip trailing lines in junos model if ssh_no_exec enabled

- lib/oxidized/input/ssh.rb
- lib/oxidized/model/airos.rb
- lib/oxidized/model/fabricos.rb
- lib/oxidized/model/junos.rb
- lib/oxidized/model/opengear.rb
- lib/oxidized/model/routeros.rb
- lib/oxidized/model/tmos.rb
this cleans up the ssh_no_exec test logic, reverting the individual models back to their original config.
> move ssh_no_exec exec test into exec definition

- lib/oxidized/node.rb
- lib/oxidized/nodes.rb
- lib/oxidized/output/git.rb
- spec/input/ssh_spec.rb
- spec/node_spec.rb
- spec/nodes_spec.rb
There was missing the option for when using groups and defining the repository as a `String` (like, for `default` group).
This should (hopefully) fix some issues, like #473, #497, #334 :smile:
> fix repository path resolution

- lib/oxidized.rb
- lib/oxidized/config.rb
- lib/oxidized/input/ftp.rb
- lib/oxidized/input/ssh.rb
- lib/oxidized/input/telnet.rb
since we have several hundreds of devices, the `oxidized` directory is bloated with log files.
now the logs are kept in a `oxidized/logs` direcotry :smiley:
> create a `logs` dir for all the debug logs

- lib/oxidized/model/screenos.rb
removed current bandwith from get system, because it can create different config versions when there is traffic on the interfaces.
current bw is just stats.
> removed current bw stats from screenos 'get system'

- lib/oxidized/model/asa.rb
Tested on
----
```
! Cisco Adaptive Security Appliance Software Version 9.6(1)5
! Device Manager Version 7.6(1)
!
! Compiled on Fri 03-Jun-16 00:07 PDT by builders
! System image file is "(hd0,1)/asa961-5-smp-k8.bin"
! Config file at boot was "startup-config"
!
!
! Hardware:   ASAv, 2048 MB RAM, CPU Xeon 5600 series 2397 MHz,
! Model Id:   ASAv10
```
Mock text
----
Before:
```
aaa-server TACACS+ protocol tacacs+
reactivation-mode depletion deadtime 1
aaa-server TACACS+ (my_fancy_network) host my_tacacs_host1
timeout 7
key mysecret_key123123
user-identity default-domain LOCAL
aaa authentication http console TACACS+ LOCAL
```
After:
```
aaa-server TACACS+ protocol tacacs+
reactivation-mode depletion deadtime 1
aaa-server TACACS+ (my_fancy_network) host my_tacacs_host1
timeout 7
key <secret …
```
> Cisco ASA Secret filter for TACACS+ key

- lib/oxidized/model/saos.rb
I can retrieve configurations from a Ciena 3911 running saos-06-05-01-0051 with this when I set `saos_shell_set_more_off`.
Looking around, it seems like the command to disable the pager differs based on version and/or model, so I am not sure whether there is a better solution than to use the variable.
> saos: support ssh and different disable-pager command

- README.md
The example for basic http auth doesn't match https://github.com/ytti/oxidized/blob/master/lib/oxidized/source/http.rb#L31, which requires cfg.user and cfg.pass.
> Basic HTTP auth requires user and pass

- lib/oxidized/input/cli.rb
Without this oxidized never closes the connection and potentially blocks additional sessions on some (crap) devices.
> Disconnect input when expected prompt wasn't found

- lib/oxidized/model/pfsense.rb
Noticed when pushing rules to pfSense using its API will the revision time change. This will result in alot of config diffs were revision number is the only thing that has changed.
> pfSense: config pull will not remove its revision time

- README.md
the first container run it's only needed for creating the config file,
so we run it with `--rm` to be removed after its exit
---
fixes #540
> cleanup exited container & better docs

- README.md
Net-ssh no longer supports Ruby version 1.9.3
#553
> Update ruby support in README

- Dockerfile
Pushing to an external git repo using githubrepo hook fails without libssh2-1-dev installed
> Docker: Add missing dependency for Rugged

- README.md
- lib/oxidized/model/planetsgs.rb
This adds support for Planet's Layer 3 [Managed Ethernet Switches](http://www.planet.com.tw/en/product/product_list.php?id2=504).
Their syntax is pretty similar to the one from Cisco, but there are some hacks needed (like `\r` sometimes being echoed before the prompt, and a non-existing `show inventory`, which is why I decided to use a separate model for them.
> add Planet SGS

- README.md
- lib/oxidized/model/planet.rb
So far, only SGS switches were supported.
Now, we check the model type during the `show version` command, and only
execute the `show transceiver details` command in case an SGS switch was
detected (as its not supported on SG models).
We will also strip lines containing the current System Time and Uptime.
These only appear on SG models, but it's a good idea to strip them anyways.
> add support for PLANET SG switches

- README.md
- lib/oxidized/source/http.rb
As always, prefaced by I'm not a ruby guy :)
Tested by someone on gitter channel (well the basics of just adding `http.verify_mode = OpenSSL::SSL::VERIFY_NONE` directly to the http.rb was but I've turned it into a config option and update docs.
> Added option to disable ssl verification checks for http source

- README.md
- lib/oxidized/hook/awssns.rb
This hook can be used to publish messages to an AWS SNS topic.
We are integrating multiple systems with Oxidized by having them listen to SQS queues which are subscribed to SNS topics. When device configuration changes or a backup takes place messages are published to the specified topic.
> New hook: awssns - Publish messages to AWS SNS topics

- lib/oxidized/model/eos.rb
Older versions of EOS output the current time when running the command 'show running-config | no-more'
> exclude time from show run output

- lib/oxidized/model/ciscosmb.rb
Related to #610
Hope it is ok with you @ytti that I took your suggestion and added it here. The current master branch implementation of the user name prompt is broken for all my 300 series Cisco SMB switches and would prefer to get this wrapped up.
> Fix Cisco SMB prompt suggested by ytti

- lib/oxidized/model/ios.rb
hello ytti!
First of all: thanks for this project :)
I encountered the problem that some router-configs do not call their password entries "password" at it is expected in your lib/oxidized/model/ios.rb. This leads to the problem that the secrets are still there due to the fact that the regex does not match.
I took the change to add two substitutions that also match this case.
Do you need anything else from me or is this PR fine for you?
Thank you in advance,
Kind Regards,
Matthias
> delete secret password if it is called secret

- lib/oxidized/model/ios.rb
Do the terminal configure after enable since it might be prohibited in non enable
> IOS: Configure terminal after enable

- lib/oxidized/model/ironware.rb
We have some Brocade MLX devices that are triggering  'raised Encoding::UndefinedConversionError with msg ""\xFF" from ASCII-8BIT to UTF-8"'.  Update the ironware.rb file to ignore undefined UTF8 as well as invalid UTF8
> Ignore undefined UTF8 in ironware.rb

- lib/oxidized/model/fiberdriver.rb
Our fiberdriver devices report a timestamp during 'show running-config', which results in a config diff on every run.  This patch removes the '+! Configuration saved on 2017/01/10 14:21:20' line from the config, as well as a couple other useless status messages
> Mask out configuration date for fiberdriver

- lib/oxidized/model/ironware.rb
Brocade ICX/FCX log fan speed changes like this:
Fan ok, speed (auto): 1<->[[2]]<->3
Fan ok, speed (auto): [[1]]<->2<->3
Remove the current fan speed from the configuration to prevent lots of useless changes from being logged.
> Ignore fan speed changes for ironware

- README.md
We have around ~1000 nodes, and oxidized was taking 30s to do the initial config load.  After adding the 'ip' variable to our CSV, load time dropped to less than 1 second.
> Add suggestion to set `ip` variable in CSV reader

- lib/oxidized/model/aosw.rb
This change allows cleaning of fan speed and temperature from the output of an Aruba S2500-24P switches running version 7.4.1.4 by allowing one or more spaces between the measurement and the units. Previously only one space was permitted in the expression. 
This change should not affect other devices and version as the single space will still be correctly parsed.
> Tweak the white space for cleaning.

- Gemfile
- README.md
- lib/oxidized/manager.rb
- lib/oxidized/source/csv.rb
Add support for GPG encryption for router.db, open for feedback!
> Add GPG support for reading router.db

- lib/oxidized/model/aosw.rb
This is the proposed fix for issue #669. Let me know if there is anything that I need to fix.
This appears to be working correctly for the switch I have in house (S2400-24P). However the model is not working for the Aruba Instant AP (IAP) (virtual) controller. I hope to submit a fix for those once I have it working. The problems with that device appear to be unrelated to these changes as the prompt is incorrect.
> Don't show error is unsupported

- lib/oxidized/node.rb
If an IP address is provided with a netmask, stip the netmask and keep the IP Address.
> feature: support an IP Address provided with a netmask

- lib/oxidized/model/fabricos.rb
Ignore dynamic fields (Uptime/Power/Date) in chassisShow and configShow on FabricOS.
Tested against FabricOS 6.2, 7.1, and 7.4
> Updating fabricos.rb to ignore dynamic fields

- lib/oxidized/model/ironware.rb
Remove \r from the "enable" command. Both \r and \n are interpreted the same on older versions, causing a blank line to be sent as the enable password.
Add a delay between the sending of the "logout" command and each "exit" command. Older devices don't seem to be able to keep up with the speed the commands are sent without a delay.
Fixes #208 and #676.
> Restore compatibility with older versions of IronWare

- lib/oxidized/model/ironware.rb
This works on older IronWare devices without needing a sleep between each pre_logout command.
> Cleaner way to fix older IronWare devices

- lib/oxidized/model/comware.rb
This has only been tested on an HPE 5700.
> Remove (some) secrets from Comware config

- lib/oxidized/config.rb
- lib/oxidized/nodes.rb
- lib/oxidized/worker.rb
Updated PR to include only functionality to increase the job pool by 1 when /next is called.
This feature is gated by the `next_adds_job: true` config option.
Cherry picked commits from this branch https://github.com/ytti/oxidized/tree/next-with-new-thread
> Next with new thread functionality (v2)

- Dockerfile
The existing Dockerfile installs oxidized from a published gem. This does not support building containers for development from any branch.
Proposed changes build the docker image from the git clone you currently have checked out locally.
🐳
> Dockerfile support any branch

- lib/oxidized/model/fortios.rb
added psk and private-key statements to secret removal section since they were not included and they keep changing each "show" command, too, so versioning is not possible.
also introduced variable fortiso_autoupdate like the cmdline variable in comware model to exclude autoupdate section. these section keeps changing a lot and is not really configuration relevant, so no versioning possible.
default behaviour is to include the autoupdate section for backwards compatibility
fixed some formatting misalignments, too.
> fortiOS updates: secret removal, autoupdate messages

- Dockerfile
- README.md
- lib/oxidized/hook/slackdiff.rb
This contribution includes a native [Slack](http://slack.com) hook which can be used to post colourized diffs to a Slack channel of your choice.
When expanded:
Configurable as follows:
```yaml
hooks:
slack:
type: slackdiff
events: [post_store]
token: #########################
channel: "#oxidized-prod"
```
> New Slack hook - posts colourized diffs to a channel

- lib/oxidized/model/ironware.rb
Fix for foundry/ironcore devices. `Password:` in telnet was failing and the device will not login. After this change, oxidized can login to jetcore/ironcore devices.
> Fix for foundry/jetcore username prompt on telnet

- lib/oxidized/model/procurve.rb
Small modifications to get Oxidized work with Aruba 2530 running fw 16.02.0016. https://github.com/ytti/oxidized/issues/731
> Fixed issues with HP Aruba 2530 fw 16.02.0016

- lib/oxidized/model/cumulus.rb
For Cumulus devices, added traffic.conf and ports.conf to files backed up by Oxidized.
(also touched up a weeeeeee white space typo in the SWITCHD comment insertion and some tabs v. spaces)
Tested against devices running Cumulus versions 3.1 and 3.2
> more Cumulus files backed up

- lib/oxidized/model/mlnxos.rb
When pulling Mellanox configs, the values for CPU info, System memory info, Uptime, and "Generated at" constantly change, resulting in a new configuration diff, file save, or git commit every time the configs themselves are fetched by Oxidized. This results in having to sift through tons of commits to find real network configuration changes.
Using the gsub method, these fields are removed when the configs are fetched. Versioning only occurs when a significant change is detected (OS versions, interface changes, inventory serial numbers, etc...)
> make mellanox config versioning much less noisy

- lib/oxidized/model/pfsense.rb
Fix regexp for pfSense (2.3.3-RELEASE) to remove revision time in config pull.
Also remove snort last_rule_upd_time in config pull.
> Update regexp to match pfSense 2.3.3 config files

- extra/auto-reload-config.runit
When running with docker in the background, and no CONFIG_RELOAD_INTERVAL variable set, stdin isn't attached to anything.  The blocking 'read' then fails and config reload is performed repeatedly without a delay
```
I, [2017-03-22T12:01:47.122379 #8997]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
I, [2017-03-22T12:01:47.124551 #8997]  INFO -- : lib/oxidized/nodes.rb: Loaded 2 nodes
sleep: missing operand
Try 'sleep --help' for more information.
Reloading config...
I, [2017-03-22T12:01:47.154603 #8997]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
I, [2017-03-22T12:01:47.156913 #8997]  INFO -- : lib/oxidized/nodes.rb: Loaded 2 nodes
sleep: missing operand
Try 'sleep --help' for more information.
Reloading config...
```
> fix for auto-reload. 'read' doesn't block when stdin not attached

- lib/oxidized/model/ios.rb
This is a port of some of the rancid "show version" parsing.  I tried to
simplify it from the way rancid does it, so it doesn't attempt to guess
the device type, but it does provide IOS version and the type of
processor.
> Adding support for more "show version" commands

- lib/oxidized/model/powerconnect.rb
PR #96 seems to have broken the stripping out the Up Time line in show system on some (older?) versions of PowerConnect firmware. I am seeing the following over and over in my history:
```
-! System Up Time (days,hour:min:sec):       12,02:20:24
+! System Up Time (days,hour:min:sec):       12,03:23:26
```
Switches which put the uptime into a multi-line table work fine, but ones that put it on a single line, such as below, do not:
```
System Description:                       PowerConnect 5448
System Up Time (days,hour:min:sec):       76,01:00:08
System Contact:                           <snip>
System Name:                              <snip>
System Location:                          <snip>
System MAC Address:                       <snip>
System Object ID: …
```
> Remove single line 'Up Time' lines from show system

- lib/oxidized/model/mlnxos.rb
Very little change to fix the Mellanox driver.
I observed that the SSH command never exits correctly at the end of the dumping of the configuration. By adding an extra '\n' to the pre_logout command, it works really better.
> model - mlnxos : patch exit command

- Gemfile.lock
- README.md
- lib/oxidized/node.rb
- lib/oxidized/output/gitcrypt.rb
- oxidized.gemspec
The GIT backend (recommended) will initialize an empty GIT repository in the specified path and create a new commit on every configuration change. The GIT-Crypt backend will also initialize a GIT repository but every configuration push to it will be encrypted on the fly by using ```git-crypt``` tool.
This uses the gem git and system git-crypt interfaces. Have a look at [GIT-Crypt](https://www.agwa.name/projects/git-crypt/) documentation to know how to install it.
Additionally to user and email informations, you have to provide the users ID that can be a key ID, a full fingerprint, an email address, or anything else that uniquely identifies a public key to GPG (see "HOW TO SPECIFY A USER ID" in the gpg man page).
For a single repositories for all devices:
``` yaml
output:
default: gitcrypt …
```
> Add new output GitCrypt

- lib/oxidized/model/firewareos.rb
By design there are two users on the firewareos devices. These are `admin`, and `status`. 
In my testing I confirmed that both users can retrieve the same configuration file, but the difference is that the  `status` is a readonly account, so it can't change anything.
Now, this PR is modify prompt so that of the status user is matched.
For reference here are the prompts:
admin:
```
WG#
```
status:
```
WG>
```
> [Firewareos] Update prompt to include that of the status user

- Dockerfile
- README.md
- extra/update-ca-certificates.runit
I have this specific use case for oxidized docker image.
We got a private github instance that uses a cert signed by our internal CA.
Of course the githubrepo hook fails, since the internal CA isn't trusted.
The simplest solution I could think of is this:
1) Utilise `update-ca-certs` that scans scans `/usr/local/share/ca-certificates/`
2) New environment variable `UPDATE_CA_CERTIFICATE` (similar to `CONFIG_RELOAD_INTERVAL`) to control whether update-ca-certificate should be executed.
Of course this means that the internal CA certs need to end up in the container somehow, but something among the lines of should work.
```
docker run -v /etc/oxidized:/root/.config/oxidized -v /path/to/MY-CA.crt:/usr/local/share/ca-certificates/MY-CA.crt -p 8888:8888/tcp -e UPDATE_CA_CERTIFICATES=true -t …
```
> Adding support for internal CA certs

- lib/oxidized/model/firewareos.rb
Fix to #813.
I decided to play safe - `/^([\w.@-]+[#>]\s?)$/`.
Perhaps worth waiting for @Alexandre-io just a couple of days to see if he has anything to add.
> Watchguard prompt - fix to #813

- lib/oxidized/model/airos.rb
adds the firmware version number to the comments part of the config.  I also cleaned up whitespace in the file.
> added firmware version to airos

- README.md
- lib/oxidized/model/siklu.rb
I've tested this file on a Siklu EH-1200FX radio, however that's the only model I have, and it pulls the configuration without error.
I'm looking for feedback with grabbing the running-configuration versus the startup-configuration, though. The only difference in the output is that with the startup-configuration command you get a line at the beginning that tells you what version created the configuration file. I feel like this might be important to have, however I'd also like to know if changes were made to the running config that weren't saved.
Example of the line in startup-configuration output:
`
####====####  Generated by ver. 7.0.0.16739, convert ver. 12`
> Create siklu.rb to add support for Siklu EtherHaul radios

- README.md
- lib/oxidized/config.rb
- lib/oxidized/config/vars.rb
- lib/oxidized/node.rb
Hi.
I needed specific credentials for models, and I wanted to keep my groups not dependent from the model.
It's works quite well, but I only tested it with ironware, junos and apc_aos equipments as I only have these equipements.
It works well with the model_map list, so the model in the input can match one on these entries in the model_map list.
Thanks.
> Added support for model specific credentials

- lib/oxidized/model/quantaos.rb
This was default with my Quanta LB4M
Software Version............................... 1.1.0.8
Operating System............................... VxWorks 6.6
> Quanta: accept shorter username prompt

- lib/oxidized/model/routeros.rb
Noticed stale "active users" in some versions of RouterOS, added the CLI "quit" command to cleanly exit.
Tested it for 2 days on 5 devices without any issues.
> added a pre-logout command to quit cleanly from routeros

- lib/oxidized/model/vrp.rb
Added possibilty to remove lines of configration containing secrets.
The displayed encrypted PIN changes with every call of "display current-configuration all" and makes versioning impossible.
Other secrets are also stored in an encrypted format (%^%#...%^%#)
> Added secret removal to vrp model

- lib/oxidized/model/fortios.rb
The output of "diagnose autoupdate version" contains the FortiGuard
Distribution Server (FDS) address. This IP Address changes several times
per week and therefore versioning is hardly possible. Added a line to
remove the IP Address when fortios_autoupdate is set true.
See #727 for the initial idea of fortiso_autoupdate variable
> fortios.rb fortios_autoupdate remove FDS Address

- lib/oxidized/model/planet.rb
Some Planet Switches (at least from their industrial line)
show the system temperature on the 'show version'
command, so strip it from the output, too.
> Planet: remove temperature from output

- lib/oxidized/model/ironware.rb
When setting up oxidized I kept getting updates for my Brocade ADX loadbalancers due to config byte size changes and Fan speed and temperature changes. I've modified ironware.rb to remove these.
There's just one side effect, the byte size removal also removes the bytes from image sizes in "show flash" on other Brocade devices. For me thats not a problem but for others it might be. Feel free to improve my regexp where possible :).
> Fixes for Brocade ADX loadbalancers

- extra/oxidized-report-git-commits
Update report git commits script to use bare repo instead of working directory, dropping the need for a temporary directory and the clone/pull process.
> Update report git commits script

- lib/oxidized/model/panos.rb
If you exit PanOS CLI with exit, the SSH session will be exited, but the user session inside PanOS keeps open until the session timeout occours. If you're using quit to end the SSH session, the user session will be closed too and no idle sessions keep lingering around.
> changed panos logout from exit to quit

- lib/oxidized/model/routeros.rb
This runs export with the hide-sensitive using the Mikrotik command to remove secrets from the config pulled from the device. 
Closes #900
> RouterOS: Use `/export hide-sensitive` when `remove_secret` is set in Oxidized

- lib/oxidized/model/netgear.rb
- match the User: prompt on telnet
- fix the sending of enable password
- don't issue exit/quit commands on logout, because an
additional prompt may or may not be encountered
Closes #920
> Fixes for Netgear

- extra/oxidized.service
Found with our setup this helped the service to come up on boot.
Optional so commented out.
CentOS7
thanks
> Add After/Wait to service file

- extra/oxidized.service
Puma docs @ https://github.com/puma/puma/blob/master/docs/signals.md state that SIGTERM (which systemd uses by default) stops single worker while SIGINT stops the whole cluster. Additionally a hang was observed when using the default SIGTERM when shutting down the unit. Switching to SIGINT worked as expected.
This pull request simply changes the systemd unit to use SIGINT signal.
> Change SIGTERM (default) to SIGINT when stopping oxidized systemd unit

- lib/oxidized/model/xos.rb
Hello,
Backup of XOS switches is incomplete without policies: they are the separate .xsf files on the filesystems. They are used for ACLs, routing policies etc. 
Fortunately, there is a 'show policy detail' command displaying policy files content. It shows only policies actually used in a config so it fits perfect into backup routine
> Extreme XOS policies backup

- extra/oxidized.service
Follow on from #760
Oxidized relies on network connectivity so updated the oxidized.service file to reflect this + small doc update within the same file.
> Updated oxidized.service file to rely on networking

- README.md
- lib/oxidized/model/weos.rb
We use Westell devices in our network (Westell 8178G and Westell 8266G), so I wrote a driver.
SSH daemon is broken on those devices, so only telnet-based shell works.
> Driver for Westell 8178G and Westell 8266G devices

- README.md
- lib/oxidized/model/enterasys.rb
Used for the lanparty Frag-o-Matic
Tested with the following switches:
- Enterasys Securestack C3G124-48
- Enterasys Securestack B3G124-48
This adds basic support. We will try and maintain this file if we find valuable additions in the future.
> Create enterasys.rb (C3/B3 series switches)

- lib/oxidized/model/fortios.rb
I've noticed there are sometimes secondary keys and rsso-secrets, so I propose we also replace them (worked for us)!
> Exclude secondary-secrets and rsso-secret

- README.md
- lib/oxidized/hook.rb
- lib/oxidized/hook/exec.rb
- lib/oxidized/node.rb
- lib/oxidized/worker.rb
This PR includes a new event `nodes_done` for a complete cycle.
Example of a run:
```
D, (...) loads of logs lines (...)
D,  lib/oxidized/node.rb: Oxidized::SSH ran for 10.X.X.206 successfully
D,  lib/oxidized/job.rb: Config fetched for 10.X.X.206 at 2017-08-15 14:50:54 UTC
D,  lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 3 of 3
D,  lib/oxidized/worker.rb: Running :nodes_done hook
D,  Exec: Execute: "env >> /tmp/nodes_done.log"
D,  lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 3
D,  lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 3
```
closes #178
> all nodes done hook

- lib/oxidized/model/ftos.rb
On older firmware revisions FTOS can trigger encoding errors when listing hardware inventory.
This patch replaces the invalid data (which is normally \uFFFD) with the empty string.
> Fix Encoding::UndefinedConversionError from FTOS

- extra/oxidized-report-git-commits
When running aginst a new repo, OX_REPO_COMMITREF points to the initial
commit and OX_REPO_COMMITREF~1 is invalid. Git diff fails with error:
unknown revision or path not in the working tree
> Fix #1001: Use git show instead of git diff for reporting changes

- README.md
In PR #995, I was a bit confused on the support for Alcatel-Lucent (Nokia) devices, as the README only mentioned support for the omniswitch platform.
> Update README to indicate that Alcatel Lucent routers running SR OS (TiMOS) are supported.

- lib/oxidized/model/fortios.rb
Everyday the IPS URL db is updated and so the configuration is "changed". I believe this information spams the diff config and my team and I just decided to replace it by a unique string. Maybe instead of putting this in the :secret, we could create an other var or something that can be specified in the conf. Don't know what you think of this ;-)
> Hide db last update

- lib/oxidized/model/ios.rb
Some older IOS builds have lower case telnet prompts.
username: instead of Username:
password: instead of Password:
So I've changed the match to be case insensitive.
> Some older IOS uses lowercase in the telnet prompt

- lib/oxidized/node.rb
- lib/oxidized/nodes.rb
- lib/oxidized/worker.rb
Currently, the email field is not being passed from the REST API to the worker. This prevents, in my case, Gitlab from properly displaying the commit author in the commit history/blame.
I corrected this by adding an "email" field to the node class, and modifying the worker to pass through the "email" option to the node.
> Fix issue where "email" JSON field is not being passed through from REST API

- lib/oxidized/model/ios.rb
- lib/oxidized/model/iosxr.rb
At least some versions of ios output a timestamp after each input command. This will cause Oxidized to have a different version of the config for every poll of the device. I added the per-session command to suppress timestamps.
fixes #1022
> Suppress timestamp response to ios commands

- lib/oxidized/model/netgear.rb
I have Netgear switch with hostname like "switch.example.net" which results in prompt like:
(SWGE001-STO-DC1.ita.local) #
This is not considered valid by current prompt regex, so I added . as a valid character in the character class.
> Netgear model: Permit . as valid character in prompt

- lib/oxidized/model/procurve.rb
When trying to connect to a HP Procurve Switch with stacking enabled,
you are asked to choose which switch to connect to to manage.
This patch makes it so that if this question is encountered, just press
"Enter" to choose the stack commander.
This won't make backing up stack members work (they still need to be
configured seperately and given IP addresses, making stacking useless)
but at least it makes it possible to back up a commander in a stack
seperately.
Fixed #1070
Credit to @stiltzkin10 for this fix.
> Procurve: Handle switch selection for stack commanders

- README.md
- docs/Sources.md
- lib/oxidized/source/csv.rb
Fixes https://github.com/ytti/oxidized/issues/1082
> GPG bug fix

- extra/oxidized.service
There is an issue with oxidized and correctly terminating when a user stops the service.
Unfortunately the root cause of this issue has yet to be identified, and it may
have to do with specific versions of Ruby gems.
As such, the workaround is to use a SIGKILL to kill the oxidized/puma service
instead of a SIGINIT.
Note: This does not solve the issue with manually starting the oxidized
daemon and using Ctrl + c to stop it. The solution here is to then
press Ctrl + Z, then manually "kill -9 <PID>".
Fixes: #864
> Workaround: Allow Oxidized service to be stopped.

- docs/Model-Notes/JunOS.md
- docs/Model-Notes/README.md
I've been testing this with an SRX220H2 and should be applying this to several EX and QFX switches and our MX series routers.
So far only the J2300 has shown any errors and that was due to _omit_ within the _show configuration | display omit_ command. Its running such an old version of JunOS the command doesn't exist.
It isn't extensively tested, to ensure its locked down 100%, but at least Oxidized won't be accessing with root privileges.
It was assembled using Junipers own documentation on their [knowledge base](## https://kb.juniper.net/InfoCenter/index?page=content&id=KB23038&actp=METADATA)
> Added documentation for setting up JunOS with Oxidized

- docs/Configuration.md
- docs/Model-Notes/README.md
- docs/Model-Notes/XGS4600-Zyxel.md
- lib/oxidized/config.rb
- lib/oxidized/input/ftp.rb
Having refactored the code/docs.
The Xyzel XGS4600 series require an active FTP session to enable the config file to be pulled.
Unfortunately only admin can pull the config and thus a CLI version is in the works.
Hopefully the passive/active option will be helpful for other users
> FTP Passive/Active modes & Xyzel XGS4600 series Docs

- lib/oxidized/model/aosw.rb
Per discussion in https://github.com/ytti/oxidized/issues/1000#issuecomment-363444488. Fixes: #1000
> [AWOS] Make the space between # mandatory rather than optional in the promt

- lib/oxidized/model/procurve.rb
Sanitized output:
```
Power Supply Status: 
PS#    Model       State        AC/DC  + V      Wattage
---- --------- ------------- ----------------- ---------
1   Unknwn    Powered         AC 220V          1500
2   Unknwn    Powered         AC 220V          1500 
2 /  2 supply bays delivering power.
Total power: 3000 W
```
Of course you see `unknwn` but that is addressed in latest firmware release.
Thanks!
> [procurve] add show commands

- docs/Model-Notes/Comware.md
- docs/Model-Notes/README.md
Fixes: #1171 
Unless someone adds support for pre_login call then this can be used by people to configure devices correctly to not trip up over prompt detection.
> docs: Added model note for 3com comware

- CHANGELOG.md
- README.md
- TODO.md
- docs/Configuration.md
- docs/Hooks.md
- docs/Model-Notes/AireOS.md
- docs/Model-Notes/ArbOS.md
- docs/Model-Notes/Comware.md
- docs/Model-Notes/JunOS.md
- docs/Model-Notes/README.md
- docs/Model-Notes/VRP-Huawei.md
- docs/Model-Notes/XGS4600-Zyxel.md
- docs/Outputs.md
- docs/Ruby-API.md
- docs/Sources.md
- docs/Supported-OS-Types.md
Lint markdown docs for consistency, introduce language hints on code blocks for syntax highlighting where missing, and correct a typo or two.
> Lint markdown docs

- Dockerfile
Refresh Dockerfile to resolve multiple issues:
* Bump base image from 0.9.18 to 0.10.0 (now xenial based).
* Remove dependency on ppa:brightbox and use xenial ruby2.3
* Split build into 2 stages to backport libssh2 1.7.0 which is
needed for githubrepo hook but is not available in xenial
* Misc cleanup and comments
This is meant to supersede #1039 by taking a more elegant approach, and closes #1204
> Refresh Dockerfile

- docs/Hooks.md
- lib/oxidized/hook/githubrepo.rb
This breaks out the change introduced by @yeled in #1039 to introduce OXIDIZED_SSH_PASSPHRASE support apart from the Dockerfile update contained in the same PR. 
A revised Dockerfile that is meant to supersede the changes introduced in #1039  has been submitted as #1207 - this feature depends on it being merged.
Convenience submission. Completely untested and assumes the original change set was valid.
> Introduce support for OXIDIZED_SSH_PASSPHRASE for githubrepo hook

- docs/Supported-OS-Types.md
- lib/oxidized/model/aricentiss.rb
- lib/oxidized/model/supermicro.rb
- lib/oxidized/model/supermicro2.rb
_Change is largely cosmetic, but untested. Assumes correctness of base PR #1036._
* Renames `supermicro.rb` to `edgecos.rb` to reflect which os type is actually being supported.
* Introduces a backward compatibility shim `supermicro.rb` which links to `edgecos.rb`.
* Renames proposed `supermicro2.rb` from #1036 to `aricentiss.rb` to reflect which os type is actually being supported. No backward compatibility shim here as this support is brand new.
* Documents the modules supported by each of the two types.
> Supermicro support refactor (extends #1036) 

- docs/Supported-OS-Types.md
- lib/oxidized/model/supermicro2.rb
This model (and possibly others) runs an OS with a different set of commands than the Supermicro model that already exists.
I didn't find anything resembling a name of the OS, so I just used the model name for the class. If you think this name is fine I can update the PR to add it to the README. If not, please suggest a better name (maybe just Supermicro2?).
> Add support for Supermicro SSE-G48-TG4

- lib/oxidized/model/powerconnect.rb
> Skip the word 'encrypted' in Powerconnect password masking

- lib/oxidized/model/junos.rb
- Fix the `encrypted-password` sanitization to keep the `encrypted-password` command
- Add `pre-shared-key` sanitization for `ascii-text` and `hexadecimal`
- Add `authentication-key` sanitization
I was able to test the encrypted-password and pre-shared-key, I do not currently run BGP within my homelab.
However I know it's just `authentication-key` as I've done it for peering requests in other environments.
> add secrets to sanitize in JunOS

- lib/oxidized/model/edgeos.rb
- lib/oxidized/model/vyatta.rb
Fixes https://github.com/ytti/oxidized/issues/1221
There are probably more, such as the MD5 authentication for BGP, etc. I don't have that configured in my environment so I am unable to make sure it's right.
However, the ones below should cover the most high risk secrets
Tested on Ubiquiti EdgeRouter X and VyOS devices.
> add removal of secrets in edgeos, vyatta

- lib/oxidized/model/dnos.rb
Manage Dell Network OS 6  extending the `dnos` model. May correct #804.
> Handle Dell N2000 switches (dnos6)

- lib/oxidized/model/firewareos.rb
Default prompt in firewareos cluster mode look like this :
```
WG<master># 
```
I had to rollback to the first pattern to avoid breaking the xml with `>`
> Fix prompt pattern for firewareos clusters

- lib/oxidized/model/aricentiss.rb
Always issue both 'no cli pagination' and 'no cli pagignation'.
Conditionally issuing only the correct variant would require sending the
same number of commands to the switch ('show version', 'no cli
pagi(g)nation') and also require extra logic in the model.
Additionally, always issuing both removes the need for storing
information about what OS versions require which command in the model.
> AricentISS: Fix pagination for old OS versions

- README.md
Pending confirmation that the [upstream bug](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=227118) in the package is resolved. Updates documentation to reflect that a FreeBSD package is available as alternative to RVM + gems installation.
> Improve freebsd documentation (closes #1247)

- extra/oxidized.logrotate
Assuming `log:` is set to:
> log: /var/log/oxidized/<something>.log
/var/log/oxidized will need to be owned by the user running oxidized
> Add logrotate file

- lib/oxidized/model/hpebladesystem.rb
- disable Last Update from NTP in Show Network, because it produced a new version with every backup (show network)
- disable parsing of "----More----", it is better to user "Script Mode" (cfg :telnet, :ssh) -> post_login
> updates in hpebladecenter model

- Dockerfile
Change container build order to install dependencies for hooks first so that more layers are re-usable during subsequent rebuilds.
> reorder dockerfile gem installation

- docs/Hooks.md
- lib/oxidized/hook/githubrepo.rb
Utilizes the [credentials](https://github.com/libgit2/rugged/blob/master/lib/rugged/credentials.rb) seeding of rugged to extract the correct username from the repository URI depending on configuration. Adds debug information.
> refactor githubrepo credential handling (closes #1240)

- lib/oxidized/model/fortios.rb
Disable output paging on FortiOS, speeding up the execution and avoiding job timeouts when using SSH.
New take on PR #894 without changing the device configuration.
> Disable paging for "show full-configuration" on FortiOS

- spec/cli_spec.rb
ensure asetus is initialized during Oxidized::CLI tests so that the test does not randomly fail under unusual execution order
> ensure asetus is initialized in cli_spec.rb

- .rubocop_todo.yml
- lib/oxidized/manager.rb
- lib/oxidized/source/csv.rb
- lib/oxidized/source/http.rb
- lib/oxidized/source/sql.rb
While there is some [discussion](https://bugs.ruby-lang.org/issues/10177) about `has_key` and `has_value` methods, the bulk of oxidized codebase currently uses these verbose variants. This eliminates the few short variants currently in use to make the entire codebase consistent.
Passes `Rubocop` with:
```yaml
Style/PreferredHashMethods:
EnforcedStyle: verbose
```
> standardize on verbose hash methods

- README.md
Rubies under 2.0.0 are not supported since Oxidized 0.13.0
> remove mention of ruby 1.9.3 from CentOS instructions in favor of 2.0

- docs/Supported-OS-Types.md
- lib/oxidized/model/ndms.rb
**supported devices:**
- Keenetic 4G (KN-1210)
- Keenetic Giga (KN-1010)
- Keenetic Lite (KN-1310)
- Keenetic Omni (KN-1410)
- Keenetic Start (KN-1110)
- Zyxel Keenetic
- Zyxel Keenetic II
- Zyxel Keenetic III
- Zyxel Keenetic 4G
- Zyxel Keenetic 4G Rev.B
- Zyxel Keenetic 4G II
- Zyxel Keenetic 4G III
- Zyxel Keenetic 4G III Rev.B
- Zyxel Keenetic Air
- Zyxel Keenetic DSL
- Zyxel Keenetic Extra
- Zyxel Keenetic Extra II
- Zyxel Keenetic Giga
- Zyxel Keenetic Giga II
- Zyxel Keenetic Giga III
- Zyxel Keenetic Lite
- Zyxel Keenetic Lite Rev.B
- Zyxel Keenetic Lite II
- Zyxel Keenetic Lite III
- Zyxel Keenetic Lite III Rev.B
- Zyxel Keenetic LTE
- Zyxel Keenetic Omni
- Zyxel Keenetic Omni II
- Zyxel Keenetic Start
- Zyxel Keenetic Start II
- Zyxel Keenetic Ultra
- Zyxel Keenetic Ultra II
- …
> Basic support for NDMS OS (Zyxel Keenetic)

- .github/no-response.yml
Configuration for the [Probot: no-response](https://github.com/probot/no-response) GitHub app that automatically closes issues tagged with `user_pending` after 21 days if they haven't received any feedback from the original author.
Requires a collaborator to activate the GitHub App at https://github.com/apps/no-response
> implement probot no-response

- lib/oxidized/model/dnos.rb
Gsub out the uptime which changes constantly, and remove the output of "show system" which duplicates the info from "show version" and contains fan speed data which isn't helpful (and causes a bunch of spurious commits)
> Alter DNOS config. Remove constantly changing info

- lib/oxidized/source/csv.rb
In  #1095, node_want was introduced to source loading, and is passed to all sources - however, while `http.rb` and `sql.rb` have been adjusted to do something meaningful with the parameter, `csv.rb` does not expect it, not has any use for it (the whole file needs to be processed to build a node list).
Allow and ignore node_want in `csv.rb`.
> allow node_want in csv.rb and ignore it (closes #1319)

- docs/Configuration.md
- lib/oxidized/config.rb
- lib/oxidized/node.rb
- spec/input/ssh_spec.rb
Based off the `no-resolve` branch that was created to address #599 but never had a chance to be reviewed and tested. Includes documentation for the `resolve_dns` knob and an additional case in the ssh spec that validates its behavior.
Completely untested.
> Introduce resolve_dns knob (closes #599)

- lib/oxidized/node/stats.rb
- spec/node_spec.rb
- spec/spec_helper.rb
This PR implements the following changes:
* Adds additional counter variables to allow the config download success and failure count to remain accurate beyond  the 11th run.
> Add counters to correctly track the number of runs, successes and failures

- bin/oxidized
- lib/oxidized/model/nxos.rb
This PR implements the following changes:
* Postprocessing of NXOS configs to have consistent Unix style line endings, remove lines containing exclusively a prompt, and comment all non-configuration lines. This allows the configuration taken from Oxidized to be directly supplied to a switch to revert to a specific version.
* Corrects inability to enable debug mode due to spelling error.
> Fix debug mode, properly comment NX-OS configs and normalize their line endings.

- CHANGELOG.md
- lib/oxidized/model/procurve.rb
Found this enable snippit on another device, fixed login on a couple of my older devices.
> Enable 'enable' support for HP Procurves

- README.md
Oxidized-web 0.10.2 requires gcc-c++ to be able to install the gem in Centos 7. Updated docs.
> gcc-c++ needed in oxidized-web 0.10.2

- lib/oxidized/model/comware.rb
This change works for newer HPE Comware model switches and *shouldn't* cause any issues with the previous Comware models although past functionality hasn't been tested as I don't have an older model.
> Updated HPE Comware - Issue #611 Fix

- CHANGELOG.md
- lib/oxidized/model/ciscosmb.rb
Moves the uptime filter from :secret to `show system` which actually produces the message in `ciscosmb.rb`. This ensures the uptime line gets scrubbed even if secret scrubbing is disabled.
> ciscosmb uptime filter is for show system

- CHANGELOG.md
- lib/oxidized/model/dlink.rb
Relaxes prompt expectations for D-Link model
Closes #1389
> relax d-link prompt expectations, closes #1389 

- CHANGELOG.md
- lib/oxidized/model/edgecos.rb
Scrub temperature in `edgecos.rb` from `show system` output.
Closes #1394
> scrub temperature from 'show system' in edgecos, closes #1394

- CHANGELOG.md
- lib/oxidized/model/ciscosmb.rb
Scrub uptime in `ciscosmb.rb` more carefully
Closes #1398
> Scrub uptime in ciscosmb more carefully, closes #1398

- CHANGELOG.md
- lib/oxidized/model/netgear.rb
Tested on Netgear M5300's running firmware 10.0.0.53, 11.0.0.23 & 11.0.0.31
Fixes issue with Netgear login via telnet.
The password prompt wasn't recognised after the latest update.
Closes issue #1385 for Netgear devices
> added telnet password prompt detection for Netgears

- lib/oxidized/model/netgear.rb
Clearer implementation for the `enable` var in netgear.rb.  The logic is backwards-compatible:
* Any string (including empty string) sends "enable", waits for password prompt, sends the string
* `true` sends "enable" only, does not expect password prompt
* `false` or `nil` does not send "enable"
Discussion in tail end of #1413
> Tidy up logic for sending 'enable' with or without password

- lib/oxidized/worker.rb
- [x ] Passes rubocop code analysis (try `rubocop --auto-correct`)
- [NA ] Tests added or adapted (try `rake test`)
- [NA ] Changes are reflected in the documentation
- [NA ] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)
Standardises the syslog messages in `worker.rb` by prefixing a node name with it's group.
`node.group/node.name` is now shown in all logs generated by `worker.rb`
> adding node group to worker logs

- lib/oxidized/model/coriantgroove.rb
Coriant reduced the maximum line length from 65536 chars to 4000. Specifying `set -f cli-config cli-columns 65535` returns an error on recent software.  Changing this to 400 chars fixes the problem.
There are no open issues about this.  Discovered on internal testing.
> Coriant Groove FP3.x only accepts a line length of 4000 chars

- lib/oxidized/model/ftos.rb
Fixed secret regex which would strip config after secret string
(like "privilege 15") and which would not match on:
"bsd-username test secret $1$FAKESTRINGblahblah" which is created
whenever username secret is created.
Added regex to filter password hashes for configs using
password 7 instead of secret such as:
username test password 7 8888blahblah8888 privilege 4
> FTOS secret filtering fixes

- lib/oxidized/model/fortios.rb
Just made first .* portion of regex not greedy. The multi-line match would eat all config between the first and last certificate in my configs when I turned on remove_secret. Also adjusted spacing slightly so that there would always be a single-space before "<configuration removed>".
> Fortios secret filtering: Fixed greedy regex's eating configuration

- extra/oxidized.service
Not sure what the rubocop stuff is, sorry :(
Not sure what the rake test stuff is, sorry :(
None required?  I inserted a comment into the modified file itself
Whoops. No :(
Added verbiage to set OXIDIZED_HOME correctly under Debian 8.8 w/systemd
Closes issue #1441  and issue #1440
> Added verbiage to set OXIDIZED_HOME correctly under Debian 8.8 w/systemd

- lib/oxidized/model/fortios.rb
format of the strings to be excluded/removed:
```set md5-key <integer_id> "ENC <md5_key>"```
Related PR: #1010
> fortios: mask "md5-key" secrets

- oxidized.gemspec
Pessimistic lock for net-telnet to 0.1 as 0.2 depends on Ruby 2.3+
Make dependency on net-telnet unconditional since the gemspec is evaluated as bundle time - avoids release master environment drift from having impact on published gems (0.21.0 release had no net-telnet dependency in the published gem, but 0.22.0+ does).
Closes #1472
> pessimistic net-telnet lock on 0.1 as 0.2 requires ruby 2.3+

- lib/oxidized/model/axos.rb
I have tested this on a Calix AxOS E5-16F, backups config perfectly. The first line in the config file is the command to show the config, i don't know how to remove this, so if someone tells me i can update it and test again.
Add configuration backup support for Calix AXOS operating system, Tested with Calix E5-16F
> Support for Calix AXOS Devices

- CHANGELOG.md
- Dockerfile
Adds ```sequel``` and ```gpgme``` gems to Dockerfile to enable more functionality out of the box.
Closes #1484
> add sequel and gpgme source deps to Dockerfile

- CHANGELOG.md
- docs/Configuration.md
- docs/Model-Notes/Nokia.md
- docs/Model-Notes/README.md
- docs/Model-Notes/Viptela.md
- lib/oxidized/input/ssh.rb
ssh keepalive support was turned on in #1276 but appears to have side effect in rare edge cases, such as #1482
This makes ssh input keepalive setting configurable to deal with rare devices which don't correctly support keep-alive
Closes #1482
> add configurable per node ssh_no_keepalive boolean

- lib/oxidized/model/fortios.rb
Adds secret field to FortiOS.rb required for Fortiswitch units (END RSA PRIVATE KEY).
Closes issue #1510
> Add fortios fields to be masked by remove_secret flag

- lib/oxidized/source/http.rb
Current issue:
When using an `http` source and `secure: false`, oxidized gives error:
```
I, [2018-07-30T01:54:56.900233 #128]  INFO -- : Oxidized starting, running as pid 128
I, [2018-07-30T01:54:56.923148 #128]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2018-07-30T01:54:56.923327 #128] FATAL -- : Oxidized crashed, crashfile written in /root/.config/oxidized/crash
uninitialized constant Oxidized::HTTP::OpenSSL
```
We require the 'openssl' package.
> Require openssl for use of 'OpenSSL::SSL...' constants

- CHANGELOG.md
- docs/Supported-OS-Types.md
- lib/oxidized/model/comtrol.rb
> Add comtrol model

- CHANGELOG.md
- lib/oxidized/model/tmos.rb
When running an F5, you can configure Advanced Routing, this in generally BGP. This BGP configuration is done through `imish`, which drops you in ZebOS. This configuration is useful to capture/audit for changes as it affects traffic as much as any other configuration
> capture ZebOS configuration from F5

- lib/oxidized/model/tmos.rb
- [] Tests added or adapted (try `rake test`)
- [] Changes are reflected in the documentation
In #1501 ZebOS is captured, however ZebOS is used when the F5 has Dynamic Routing licensed + provisioned. This adds a check for the `/config/zebos` directory before it attempts to read the ZebOS configuration.
Makes #1501 more robust
> tmos: ZebOS configuration should only be captured if it's configured

- CHANGELOG.md
- Dockerfile
Bumps the base container to phusion/baseimage v0.11, based on Ubuntu 18.04 (Bionic Beaver). This distribution provides the requisite libssh2 version neccesary for compatibility with Github (`githubrepo` hook) out of the box. As a consequence, we can revert from the two-stage build process that included building a libssh2 1.7 backport first to a single-stage build.
> Bump Dockerfile to phusion/baseimage v0.11

- Dockerfile
Add libicu next to libicu-dev to Dockerfile to prevent it from being autoremoved after build.
Closes #1531
> add libicu60 next to libicu-dev so its not autoremoved

- CHANGELOG.md
- lib/oxidized/model/cumulus.rb
This PR introduces a new feature: privilege escalation for cumulus devices.
If enable is set for the node to true, we will send a command to sudo up to root, then provide the node password.
If it is set to anything else, we will su to root, using the enable variable as the root password for the device.
This closes issue #1069.
> Sudo for cumulus

- CHANGELOG.md
- Dockerfile
Add the `sqlite3` and `mysql2` gems to Dockerfile for `sequel` (used by sql source) to be useful out of the box. 
Installs most gems with `--no-docs` and `--no-ri` option as well as removes more build dependencies after build to reduce size of resulting container.
Closes #1526
> add sqlite3 and mysql2 drivers for sequel to Dockerfile

- CHANGELOG.md
- lib/oxidized/model/dlink.rb
D-Link defaults to using the model of the device as the hostname, which is displayed as prompt. Add support for forward slash (`/`) to accommodate D-Link DES 1210-10/ME.
Closes #1541
> Dlink fast forward slash

- lib/oxidized/model/ftos.rb
Some additional sensitive data needed to be removed from ftos configs when using remove_secret: true.
Before:
```
radius-server host 192.168.1.1 key 7 somehashhere
snmp-server host 192.168.1.2 traps version 2c somecommunitystring udp-port 162
```
After:
```
radius-server host 192.168.1.1 key 7 <hash hidden> 
snmp-server host 192.168.1.2 traps version 2c <community removed> udp-port 162
```
> adding more gsubs for removing sensitive config on FTOS/DNOS

- docs/Hooks.md
`rubocop` output resulted in a set of changes, but not to any files I had touched.  This is purely a documentation update.  I left the rubocop auto-correct changes out of this commit/PR as I don't want ot mess with anything currently in flight but outside the scope of this PR.
rubocop output:
```
Offenses:
extra/syslog.rb:51:35: C: [Corrected] Style/TrailingCommaInLiteral: Avoid comma after the last item of a hash.
/(.*)\.ip\.fi/       => '\1',
^
extra/syslog.rb:57:48: C: [Corrected] Style/TrailingCommaInLiteral: Avoid comma after the last item of a hash.
:nxos  => /%VSHD-5-VSHD_SYSLOG_CONFIG_I:/,
^
lib/oxidized/node/stats.rb:13:30: C: [Corrected] Style/TrailingCommaInLiteral: Avoid comma after the last item of a hash.
:time   => job.time,
^
lib/oxidized/config.rb:53:29: C: [Corrected] …
```
> add https proxy info in slackdiff and ciscosparkdiff hook docs

- lib/oxidized/input/ssh.rb
When connecting to old equipment it is sometimes necesary to force the 
host_key to something old like ssh-dss.
Since it is already possible to force the encryption and kex settings, 
this one is added as well.
> Add ssh_host_key setting

- docs/Configuration.md
- lib/oxidized/input/ssh.rb
This add the ssh_hmac setting. This completes all settings which might 
be needed when connecting to older firmware releases.
> Add ssh_hmac setting

- docs/Configuration.md
- lib/oxidized/input/ssh.rb
This setting is useful when SSH is not listening on port 22 on the proxy 
host. It closes #1537
> Add ssh_proxy_port

- lib/oxidized/model/dnos.rb
newer DNOS switches are branded EMC as well - this means the regex for excluding the uptime from config backups is no longer effective on these switches. A sample output on the newer switches is "Dell EMC Networking OS uptime is 6 day(s), 20 hour(s), 33 minute(s)"
I have added a seperate line for the new format.
I imagine its also possible to do this more gracefully by editing the regex but im not all that skilled in it.
> update dnos.rb to take account of EMC branding

- lib/oxidized/model/netscaler.rb
More generic regex for finding secrets. Testing shows all secrets are followed by `-encrypted`. Makes up for some additional secrets found on new production deployments from my previous commit.
> Update netscaler.rb with better secret handling

- README.md
> update Ubuntu and Debian install instructions in README.md

- CHANGELOG.md
- lib/oxidized/model/pfsense.rb
If 'lighttpd' is configured in pfSense its password should be replaced in output if 'remove_secret' is activated.
> Hide potential secret set as 'lighttpd_ls_password' at pfSense systems

- lib/oxidized/model/powerconnect.rb
- [X ] Passes rubocop code analysis (try `rubocop --auto-correct`)
Powerconnect.rb didn't work in my case because an enable password is not required.  
I updated the model to allow enable to be a true or a password.
> Add logic to check :enable to see if it is password String or a Boolean.

- lib/oxidized/model/dnos.rb
- lib/oxidized/model/powerconnect.rb
Improved filtering for dnos and powerconnect switches.
dnos:
* improve uptime message filtering. On my switches uptime is reported like this:
```
! sw-541saw21 uptime is 3 year(s), 36 week(s), 0 day(s), 7 hour(s), 21 minute(s)
```
* filter secrets for local users passwords
* filter secrets for tacacs key
powerconnect:
* filter secrets for tacacs key
> Improved filtering for dnos and powerconnect

- CHANGELOG.md
- lib/oxidized/model/procurve.rb
Additional secret filters in procurve model
-------------------------------------------------------------------------------
```
-    cfg.gsub! /^(snmp-server community).*/, '\\1 <configuration removed>'
+    cfg.gsub! /^(snmp-server community) \S+(.*)/, '\\1 <secret hidden> \\2'
```
config:
```
snmp-server community "community1" Operator
```
before:
```
snmp-server community <configuration removed>
```
after:
```
snmp-server community <secret hidden> Operator
```
-------------------------------------------------------------------------------
```
-    cfg.gsub! /^(snmp-server host).*/, '\\1 <configuration removed>'
+    cfg.gsub! /^(snmp-server host \S+) \S+(.*)/, '\\1 <secret hidden> \\2'
```
config:
```
snmp-server host 192.168.100.1 "COMMUNITY1" Critical
snmp-server host 192.168.100.2 …
```
> Additional secret filters in procurve model

- CHANGELOG.md
- lib/oxidized/hook/ciscosparkdiff.rb
Used the same logic from diff: true section. The original line was invalid. 
Closes issue #1643
> Fix ciscospark hook when diff is false

- docs/Hooks.md
Add help text describing how to generate the correct auth token for slackdiff.
> Clarify which kind of slack token to use in slackhook configuration.

- CHANGELOG.md
- lib/oxidized/model/ciscosmb.rb
Improved secret filtering for ciscosmb
config before:
```
username TEST1 password encrypted da39a3ee5e6b4b0d3255bfef95601890afd80709
username TEST2 password encrypted 40fa37ec00c761c7dbb6ebdee6d4a260b922f5f4 privilege 7
enable password level 3 encrypted 40fa37ec00c761c7dbb6ebdee6d4a260b922f5f4
encrypted radius-server host 192.168.100.1 acct-port 222 retransmit 3 key tFnQUb+haZWjNZgGR+DHH3auI/XzjJYIwNicffDrNok=
encrypted tacacs-server key tFnQUb+haZWjNZgGR+DHH3auI/XzjJYIwNicffDrNok=
encrypted tacacs-server host 192.168.100.2 single-connection timeout 2 key tFnQUb+haZWjNZgGR+DHH3auI/XzjJYIwNicffDrNok= priority 5
encrypted sntp authentication-key 2 md5 tFnQUb+haZWjNZgGR+DHH3auI/XzjJYIwNicffDrNok=
```
after:
```
username TEST1 password encrypted <secret hidden> 
username TEST2 password …
```
> Improved secret filtering for ciscosmb

- lib/oxidized/model/netonix.rb
Prompts can include parentheses.
Prompts for Netonix devices can have parentheses in them.
> Netonix Model Prompt Update

- lib/oxidized/model/netscaler.rb
The existing NetScaler prompt only allows for `>`. This PR updates the prompt to allow for the device hostname proceeding the `>`.
Closes issue #1215.
> update  netscaler model prompt

- .travis.yml
temporarily disable ruby 2.3 build from travis due to bundler issues since bundler 2.0 release
> temporarily disable ruby 2.3 build from travis

- README.md
Add g++ (mandatory to compile extensions used with oxidized-web compilation through gem install)
> Adding a missing dependency for debian

- CHANGELOG.md
- docs/Model-Notes/README.md
- docs/Model-Notes/SmartAX-Huawei.md
- docs/Supported-OS-Types.md
- lib/oxidized/model/smartax.rb
This PR adds support for Huawei SmartAX series devices. 
I have tested this extensively and it works flawlessly for both SSH and Telnet for configuration retrieval.
For proper SSH config retrieval it is necessary to disable SSH keepalives, otherwise net-ssh crashes randomly.
Some explaination for the commands used in the model as well as the order since it is important.
```
post_login "enable" #This enters the privileged mode, it is not necessary to provide any password. It is mandatory to be in privileged mode in order to fetch the config.
post_login "undo interactive" #This disables confirmation prompts, e.g. when entering "quit" it is otherwise necessary to input "Y" for confirmation.
post_login "undo smart" #This disables command help prompts. Normally once a valid command is entered …
```
> Huawei SmartAX support

- lib/oxidized/model/smartax.rb
Just noticed different cfg output between recent fw versions that I run and a very old box that just got configured for cfg retrieval that mandates the usage of `cut_both` to have consistent cfg output. 
I couldn't seem to reopen the older PR to put the modification there unfortunately.
> Huawei SmartAX minor fix for cfg consistency

- docs/Supported-OS-Types.md
* Allied Telesis AT-8000s and AT-8000GS series switches are  RADLAN switches, same as powerconnect and can use powerconnect.rb model.
* TP-link switch TL-SL5428 (not JetStream) with Marvell 98DX106-B0, 88E6095[F] same as EdgeCore - ES352x or SMC TigerSwitch 10/100 SMC6128L2 Manager and can use edgecos.rb model
* TP-link switch TL-SL3428 can use powerconnect.rb model.
> Rebranded (hardware compatibile) devices

- lib/oxidized/model/tmos.rb
Starting in F5's bigip software version 14, the 'tmsh -q list' command reports real time bandwidth usage for each pool. This causes oxidized to perform an update on every query of the F5 as the bandwidth usage is always changing. Added gsubs to tmos.rb to remove the bandwidth usage lines.
> Ignore bandwidth usage on F5 bigip version 14

- README.md
net-telnet and puma both require Ruby to be over 2.2.
Either you install the old variants of those 2, or update ruby to 2.3
> Added ruby 2.3 install on centos 7

- CHANGELOG.md
- lib/oxidized/model/voss.rb
show sys-info has the following information that changes even though the configuration has not changed.  This is causing a lot of configs to be archived in oxidized for Extreme/Avaya voss.
Last Change: 45 day(s), 15:20:07   (1 day(s), 05:30:16 ago)
Last Vlan Change: 45 day(s), 15:20:07   (1 day(s), 05:30:16 ago)
Last Statistic Reset: 0 day(s), 00:00:00
> Update VOSS to filter out "show sys-info" changes

- CHANGELOG.md
- lib/oxidized/model/cambium.rb
Just added a gsub to drop the timestamp from configuration as it changes every backup
Closes issue #1740
> Cambium timestamp correction

- CHANGELOG.md
- docs/Supported-OS-Types.md
- lib/oxidized/model/airfiber.rb
This PR creates and adds support for backing up the latest config from the airfiber from telnet/ssh.
> Add ubiquiti Airfiber model support.

- CHANGELOG.md
- lib/oxidized/model/dlink.rb
Added space character for the prompt match of dlink.rb this allows models like EAS 200-24p to be valid prompts because the prompt appears as "EAS 200-24p:admin#" and space broke it previously.
Closes #1738
> Allows DLink OS to work with OEM models with spaces

- docs/Supported-OS-Types.md
Just a quick modification to documentation as oxidized supports cambium pmp450's but it's not listed as supported in documentation
> Add cambium as a supported model to docs (pmp450 series)

- CHANGELOG.md
- extra/nagios_check_failing_nodes.rb
The script crashes at least on Ruby 2.3 due to a denied implicit conversion during JSON parsing:
```
/usr/lib/ruby/2.3.0/json/common.rb:156:in `initialize': no implicit conversion of StringIO into String (TypeError)
from /usr/lib/ruby/2.3.0/json/common.rb:156:in `new'
from /usr/lib/ruby/2.3.0/json/common.rb:156:in `parse'
from ./check_oxidized_failing_nodes.rb:13:in `<main>'
```
I added a `.string` explicit conversion to prevent the error.
> Explicit stringio to string type conversion in nagios check

- extra/syslog.rb
Fixes errors reported:
```
syslog.rb:134:in `rescue in getname': undefined local variable or method `ipadr' for #<Oxidized::SyslogMonitor:0x0055b9858ad448 @mode=:udp> (NameError)
Did you mean?  ipaddr
from syslog.rb:134:in `getname'
from syslog.rb:99:in `jnpr'
from syslog.rb:107:in `handle_log'
from syslog.rb:126:in `block in run'
from syslog.rb:112:in `loop'
from syslog.rb:112:in `run'
from syslog.rb:78:in `initialize'
from syslog.rb:64:in `new'
from syslog.rb:64:in `udp'
from syslog.rb:142:in `<main>'
```
> [syslog] Fix typos in varaible names

- CHANGELOG.md
- docs/Supported-OS-Types.md
- lib/oxidized/model/sonicos.rb
Introduces support for SonicOS, refactor of #950 by @rgnv to clean it up and separate the models into separate PRs.
Potentially addresses #1236 #938
> refactor sonicos model from PR #950

- lib/oxidized/model/sonicos.rb
Remove telnet from config block in sonicos model as no telnet prompts are defined.
> remove telnet config as no prompts are defined

- CHANGELOG.md
- lib/oxidized/model/ciscosmb.rb
'show system' on a Cisco SG500 emits the following output:
```
System Description:                       SG500-52P 52-Port Gigabit PoE Stackable Managed Switch
System Up Time (days,hour:min:sec):       102,20:25:15
System Contact:                           X
System Name:                              X
System Location:                          X
System MAC Address:                       XX:XX:XX:XX:XX:XX
System Object ID:                         1.3.6.1.4.1.9.6.1.81.52.2
Fans Status:                              OK
Unit            Temperature (Celsius)            Status          
------------------------ ------------------------ ------------------------ 
1                        32                       OK            
```
None of these informations are relevant for a backup system IMO. The …
> Ciscosmb: remove 'sh system' output

- lib/oxidized/input/telnet.rb
Changed telnet cmd because it was getting stuck at login prompts for some devices.
fixes #1614
fixes #1650
fixes #1784
fixes #1493
fixes #1786
> Changing telnet cmd endings from \n to \r\n

- lib/oxidized/model/routeros.rb
Minimal change
Strip line `# received packet from x.x.x.x bad format` from RouterOS config.
This message intermittently appears and disappears when RouterOS is running VRRP and there is also CARP traffic on the same network.
The two protocols work side-by-side without problem if using different group IDs, but share the [same IP protocol number](https://en.wikipedia.org/wiki/Common_Address_Redundancy_Protocol#Incompatibility_with_IANA_standards) and this causes Mikrotik to (sometimes) include this warning in configs.
> Strip line "# received packet from x.x.x.x bad format" from RouterOS

- CHANGELOG.md
- lib/oxidized/model/procurve.rb
power consumption may differ per run/check and trigger an unneeded backup/change
it can be re-added by monkey patching the model, i don't think dumping
infos about the power module should be the default
Closes #1453 , relates https://github.com/ytti/oxidized/pull/1176 & https://github.com/ytti/oxidized/pull/1553
> Procurve: remove infos about power modules

- CHANGELOG.md
- docs/Supported-OS-Types.md
- lib/oxidized/model/hpmsm.rb
Added support for the HP MSM Wireless Controller. Tested on a HP MSM720
> HP MSM Wireless Controller support

- CHANGELOG.md
- lib/oxidized/model/comware.rb
Comware let's you store passwords with the "password cipher" command that was not recognized as secret pattern, so the cipher string was stored in git without removing it.
Added "password cipher" to secret detection patterns.
> Added "password cipher" to comware secret removal pattern.

- CHANGELOG.md
- lib/oxidized/model/adtran.rb
Adtran OS inserts random and variable quantities of trailing whitespace.  Occasionally it will insert a random \r into the config output for no particular reason.  This patch removes that whitespace.
> remove random trailing whitespace from adtran output

- CHANGELOG.md
- docs/Model-Notes/LinuxGeneric.md
- docs/Model-Notes/README.md
- docs/Supported-OS-Types.md
- lib/oxidized/model/aosw.rb
- lib/oxidized/model/linuxgeneric.rb
See: https://github.com/ytti/oxidized/issues/1818
View [culumus.rb](https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/cumulus.rb) for differences
I have tested it with CentOS 7. It worked fine. :smile: 
I am not too sure how to feel about the `prompt`. 
To to reiterate here, for more specific needs, users could extend the model like so:
```
require 'oxidized/model/linuxgeneric.rb'
class LinuxGeneric
cmd :secret, clear: true do |cfg|
cfg.gsub! /^(username (\S+) privilege (\d+) (\S+) (\d+)).*/, '\\1 <redacted>'
cfg
end
post do
cfg = add_comment 'THE MONKEY PATCH'
cfg += cmd 'firewall-cmd --list-all --zone=public'
end
end
```
Any input is much appreciated!
Thank you,
Dave
> Create linuxgeneric.rb model

- CHANGELOG.md
- lib/oxidized/model/procurve.rb
- [N/A] Changes are reflected in the documentation
Fixes an issue with detecting prompt on older procurve switches (J4899B and J4813A tested), where VT100 control chars get send to scroll, resulting in a prompt which starts with a control character instead of a newline.
Also tested for regression against the following switches (which still work):
- J9776A, J9138A, J9775A, J9783A, J9728A, J9586A
Should fix https://github.com/ytti/oxidized/issues/1804 and https://github.com/ytti/oxidized/issues/1705 and maybe https://github.com/ytti/oxidized/issues/1607
> Procurve compatibility enhancement

- lib/oxidized/model/aosw.rb
Revert unintentional prompt change in asow model that slipped in as part of #1820
Closes #1870
> restore aosw prompt that slipped through review in #1820

- lib/oxidized/model/procurve.rb
Clean up procurve prompt to be more concise.
Follow-up from #1866
> Clean up procurve prompt regexp

- CHANGELOG.md
- docs/Supported-OS-Types.md
- lib/oxidized/model/zynosgs.rb
Adds support for Zyxel GS1900-8 switch to ZynOS, might also work with bigger GS1900 switches.
Fixes https://github.com/ytti/oxidized/issues/1703, part of https://github.com/ytti/oxidized/issues/1404
> Zyxel GS1900 support

- lib/oxidized/model/procurve.rb
As discussed in https://github.com/ytti/oxidized/pull/1866, this is a less open version of the prompt working for ssh and telnet switches
> More restrictive prompt regex

- CHANGELOG.md
- docs/Supported-OS-Types.md
- lib/oxidized/model/comware.rb
- lib/oxidized/model/ios.rb
- lib/oxidized/model/ironware.rb
- lib/oxidized/model/screenos.rb
- lib/oxidized/model/speedtouch.rb
Comware model login prompt has changed in newer HPE devices. Fix for #1886
Wipe out 'flash free space' from some Brocade devices which use ironware model.
Added Thomson Speedtouch model.
Added gsub's to ios model, to ignore "configuration last changed", "NVRAM modified" lines from config and VTP status.
> Model impovements for ios/comware/ironware/screenos and new model speedtouch

- CHANGELOG.md
- docs/Model-Notes/JunOS.md
- lib/oxidized/model/junos.rb
Moved 'show configuration' to the end of commands list, so the cfg result will start with comments and end with configuration. Most of the models execute configuration retrieval command the last one, so changing junos model to the same behaviour would be nice.
> Moved show configuration output the end of cfg

- CHANGELOG.md
- extra/oxidized.service
- [N/A] Passes rubocop code analysis (try `rubocop --auto-correct`)
- [N/A] Changes are reflected in the documentation
oxidized service may fail when using http source and no hosts are listed.
This allows systemd to restart a failed oxidized service on failure.
This needs #1929 to work
> Systemd restart on failure

- CHANGELOG.md
- lib/oxidized/model/sros.rb
Cleaned up copy-paste gsub's from each cmd.
Added 25 lines of "show chassis" command from where additional non-persistent lines are rejected.
Sample section appended to comments:
```
#
#
```
> sros show chassis and model cleanup

- CHANGELOG.md
- lib/oxidized/model/oneos.rb
Added **show system hardware** and **show product-info-area** to OneAccess model.
Comments now contain device description and serial number information. 
Perhaps it's reasonable to cut out "! +------------------------------+---------------------------------+" lines to reduce dumb formatting output?...
Live example:
```
!  HARDWARE DESCRIPTION
!
!   Device   : One20d
!   CPU      : MPC8323 PowerQUICC II Pro
!
!  Bus Freq : 133MHz   QE Freq : 200MHz   Core Freq : 266MHz
!  Ram size :  64Mo    Flash size : 512Ko   Extended Flash size :  32Mo
!  Ram disk :   1Mo    Flash disk :  32Mo  (Extended)
!
!  Local : x Uplink : x ISDN :
!
!  Local  : FAST ETHERNET + SWITCH ETHERNET / 4 ports
!  Uplink : G.SHDSL.bis / 2 pairs
!
!
! +----------------------------------------------------------------+
! | …
```
> oneos system hardware and product-info-area commands

- CHANGELOG.md
- lib/oxidized/model/fortios.rb
Added 'get system ha status' command to fortios. Comments now include hardware information about FortiGate cluster nodes.
```
```
```
```
> fortios added command 'get system ha status'

- CHANGELOG.md
- lib/oxidized/model/comware.rb
BUGFIX: comware improvement for requesting HP 19x0 switches hidden CLI.
FEATURE: comware added device manuinfo to include serial number
Fixes issues #1754 and #1447
> comware fix 19x0 cli mode and add device manuinfo

- CHANGELOG.md
- lib/oxidized/model/procurve.rb
- [N/A] Changes are reflected in the documentation
I recently worked on HPe 5400 series switches which work great with current oxidized, but create new versions of the configuration because of power consumption output in the configuration.
This fix replaces the actual wattage with `<removed>` so the config doesn't change.
> Procurve exclude power consumption

- extra/syslog.rb
Tested working on UDP invoking rest AIP call.
> Add aruba class in syslog monitor example

- lib/oxidized/model/aosw.rb
Used instead of a serial number for virtual mobility master and virtual controllers
> [AOSW] Add show license passphrase

- CHANGELOG.md
- lib/oxidized/model/ibos.rb
add support for Waystream products, with their iBOS operating system
This has been in production at customer site for over one year, doing backup on approx 1400 devices.
> add Waystream iBOS model

- docs/Supported-OS-Types.md
The software of the S3900 switches is very simmilar to the EdgeCOS software.
This should help users to easily find the correct module without duplicating code.
> Supported OS types: add Fiberstore S3900 series

- CHANGELOG.md
- lib/oxidized/model/sonicos.rb
Sensitive information also exists in the following lines. Mark then in hidden secret module.
- password xxx
- passphrase password xxx
- bind-password xxx
- authenticate sha1 xxx
- encryption aes xxx
> Add hidden info for SonicWall

- CHANGELOG.md
- lib/oxidized/model/eos.rb
- lib/oxidized/version.rb
Hides macsec secret key: the CKN and CAK.
* Original Syntax Example
```
mac security
fips restrictions
!
profile default
cipher aes256-gcm-xpn
key 1ffab311 7 00C655A8E47F0E4756B32767F7C9A34854716C7F33F2E948A39CA9C00D0D0A0330
mka session rekey-period 3600
l2-protocol lldp bypass
```
* Replacement Syntax Example
```
mac security
fips restrictions
!
profile default
cipher aes256-gcm-xpn
key <secret hidden>
mka session rekey-period 3600
l2-protocol lldp bypass
```
> EOS: Hides MACsec Key

- CHANGELOG.md
- lib/oxidized/model/gcombnps.rb
Allow any max length for username/password in GcomBNPS model (max length varies between software versions)
> GcomBNPS: allow any max length for username/password

- CHANGELOG.md
- docs/Supported-OS-Types.md
- lib/oxidized/model/cnos.rb
- lib/oxidized/model/fsos_s5800.rb
Add Fiberstore S5800/S5850 series support
A better solution than #1855
> add Centec Networks CNOS support

- lib/oxidized/model/ciscosmb.rb
PR #1473 has solved the login issues for SG220 switches that ciscosmb model has.
In order to completely assimilate SG220 switches there also has to be a solution for the uptime string that causes meaningless diffs. Note that the complete removal of show system command from the ciscosmb model (as per PR #1799) hasn't solved the problem since in SG220 switches the uptime is printed by the show version command.
This should be the last required change to close issue #1148
> Strip uptime from 'show version' command in SG220 switches

- CHANGELOG.md
- oxidized.gemspec
The rugged gem now has 0.99.0 that requires a much newer cmake than is available on RHEL7:
```
[root@centos-7 /]# scl enable rh-ruby23 -- gem install --no-document oxidized
Building native extensions.  This could take a while...
ERROR:  Error installing oxidized:
ERROR: Failed to build gem native extension.
current directory: /opt/rh/rh-ruby23/root/usr/local/share/gems/gems/rugged-0.99.0/ext/rugged
/opt/rh/rh-ruby23/root/usr/bin/ruby -r ./siteconf20200312-1719-1x0mvem.rb extconf.rb
checking for gmake... yes
checking for cmake... yes
checking for pkg-config... yes
-- The C compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
CMake Error …
```
> Fix rugged dependency

- CHANGELOG.md
- lib/oxidized/model/routeros.rb
`/system history print` some times more than screen. And it waits for a key press.
```
U nat rule changed                         user    write
U address list entry added                 user    write
U address list entry added                 user    write
-- [Q quit|down]
```
**without-paging** after **print** solve all problems.
> fix paging output (disable press Q paging message)

- CHANGELOG.md
- lib/oxidized/model/fortios.rb
Strip cluster uptime from FortiOS dumps even without :remove_secrets
This is not a secert but dynamic data that *always* changes between two dumps, thus it should never be included, regardless of the :remove_secrets setting
> fortios: Strip cluster uptime even without :remove_secrets

- CHANGELOG.md
- lib/oxidized/model/procurve.rb
On my HP ProCurve devices, the prompt contains `device-name> `  and not `device-name# `  as expected by the prompt setter.
This PR also allows `>` to be in-place of the current `#` requirement.
This PR does not break any compatibility with previous versions.
> HP ProCurve now accepts ">" as apart of the prompt

- CHANGELOG.md
- lib/oxidized/model/ios.rb
for informs and v3
Examples:
snmp-server host 127.0.0.1 inform version 2c COMMUNITY
snmp-server host 127.0.0.1 informs version 3 priv USERNAME
> IOS: Fix SNMP notification community hiding

- CHANGELOG.md
- lib/oxidized/model/xos.rb
This regular expression is invalid on some XOS-prompts, example X620-series, where the OS adds a '\*' symbol in front of the hostname. For example, hostname **mydevice-eu-sw02** would give a prompt looking like this: ```* mydevice-eu-sw02 >```
I manually tested the current regex on xos.rb using [regex101.com](https://regex101.com) and also noticed that it generally does a poor job in matching valid hostnames. In this change, I basically copied the regex that existed on ```fortios.rb```, manually tested it and then slightly tweaked it to work for XOS-prompts as well.
> Updated xos.rb regex-code to better match XOS-prompts

- CHANGELOG.md
- docs/Supported-OS-Types.md
- lib/oxidized/model/qtech.rb
QTECH company offers several lines of Ethernet switches
designed specifically for Internet providers, data centers,
industrial enterprises and the energy sector.
https://www.qtech.ru/en/catalog/
> Add QTECH model

- CHANGELOG.md
- lib/oxidized/model/cumulus.rb
This is a trivial change to remove the logging of kernel routes by the Cumulus model, as they are transient data and not configuration which needs backing up.
Closes issue #2080
> Cumulus model - Don't store transient data

- CHANGELOG.md
- lib/oxidized/model/pfsense.rb
pfSense 2.4.5 now wraps the data inside `<password>` tags with a `<![CDATA[` `]]>` wrapper.  The current regular expression does not match the new format.  This causes pfSense password data to be exposed by Oxidized.  
My regular expression update handles both the existing data (from versions 2.4.4 and prior) and data that is wrapped in CDATA (from version 2.4.5 and beyond).
Example of old configuration data from 2.4.4:
`<password>$1$bcrypthash/</password>`
Example of new configuration data from 2.4.5:
`<password><![CDATA[$1$bcrypthash/]]></password>`
> Handle pfSense 2.4.5+ passwords that are wrapped in CDATA

- CHANGELOG.md
- lib/oxidized/model/xos.rb
The current xos.rb regexp for prompt does not take stacked switches into account and therefore only works for standalone devices. This is a slight update to make the prompt regexp include stacked switches.
Reference: #2107
This update also fixes an issue that wasn't entirely solved in the previous pull request for xos.rb where Oxidized can't match the prompt if the XOS-device has not saved its configuration.
Reference: #2113
> Update xos.rb prompt to work with stacked switches

- CHANGELOG.md
- docs/Supported-OS-Types.md
- lib/oxidized/model/edgecos.rb
that doesn't support `terminal` command
> EdgeCOS: add ES3526XA-V2

- CHANGELOG.md
- docs/Supported-OS-Types.md
- lib/oxidized/model/eltex.rb
> Model for Eltex MES

- CHANGELOG.md
- docs/Supported-OS-Types.md
- lib/oxidized/model/zteolt.rb
model for zte olt c3xx
working with firmware 1.2.5 and 2.1
> Model for zte olt c3xx

- CHANGELOG.md
- Dockerfile
Rebase the Dockerfile (on which the official container is based) to bionic-1.0.0 release of phusion/baseimage-docker
> rebased to phusion/baseimage-docker bionic-1.0.0

- CHANGELOG.md
- lib/oxidized/model/routeros.rb
Comments like this seem to come and go on some MikroTik equipment:
> routeros model: Remove intermittent POE comment

- extra/oxidized.service
Administrators are not expected to put files in `/lib`. The correct
location for the systemd service file is in
`/etc/systemd/system` (like for RHEL).
This is only a change in documentation. Also, I think we should not use `SIGKILL` as the kill. Is the issue still present in recent versions of oxidized? Just using `SIGTERM` works for me. Cc @mattie47
> Fix location of systemd service file on Debian systems

- CHANGELOG.md
- lib/oxidized/model/dlink.rb
Added support for d-link dgs-1100 series switches, tested with dgs-1100-10/me
> Glaubway dlink

- CHANGELOG.md
- lib/oxidized/model/ironware.rb
The following line output by show chassis was not accounting for all cases, which meant configuration would be updated based on fan speed.
```-! --- TEMPERATURE are in auto mode (current speed is MED-HI (90%)). Temperature monitoring poll period is 60 seconds.```
Added '-' character to regex to resolve issue.
> ironware.rb: Fix "current speed" regex to enclude MED-HI speed

- CHANGELOG.md
- lib/oxidized/model/netgear.rb
Before:
```
snmp-server community <hidden>
snmp-server community <hidden> 192.168.0.100 public
snmp-server community <hidden> 255.255.255.255 public
```
After:
```
snmp-server community <hidden>
snmp-server community ipaddr 192.168.0.100 <hidden>
snmp-server community ipmask 255.255.255.255 <hidden>
```
> Fix SNMP community removal for Netgear

- CHANGELOG.md
- docs/Supported-OS-Types.md
- lib/oxidized/model/aoscx.rb
This adds a model for the Aruba CX switch line. It is modeled after the procurve module, with updated commands to match the Aruba AOS-CX software.
> Added aoscx.rb model

- CHANGELOG.md
- lib/oxidized/model/xos.rb
Filter the next periodic schedule time from configuration output. In our case that line triggered a change several times a day.
> model/xos: filter perodic save schedule time

- docs/Creating-Models.md
I noticed that the examples for monkey-patching gave syntax errors when used.
I fixed some typos, and added an example of a string based command, instead of only having single word symbol commands.
> fix documentation for monkey-patching

- extra/oxidized-report-git-commits
[tests don't apply to extra/ directory #yolo]
As it stands, `oxidized-report-git-commits` will send an failure email if a device is offline.  This is an unmerciful nuisance which ends up with lots of spam.  Oxidized is not a monitoring system, so this is of limited use at best.
This update moves sending the email to the recipient into the script, and introduces the `-f` option which suppresses these failure emails.
> migrate mail option to being part of the script to stop endless blank failure emails

- lib/oxidized/input/ssh.rb
- oxidized.gemspec
Should solve: https://github.com/ytti/oxidized/issues/2228
Note:
Not a ruby dev so i am sure there is a better way to do it.
Open to suggestions.
I also tested if node has an ipv4 address and it also works. So basically, at least from what i can tell, it does not break anything. :laughing: 
Thanks,
Dave
> add bracket on node if using proxy and node has ipv6 address

- CHANGELOG.md
- lib/oxidized/model/routeros.rb
The current code for sensitive backup on Mikrotik is not working,
To enable exporting sensitive data like SNMP credentials or others, you need to add the `show-sensitive` flag to the export command, without it, it is the same as with the `hide-sensitive` flagged export
Close issue #1976
> Fix sensitive configuration backup on Mikrotik RouterOs

- lib/oxidized/model/aosw.rb
Reboot Time and Cause: AP rebooted Tue Jun 22 06:39:10 UTC 2021; CLI cmd at uptime 0D 0H 41M 48S: reload
Reboot Time and Cause: AP Reboot reason: BadPtr:0000000c PC:_raw_write_lock_bh+0x20/0x40 Wa
The above lines are examples of what we get with the "sh version" command. These lines change at every reboot of the device.
I don't think they're needed as part of the config backup.
> Delete Reboot Time and Cause line in aosw.rb

- lib/oxidized/model/fabricos.rb
reject "Power Usage:" in fabricos showconfig
reject "Power Usage:" in fabricos showconfig
> reject "Power Usage:" in fabricos showconfig

- CHANGELOG.md
- docs/Supported-OS-Types.md
- lib/oxidized/model/necix.rb
Adds support for NEC IX devices.
> Adds support for NEC IX devices.

- CHANGELOG.md
- lib/oxidized/model/sonicos.rb
Additional scrubbing for SonicOS v7 devices - scrubbed smtp-pass, pop-pass, date, and time
> Additional scrubbing for SonicOS v7 devices

- CHANGELOG.md
- lib/oxidized/model/airfiber.rb
Did not match rc versions of airfiber.
` AF09.v4.1.0-rc.2.218.200225.0850#` for example
> Update airfiber prompt regex

- lib/oxidized/model/comware.rb
HPE Comware Release 3208 (v7.1) doesnt accept the xtd-cli-mode on as it has "too many parameters" removing the on will allow it to work.
I suspect the post login on this section needs better logic.
> Update to comware for v1950 OS Release 3208

- docs/Creating-Models.md
Fixed a couple of errors in the docs where the wrong path for the models was listed.
> Fix docs with correct path for where to put models

- CHANGELOG.md
- lib/oxidized/hook/xmppdiff.rb
Previously, only diffs that contained added *and* deleted lines were considered "interesting".
This is a curious definition that I was unable to find in other hooks, and definitely not what we wanted/expected.
> xmppdiff: Make more diffs interesting

- CHANGELOG.md
- lib/oxidized/hook/xmppdiff.rb
Instead of doing (connect, join, post, leave, disconnect) for each change, xmppdiff now stays connected to the server and joined to the MUC after the first change it posted.
> xmppdiff: Persist connection to XMPP server

- CHANGELOG.md
- docs/Model-Notes/OS10.md
- docs/Model-Notes/README.md
- [ N/A ] Passes rubocop code analysis (try `rubocop --auto-correct`)
- [ N/A ] Tests added or adapted (try `rake test`)
- [ N/A ] Changes are reflected in the documentation
- [ OK ] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)
I added some model notes for Dell/EMC OS10 switches.
I could also include the kludge mentionned in https://github.com/ytti/oxidized/issues/2419 but I'm not so sure, so I want your advice on this.
Thanks.
> Add model notes for Dell/EMC OS10

- lib/oxidized/model/routeros.rb
Fix Mikrotik Routeros Backups being empty for routeros versions <7.
Closes issue #2427
> routeros: /export params depending on version

- CHANGELOG.md
- lib/oxidized/model/routeros.rb
Once you execute `/system package update check-for-updates`, the information about available updates is included in the output.
Diff of output header:
```diff
-#                 ;;; Firmware upgraded successfully, please reboot for changes 
-#                     to take effect!
-#        routerboard: yes
-#   factory-firmware: 3.39
-#   upgrade-firmware: 6.47.9
-# 
-#             channel: long-term
-#      latest-version: 6.48.5
-#              status: New version is available
-# 
```
This PR is based in #2435, since it's related.
> routeros: Reduce metadata/version output

- CHANGELOG.md
- lib/oxidized/model/tplink.rb
This strips the timestamps 'System Time' and 'Running Time' from the output of 'show system-info'.
> tplink: Strip 'System Time' and 'Running Time'

- CHANGELOG.md
- lib/oxidized/model/xos.rb
Had issues that new backups where pushed every hour to git when "Next periodic save on" was updated with the next time to run.
Instead set the row to "empty".
```` 
- #                   Next periodic save on Mon Jun 14 11:57:27 2021
+ #                   
````
> Fix when auto-saved is configured on xos switches

- CHANGELOG.md
- docs/Supported-OS-Types.md
- lib/oxidized/model/zy1308.rb
Easy pull via HTTP basic auth, I added the correct URL
> Support for Zyxel 1308 OLTs

- CHANGELOG.md
- lib/oxidized/model/tmos.rb
Avoid /humidity hardware field to be reported as Oxidizer is detecting as a change on the config
Avoid /humidity hardware field to be reported as Oxidizer is detecting as a change on the config
> Avoid /humidity hardware field to be reported

- lib/oxidized/model/hpebladesystem.rb
Without this little patch we get "Generated on: <removed>" instead of "#Generated on: <removed>"
> hpebladesystem.rb: keep dash before "Generated on"

- CHANGELOG.md
- lib/oxidized/model/model.rb
- lib/oxidized/model/opnsense.rb
- lib/oxidized/model/pfsense.rb
This PR does a two things:
1. There was an issue where the OPNsense and PFsense models would chop off the first line of the config file containing an <?xml... header. This is unneccessary and might cause issues, and was probably left in unintentionally, so I removed this.
2. Added functionality to OPNsense and PFsense models to gather version information and put it into a comment.
3. Refactors the "xmlcomment" function added in step 2 into model.rb, since it's probably useful to other models, and it's really messy to keep it in the opnsense and pfsense models.
> OPNsense/PFsense models: Do not remove <?xml header, and add version information as comment.

- CHANGELOG.md
- lib/oxidized/model/fastiron.rb
Added a second "exit" in fastiron.rb pre_logout.
This change fixes a timeout on ICX-series devices that keeps waiting forever after the first "exit" and didn't makes the backup, as stated in issue #2202 
Now it works fine:
```
D, [2020-10-15T19:35:59.432065 #31] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to BROCADE_ICX7250-24
D, [2020-10-15T19:36:15.401607 #31] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([\w.@()-]+[#>]\s?)$/] at BROCADE_ICX7250-24
D, [2020-10-15T19:36:16.205171 #31] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login commands at BROCADE_ICX7250-24
D, [2020-10-15T19:36:16.205305 #31] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: nil, block: #<Proc:0x000055999314e290@/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/model/fastiron.r …
```
> fastiron.rb: added a second "exit" to pre_logout

- CHANGELOG.md
- docs/Model-Notes/LinksysSRW.md
- docs/Supported-OS-Types.md
- lib/oxidized/model/linksyssrw.rb
This creates a model for Linksys SRW switches by sneaking out form the
menu mode and starting the lcli tool to be able to dump the config.
Due to the fact that we're navigating and escaping from a curses mode
not using the regular username/password entry procedures,
but rather chaining a bunch of expect to do the login and start the
lcli terminal mode.
This resolves #875
This is a RFC for Linksys SWR support. I'm probably abusing a lot of code here, and I should write both documentation and some explaining about the model but I'm throwing this out there for some early feedback.
> [RFC] Create a model for Linksys SRW switches

- docs/Hooks.md
- No user-visible changes except to documentation, which I believe to be self-evident
Adds documentation about the key format required by the `githubrepo` hook's `privatekey` parameter. This does not address the underlying issue of #2324 or #1877, but it should make it more clear which key format users should use until that limitation is addressed.
> Specify format for githubrepo's privatekey file

- CHANGELOG.md
- docs/Supported-OS-Types.md
- lib/oxidized/model/cambiumepmp.rb
Pull Request for Cambium ePMP devices to add support for these devices. The model name to use is cambiumepmp
I've had this running on our Oxidized instance and it's working well and perfectly stable for the last three months. 
This will close off https://github.com/ytti/oxidized/issues/2000 with people reporting that it works great in that issue. 
This will close off this issue also. https://github.com/ytti/oxidized/issues/2081
> Cambium ePMP Support

- CHANGELOG.md
- lib/oxidized/model/enterasys.rb
Adds paging handler to `enterasys.rb` model
The paging prompt that I have is:
```
--More-- <space> next page, <cr> one line, <q> quit
```
But saw in some documentations `--More-- or (q)uit` or even `--More--` so I used a regexp that can handle all of them. Better safe than sorry.
Closes #2454
> Adds paging support to Enterasys B3/C3

- CHANGELOG.md
- lib/oxidized/input/ssh.rb
This prevents the [ssh_proxy code block](https://github.com/ytti/oxidized/blob/c0dae48928ec391c01070a32c2eedb034d983c10/lib/oxidized/input/ssh.rb#L137) being executed when the value is empty in an SQL source, and otherwise has no effect.
It brings Oxidized in line with the _expected_ behaviour and closes #2267
> Avoids running proxy commands if ssh_proxy config is empty/blank

- CHANGELOG.md
- lib/oxidized/model/vrp.rb
- ~~[ ] Tests added or adapted (try `rake test`)~~ N/A
The change makes it so that devices that are in HRP mode can correctly be collected and parsed by oxidized. If not the * is removed is will not process devices in HRP mode. Even with this change other Huawei devices can be correctly collected as before.
> Collect config from HRP enabled devices

- CHANGELOG.md
- lib/oxidized/model/netscaler.rb
Citrix Netscalers have functionality for logical partitioning, where each partition has its own config. This pull request enhances oxidized to check for presence of these additional config partitions and retrieves the configuration from them if present.
It is modeled on the asa model which has similar logical config separation in contexts.
> Netscaler multiple partition support

- CHANGELOG.md
- lib/oxidized/model/asa.rb
Reopen https://github.com/ytti/oxidized/pull/1904
The date of the last configuration change is changed even if the user enters the configuration mode and exits. It creates additional (useless) entries in the history, which is inconvenient and slows down the work with a long history (useful for https://github.com/ytti/oxidized/issues/1616).
> asa: information about the configuration change time is deleted

- CHANGELOG.md
- lib/oxidized/model/eos.rb
> EOS: Fix truncated configs #2038

- lib/oxidized/input/ssh.rb
- lib/oxidized/model/enterasys.rb
- lib/oxidized/model/model.rb
~~- [ ] Tests added or adapted (try `rake test`)~~ N/A
~~- [ ] Changes are reflected in the documentation~~ N/A.
~~- [ ] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)~~ N/A
Clean up a few rubocop offences reported by the Travis Pull Request checks.
Fixed ssh_make_opts by breaking out the proxy command generation to a separate function.
> Rubocop fixes

- lib/oxidized/config.rb
- lib/oxidized/input/ssh.rb
- lib/oxidized/model/enterasys.rb
- lib/oxidized/model/model.rb
Using `$OXIDIZED_HOME` doesn't change the load location of the config file, this PR adds that functionality by setting the `usrdir` option to the `asetus` module to the oxidized config root value.
> Load config file from OXIDIZED_HOME env var location.

- CHANGELOG.md
- lib/oxidized/model/edgeswitch.rb
> Better manage of the enable mode in edgeswitch.rb

- CHANGELOG.md
- Dockerfile
- README.md
Build of Docker image is failing due [nokogiri 1.13.3](https://rubygems.org/gems/nokogiri/versions/1.13.3) not working with Ruby 2.5 anymore. Rebasing to Focal will bump Ruby to 2.7 and Gem to 3.1.
> Fix Dockerfile building, bump to Focal baseimage

- lib/oxidized/model/linksyssrw.rb
The wrapping of lldpPortConfigTLVsTxEnable lines sometimes break at
another place, so to produce stable output we should massage these lines
to.
> linksyssrw: Better massaging of wrapped lines

- CHANGELOG.md
- lib/oxidized/model/nxos.rb
Allow additional types of passwords to be stripped from nxos configs, not just local account passwords.
> nxos: Allow additional types of passwords to be stripped from nxos configs

- CHANGELOG.md
- docs/Configuration.md
- lib/oxidized/config.rb
- lib/oxidized/jobs.rb
- lib/oxidized/worker.rb
Allows to backup using the maximum number of threads, without using
autotuning (but not more than the maximum)
Fixes #2527
> Add option: use_max_threads

- CHANGELOG.md
- docs/Model-Notes/ADVA.md
- lib/oxidized/model/adva.rb
This PR adds support for ADVA devices by adding a proper model for it. Tested with ADVA FSP devices.
> Add support for ADVA devices.

- CHANGELOG.md
- lib/oxidized/model/nxos.rb
nxos: Fix password match to avoid stripping out user role.
before:
`username admin password 5 <secret hidden>
`
after:
`username admin password 5 <secret hidden>  role network-admin
`
> nxos: Fix password match to avoid stripping out user role.

- CHANGELOG.md
- lib/oxidized/model/pfsense.rb
If a <pfsense> tag is not in the config file output, there's an error, for example there are not enough permissions for the user to get the config file. This change detects this condition and throws an error, so that this doesn't fly under the radar silently.
> Check for <pfsense> tag in config file!

- CHANGELOG.md
- docs/Model-Notes/Cumulus.md
- lib/oxidized/model/cumulus.rb
Adds an option to use [cumulus NCLU](https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-44/System-Configuration/Network-Command-Line-Utility-NCLU/) instead of the current method for gathering config
I'm entirely sure _when_ NCLU became a default package in Cumulus, but at least as of 3.6 it was preinstalled and encouraged to use.
I don't have a proper ruby environment at hand, but it is such a small change I doubt anything is ugly :-)  
It is currently running in my production environment.
> Cumulus: add option to use NCLU as configuration collecting method

- CHANGELOG.md
- docs/Hooks.md
- lib/oxidized/hook/exec.rb
- lib/oxidized/model/model.rb
- lib/oxidized/node.rb
- lib/oxidized/version.rb
Allows to get more granular information on the failure reason for a specific node when working with the exec hook.
Closes issue https://github.com/ytti/oxidized/issues/2424
> added err_type and err_reason node attr, mapped to exec hook

- CHANGELOG.md
- lib/oxidized/model/openbsd.rb
This will include the following files:
- bgpd.conf
- ospfd.conf
- ospf6d.conf
> OpenBSD: Include bgpd, ospfd and ospf6d files

- CHANGELOG.md
- lib/oxidized/model/junos.rb
junos model archives the output of `show system license` command. That output contains used values where some change often. In our case that is the number of active routes (in `fib-scale` and `rib-scale` lines). I've replaced the values in used column with `<count>`
```
> show system license 
License usage: 
Licenses     Licenses    Licenses    Expiry
Feature name                       used    installed      needed
bgp                                   1            1           0    permanent
isis                                  0            1           0    permanent
filter-based-forwarding               0            1           0    permanent
vrrp                                  0            1           0    permanent
fib-scale                         90925       256000           0 …
```
> in junos license output remove values that change frequently

- CHANGELOG.md
- lib/oxidized/model/model.rb
First two, I have no idea... not a Ruby coder, sorry!
I wrote a quick fix to close issue #2471 .
The fix is to check the type of block passed to `process_args_block()` when `clear: true` has been set as an arg, and if it's an Array, filter the target to remove any entries with the command given, then push the new command on to the end.
A better approach might be to use `map!` first to replace a single occurence, then filter afterwards to remove other occurences in order to retain some sort of ordering - however, I'm not confident enough to try to do that.
_This PR replaces #2472 , which was from [mjbnz:master](/mjbnz/oxidized/) instead of a PR-specific branch_
> Prevent clearing of all commands when using `clear: true` with an explicitly defined command

- CHANGELOG.md
- docs/Configuration.md
- lib/oxidized/config.rb
- lib/oxidized/source/csv.rb
- lib/oxidized/source/http.rb
- lib/oxidized/source/source.rb
- lib/oxidized/source/sql.rb
Add the ability to map group aliases to group names. This is useful when a data source doesn't have a simple field for grouping, but does have another that can be combined. (For example, in Netbox this allows for multiple tennants to be grouped together)
> Add group mapping

- CHANGELOG.md
- docs/Hooks.md
- lib/oxidized/hook/githubrepo.rb
This patch adds support for group unique ssh keys for the githubrepo hook.
Keys are specified by private key only (public keys for Rugged are assumed to be the same filename + `.pub`), in the `remote_repo` configuration option. The patch supports existing functionality of:
```
remote_repo:
group1: <remote_url1>
group2: <remote_url>
```
and expands to support:
```
remote_repo:
group1:
url: <remote_url1>
privatekey: <priviate_key1>
group2:
url: <remote_url>
privatekey: <priviate_key2>
```
> Support group unique ssh keys for githubrepo hook

- CHANGELOG.md
- docs/Configuration.md
- lib/oxidized/config/vars.rb
This pull request allows for the specifying of vars for models within groups, overriding more general vars:
```
groups:
foo:
models:
arista:
vars:
ssh_keys: "~/.ssh/id_rsa_foo_arista"
vyatta:
vars:
ssh_keys: "~/.ssh/id_rsa_foo_vyatta"
bar:
models:
routeros:
vars:
ssh_keys: "~/.ssh/id_rsa_bar_routeros"
vyatta:
vars:
ssh_keys: "~/.ssh/id_rsa_bar_vyatta"
```
> Support variables for different models within groups

- CHANGELOG.md
- lib/oxidized/model/adtran.rb
This adds a missing check for if the `enable` command should be run on Adtran devices. Without the check, it causes an exception to be raised if the `enable` command isn't specified in the `vars` configuration setting. Fixes #2386.
> Add missing check for if to do `enable` for Adtran devices

- CHANGELOG.md
- lib/oxidized/model/opengear.rb
Opengear model backups only `/etc/version` not config itself. Proposed patch in Issue 1899 works so i use it to create PR.
Closes issue 1899
> Opengear model backup patched with proposed code from issue 1899

- CHANGELOG.md
- lib/oxidized/model/adva.rb
This PR fixes an issue with filtering out the local time and system uptime of ADVA devices.
> ADVA: Ensure local time and up time is properly filtered out.

- CHANGELOG.md
- lib/oxidized/input/ssh.rb
- oxidized.gemspec
- spec/input/ssh_spec.rb
This updates `net-ssh` to latest version `7.0.0.beta1`. I'm aware that #2555 exists, but this PR adds that while also making sure to enable `append_all_supported_algorithms: true` within `net-ssh` to ensure that nothing breaks from this upgrade. Despite the wording upstream, deprecated algorithms have yet to be removed in this version and all looks to be working great.
Please consider to add this as the upgrade to latest `net-ssh` does enable new KEX algorithms that newer devices support (e.g. `diffie-hellman-group14-sha256`).
> Upgrade to latest net-ssh (7.0.0.beta1)

- CHANGELOG.md
- lib/oxidized/model/procurve.rb
Allow (config) in procurve prompt so oxidized script can be used to enter configure mode on older HP procurve switches
Allow (config) in procurve prompt so oxidized script can be used to enter configure mode on older procurve switches
> Allow (config) in procurve prompt

- CHANGELOG.md
- docs/Model-Notes/IOS.md
- lib/oxidized/model/ios.rb
This is a fork of #1841 to resolve the merge conflicts and allow it to be submitted.
This PR allows issue #677 to be closed. It provides backwards compatibility with non altered configuration, and only takes effect if the ios_rbac variable is specified.
If ios_rbac variable is specified, the IOS model will append 'view full' to the 'show running-config' command to allow non level 15 users read access (if configuration on the device allows).
> Add support for IOS RBAC to close #667

- docs/Model-Notes/JunOS.md
Fix formatting error introduced in 87600b1f5f12711afe29c408e02dbbd927e3f25d which mismatched the model specific commands. Off-by-one documentation ;-)
Code reference: https://github.com/ytti/oxidized/blob/38a7a6405036c393eaddd07a375a1b9f3b0b43e4/lib/oxidized/model/junos.rb#L28-L31
> Correct documentation for JunOS model specific commands

- CHANGELOG.md
- docs/Supported-OS-Types.md
- lib/oxidized/model/nodegrid.rb
- [Y*] Passes rubocop code analysis (try `rubocop --auto-correct`)
- [N] Tests added or adapted (try `rake test`)
- [Y] Changes are reflected in the documentation
- [Y] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)
* Removed rubocop's "# frozen_string_literal: true" as I'm not sure it applies here
Adding basic support for ZPE Nodegrid OS (Tested on v5.4.10). Exports config correctly and includes all information required to restore from using the import function 'import_settings'. https://www.zpesystems.com/products/.
> Adding ZPE Nodegrid OS Support

- docs/Model-Notes/ADVA.md
Adding documentation to model-notes on how to restore the files generated by oxidized
This is reflected in the official ADVA documentation(FSP 150-GE100Pro, ProVMe R11.5 Provisioning and Operations Manual - Issue: A, Section: Configuration FIles):
> Add documentation on adva restore

- CHANGELOG.md
- lib/oxidized/model/adva.rb
Change prompt for the adva module to be any combination of word characters, since the defualt `ADVA-->` prompt can be overridden in the config via:
```
home
network-element ne-1
prompt "cpe123"
```
> fix adva prompt

- lib/oxidized/model/tmos.rb
Most of the configuration is stored in bigip.conf file. However, configuration for GTM is stored in bigip_gtm.conf
Changing "bigip.conf"  to "bigip*.conf"
Example of my environment:
[user@xx-dc-lb-02:Standby:In Sync] partitions # ls -LR
.:
EXCHANGE  LYNC  SP  SSO
./EXCHANGE:
bigip.conf  bigip_gtm.conf
./LYNC:
bigip.conf
./SP:
bigip.conf
./SSO:
bigip_gtm.conf
> Collect all bigip configurations in partition folder

- CHANGELOG.md
- lib/oxidized/model/eos.rb
Removes the unsupported-transceiver "license key" (password) from EOS configs when secrets are hidden.
> Hide unsupported-transceiver license key in Arista EOS

- CHANGELOG.md
- oxidized.gemspec
Rugged before v1.0.1 are incompatible with ruby 3.0 Fix upstream: https://github.com/libgit2/rugged/commit/a4ad1dff3d6f7418eda6bbbeb24f70b6e0d43237
Updated rugged gem to latest public release with above upstream fix for ruby 3.0 compatibility.
Fixes: #2620
> Updated rugged dependency for ruby 3.0 compatibility

- CHANGELOG.md
- extra/oxidized.logrotate
Currently if the logs do not yet exist logrotate service will fail. Add missingok to fix.
> Fix oxidized.logrotate to not fail if logs missing

- CHANGELOG.md
- lib/oxidized/model/netgear.rb
At the moment, it's not possible for Oxidized to save config on a Netgear device when connected over SSH, as it doesn't correctly finish the SSH session since we don't issue any `pre_logout` commands. This looks to have been previously done as Netgear devices do prompt the below each time an SSH session is ended:
````
The system has unsaved changes.
Would you like to save them now? (y/n)
````
As there are no actual changes being done over the SSH session that Oxidized uses though, it's safe to simply choose "n" here and move along.
Ref #1100 #2531
> Make sure SSH session can end on Netgear correctly

- CHANGELOG.md
- lib/oxidized/model/casa.rb
Updated the Casa model to include secret handling for rip authentication secrets.
Closes issues #2647
> Casa model: added handling for rip secrets

- CHANGELOG.md
- lib/oxidized/model/airfiber.rb
Made prompt regex match case-insensitive for the airfiber model. This allows it to support the AF5xHD model which returns a prompt like `af5xhd.*#`
> airfiber: prompt changes to support AF5xHD

- CHANGELOG.md
- lib/oxidized/model/edgecos.rb
"enable" is required by FS S3900-48T6S-R before running "show running-config".
Strips uptime from "show version"
> EdgeCOS: add support for FS S3900-48T6S-R

- CHANGELOG.md
- docs/Supported-OS-Types.md
- lib/oxidized/model/bdcom.rb
If possible I want to resurrect PR #2395, to be able to support an FS.COM switch (s3900R).
I've fixed the merge conflict by rebasing from the projects' master branch.
Tested with Fiberstore S3900-48T6S-R
See also PR #1855
> Add bdcom driver

- CHANGELOG.md
- lib/oxidized/model/fortios.rb
Our Fortigates often have unnecessary config updates due to the IoT database version updating. This PR strips out this version, as is already done for the other DB-versions.
> Fix remove FortiOS IoT-Detect database version

- CHANGELOG.md
- Dockerfile
- lib/oxidized/model/truenas.rb
There's an occasional race condition in the TrueNAS module. When the TrueNAS software is accessing the SQLite database, the command to dump it will fail and output only: 
```
/**** ERROR: (5) database is locked *****/
ROLLBACK; -- due to errors
```
This command invocation ought to get it to open even if it's locked, with the promise of being a read-only session.
> Fix TrueNAS locking contention

- CHANGELOG.md
- lib/oxidized/model/ironware.rb
Example:
```
telnet@lb1.adx1016> enable
No password has been assigned yet...
telnet@lb1.adx1016#
```
> Add support for no enable password set on ironware

- CHANGELOG.md
- Dockerfile
- extra/oxidized.runit
run oxidized as non-root user
parameterize oxidized UID and GID on build
This is to allow run oxidized in docker-container as non-root (oxidized) user. Said user UID and GID could be adjusted on image build.
> feat: run oxidized as non-root

- CHANGELOG.md
- lib/oxidized/model/pfsense.rb
In pfSense secret scrubbing, change `<secret hidden>` to `[secret hidden]`
This is so that the config remains as well-formed XML and can be read by an XML parser.
> pfsense: Change <secret hidden> to [secret hidden]

- CHANGELOG.md
- lib/oxidized/input/telnet.rb
several rake tests did fail, but they were all related to git operations? I'm not sure the best ways to test this.
models now work as already documented when using telnet.
I think the maintainer gets to decide where to do that.
this updates the cmd method to run through oxidized_expect and grab the resulting output buffer. this allows for models using expect (like the GS108T referenced in #2591) to work. I did not update that model here, as this is more for the core expect functionality.
Closes issue #2296
> work on cmd method to get expects in models again

- README.md
Following the commit 2a135ad47db34d7efaa1045515249fb83b1fe254, the READ.me provide wrong docker command as now the new user oxidized can't read in /root/ but should read his configuration in /home/oxidized.
This commit correct the commands given by READ.me to run oxidized container.
> Update READ.me following PR #2657

- CHANGELOG.md
- docs/Supported-OS-Types.md
- lib/oxidized/model/ciscoce.rb
New model for Cisco Catalyst Express switches.  They are IOS switches, but the SSH and Telnet interfaces are permanently disabled.  This will pull the configuration via the web interface.  It should also work on older IOS devices that have the basic web interface enabled.
> Add Model for Catalyst Express switches (ciscoce.rb)

- CHANGELOG.md
- lib/oxidized/model/comware.rb
Added support to comware type switch HPE Office Connect 1950.
> Modifications to allow HPE Office Connect 1950 xtd-cli-mode

- CHANGELOG.md
- docs/Supported-OS-Types.md
- lib/oxidized/model/hios.rb
Figured it out:
- The original Hirschmann CLI in Oxidized only worked for classic CLI environments, details on this [classic CLI here](https://www.doc.hirschmann.com/pdf/ManualCollection_Classic_L2P_09000_en.pdf)
- The added file hios.rb now works for more recent Hirschmann Industrial switches running HiOS, details on the [HiOS CLI here](https://www.doc.hirschmann.com/pdf/RM_CLI_HiOS-09001_Overview_en.pdf)
Note that the classic OS was sometimes also called HiOS, as seen in the filename [here](https://www.doc.hirschmann.com/pdf/RM_CLI_RSB20_Classic-HiOS-L2B-05300_en.pdf), but the text itself does not reference HiOS.
More evidence (Classic vs HiOS) here: http://www.doc.hirschmann.com/migration.html
- Hirschmann MACH Release L2P-09.0.19 and L2P-09.1.07 (for regular _hirschmann.rb_)
- …
> Added Hirschmann HiOS next to Hirschmann Classic

- lib/oxidized/hook/slackdiff.rb
#2576 switched to a different Slack web client, but did not also refactor the configuration object that is needed when a proxy is configured. This patch refactors the configuration object to the new client as well.
Closes #2615
> Fixes #2615 - Use correct Slack Web Client config object

- CHANGELOG.md
- lib/oxidized/model/stoneos.rb
> (StoneOS) Prompt support for long device names (>16 chars), '^H' handling and removal of ever-changing data

- CHANGELOG.md
- extra/gitdiff-msteams.sh
Add support for MS Teams webhooks to Oxidized
- [X ] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)
Add support for MS Teams webhooks. Closes ussue #1987
> Add support for MS Teams Webhook

- Dockerfile
When rugged is installed without defining a version, the newest version is build.
But then oxidized installs version 1.5.0.1 without ssh support later
Ending up with oxidized using version 1.5.0.1 without ssh support
Closes issue 2711
> Build the rugged version we use

- CHANGELOG.md
- docs/Model-Notes/PanOS_API.md
- docs/Supported-OS-Types.md
- lib/oxidized/model/panos_api.rb
Add Palo Alto model to allow backups of the XML configuration via the HTTP API. Reworked original [PR](https://github.com/ytti/oxidized/pull/2360)
Related #1110, #1287, #2434
Closes #1706
> Add Palo Alto HTTP API model (panos_api)

- lib/oxidized/output/git.rb
~~- [ ] Tests added or adapted (try `rake test`)~~
~~- [ ] Changes are reflected in the documentation~~
~~- [ ] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)~~
Fixes a bug caused by the RuboCop autocorrect.
In [/lib/oxidized/output/git.rb](https://github.com/ytti/oxidized/blob/637434b94055d4227aaae295958157a9af0cd788/lib/oxidized/output/git.rb) the code in [line 82](https://github.com/ytti/oxidized/blob/637434b94055d4227aaae295958157a9af0cd788/lib/oxidized/output/git.rb#L82) caused an error. 
Cause is `next if commit.diff(paths: [path]).empty?`, the return value of diff has no `empty?` function. 
The old line `next if commit.diff(paths: [path]).empty?` was correct. 
The same mistake was corrected in this [commit](https://github.com/ytti/oxidized/commit/c1b3aa871bfde4bb5031 …
> Fix git diff detection

- Dockerfile
Add detail about `CMAKE_FLAGS='-DUSE_SSH=ON'` being used to ensure rugged build with SSH support.
> Update Dockerfile with minor comment

- lib/oxidized/output/git.rb
Add missing "using Refinements" in lib/oxidized/output/git.rb, which was making the git output unusable since version 0.29.1.
Closes issue #2803
> Add missing "using Refinements" (closes issue #2803)

- CHANGELOG.md
- lib/oxidized/model/opnsense.rb
Oxidized tries to grab the opnsense version by running `opnsense-version 2>/dev/null`. This is not supported on opnsense's default shell (csh) and leads to:
```
```
The suggested change simply removes the I/O redirection of stderr to /dev/null.
> opnsense: do not redirect stderr when fetching opnsense version since default shell (csh) doesn't support it

- CHANGELOG.md
- Dockerfile
- docs/Hooks.md
Added the package msmtp to the docker container to add the ability to send mail using SMTP when using hooks and docker, also added relevent documentation.
I'm not that happy with the whole symlink from .config/oxidized to the homedir for the `.msmtprc` file, but having config all in the same place is easier to manage and it does work.
Please give feedback!
Documentation might also be badly worded or not understandable enough, feel free to give me feedback.
Thanks everyone involved in this project!
Closes issue #2574
Depends on PR #2813 (Fixes #2769)
> SMTP Mail sending in docker container and documentation for sending mail with msmtp

- CHANGELOG.md
- lib/oxidized/model/netscaler.rb
Currently Netscalers with "set ns hostName _name_" set aren't able to be backed up cause Oxidized doesn't recognize a valid prompt.
Prompt when not set:
`>`
Prompt when set:
`username@hostname>`
Current regex isn't liking the change.
I'm sure there's a more graceful way of dealing with the change, but I'm not good with regex. This works for me.
> Fix Netscaler with hostname backups

- CHANGELOG.md
- oxidized.gemspec
> Fix "unsafe_load" error

- CHANGELOG.md
- docs/Supported-OS-Types.md
- lib/oxidized/model/rgos.rb
This adds support for Ruijie Networks RGOS devices (and also RGOS devices relabelled FSOS by FS.COM), e.g. https://github.com/ytti/oxidized/issues/2662
> New model for Ruijie Networks RGOS devices

- CHANGELOG.md
- lib/oxidized/model/dlink.rb
dlink: fixed prompt for other dlink switches, added additional uptime removal expressions
> dlink: fixed prompt for other dlink switches, added additional uptime removal expressions

- CHANGELOG.md
- lib/oxidized/model/junos.rb
EX3400s should be included in the list of juniper switches where virtual-chassis status is collected; existing regex was limited to ex3300.
> Add ex3400 to junos VC-enabled platforms

- CHANGELOG.md
- lib/oxidized/model/adtran.rb
Remove constantly updating dates from backup of Adtran config
> Remove constantly updating dates from Adtran config

- CHANGELOG.md
- lib/oxidized/model/aricentiss.rb
- [ N/A ] Tests added or adapted (try `rake test`)
- [ N/A ] Changes are reflected in the documentation
Starting the 2.0 firmware, the pagination command has changed and the old one isn't supported (with or without the typo).
I tested it against switches running 2.1.3-25 and 2.2.1-38 without any issues.
Thanks.
> Add support for AricentISS firware 2.x

- CHANGELOG.md
- lib/oxidized/source/http.rb
> Bug Fix: source http

- lib/oxidized/model/aoscx.rb
- lib/oxidized/model/vrp.rb
two changes here:
**Firs one:** removes extra information from `show system` output on Aruba CX switches
```
Aruba1184-2540-UP# show system
Status and Counters - General System Information
System Name        : Aruba1184-2540-UP
System Contact     : ict@mail.com
System Location    :
MAC Age Time (sec) : 300
Time Zone          : 180
Daylight Time Rule : None
Software revision  : YC.16.11.0002        Base MAC Addr      : 8030e0-946060
ROM Version        : YC.16.01.0002        Serial Number      : CN8AJYH0J4
Up Time            : 95 days              Memory   - Total   : 359,035,392
CPU Util (%)       : 5                               Free    : 258,128,676
IP Mgmt  - Pkts Rx : 5,028,126            Packet   - Total   : 6600
Pkts Tx : 5,030,762            Buffers    Free    : 4794
Lowest  : 4729 …
```
> fix for Aruba remove extra info

- CHANGELOG.md
- lib/oxidized/model/netgear.rb
The pull request is to update the prompt detection RegEx to support Netgear M4250-10G2XF-PoE+ and M4300-28G-PoE+.
> Update the prompt detection RegEx to support Netgear M4250-10G2XF-PoE+ and M4300-28G-PoE+

- CHANGELOG.md
- lib/oxidized/input/ssh.rb
With the refinement change in e47d719aff64950f8cd7313f27d85846915db837,  the output from ssh is not packed in an Oxidized::String anymore. The refinement change trusts that the output would be a String.
But in the case of pfsense and opnsense, `cmd 'cat /conf/config.xml'` the output is a `Net::SSH::Connection::Session::StringWithExitstatus`, which causes `process_cmd_output` to wipe it out (`output = String.new('') unless output.instance_of?(String)`).
This PR ensures that input/ssh.rb returns a String
Closes issues #2771 #2968
> Fixed devices not retriving config after refinement change (openwrt, opnsense, pfsense)

- CHANGELOG.md
- lib/oxidized/model/fortios.rb
Fixes #2021 (@chrisr0880, @sahdan, @dangoscomb and @robertcheramy)
When post-login-baner is enabled, the fortigate requires pressind "a" to accept the message.
This PR has been tested agains Fortigate v7.0.13, with and without following configuration:
```
config system global
set post-login-banner enable
end
```
Closes issue #2021 .
> Fixed login into Fortigate when post-login-baner ist enabled

- lib/oxidized/model/eos.rb
Arista EOS (not sure when) started using "enable password" instead of "enable secret".  Updating the regex for those of us who use secrets redaction.
> eos string is enable password now

- lib/oxidized/model/aoscx.rb
Fixes `Command not supported` error on various Aruba CX 6xxx and 8xxx series
Changes to the aosxc.rb model in https://github.com/ytti/oxidized/pull/2933 cause a `Command not supported` error on various Aruba CX 6xxx and 8xxx series devices (and maybe others, but those are the ones that I've seen it on). I've expanded the command to make it compatible with those devices while keeping the functionality intended by the original commit.
> aoscx: Expand `show system` command for compatibility

- lib/oxidized/model/fortios.rb
"config system acme" uses "set privatekey" instead of the usual "set private-key" stanza on 7.0.x (tested on 7.0.13).
> Update fortios.rb to remove additional secrets

- lib/oxidized/model/iosxr.rb
- [] Passes rubocop code analysis (try `rubocop --auto-correct`)
The core code didn't change. Only specific model
The core code didn't change. Only specific model
Particular Model didn't have the documentation
N/A
"show inventory" command without admin keyword is not showing some useful inventory information, such as FAN, PSU and Chassis serial and part numbers
> Update iosxr.rb with admin keyword for show inventory command

- lib/oxidized/model/routeros.rb
Update filter for timestamped "by RouterOS" lines to match v7 as well as v6
Closes issue #3021
> Remove "<timestamp> by RouterOS" comment lines from ROS v7

- CHANGELOG.md
- lib/oxidized/jobs.rb
- lib/oxidized/nodes.rb
This change remediates a potential busy-loop in the scheduler which results from either next_adds_job allowing the job count to exceed the node count or a retry after configuration fetch failure causing the same invalid state.
> Prevent potential busy loop in scheduler from jobs > nodes

- lib/oxidized/jobs.rb
Correct accidental regression in scheduler introduced in https://github.com/ytti/oxidized/pull/3060
Apologies for not catching this pre-merge @ytti
> Correct accidental regression in scheduler introduced in PR3060

- lib/oxidized/model/sros.rb
Change cfg.sub! line in sros.rb to cfg.gsub!
It was doing a commit every time the uptime changed...
> Change cfg.sub! to cfg.gsub

- spec/input/ssh_spec.rb
- spec/node_spec.rb
- spec/nodes_spec.rb
- spec/refinements_spec.rb
- spec/source/http_spec.rb
- debug needs explicity to be set to "false" in order to avoid DEBUG messages
- Net::SSH.start needs a Hash for its options
- use asset_nil and not assert_equal
> Fix rake test

- CHANGELOG.md
- docs/Supported-OS-Types.md
- lib/oxidized/model/procurve.rb
- Reverting PR #2498 as it broke old procurve models (2510G, 2610, 2824).
- Closes issue #2833
- Closes issue #2871
- Removed "Invalid input" on unsupported commands
- Adding myself as model maintainter for HP/Aruba devices I have access to. Multiple model maintainters per model are welcome, just add yourself :-)
> Reverting PR #2498 as it broke old procurve models

- CHANGELOG.md
- docs/Model-Notes/FSOS.md
- docs/Supported-OS-Types.md
- lib/oxidized/model/fsos.rb
> Add support for Fibrestore FSOS

- lib/oxidized/input/http.rb
This patch introduces the ability to perform Digest HTTP authentication when making requests. If Digest authentication is not required or fails, the method falls back to Basic authentication. This enhancement provides more flexibility in handling different authentication schemes and improves compatibility with various systems.
Fixes #2685.
> Add Digest HTTP Authentication with Basic Auth Fallback

- lib/oxidized/input/http.rb
Adds safe navigation for res['www-authenticate'] because it can be nil in basic auth
> save navigation for http-header

- lib/oxidized/input/http.rb
PR #3047 introduced RuboCop warnings, which are fixed with this PR
> Fix RuboCop warnings introduced by PR #3047

- CHANGELOG.md
- lib/oxidized/model/nxos.rb
Changes are in the **nxos** model only:
- always replace secret with the `<secret hidden>` string
- rework the tacacs-server regex so that is works with all known cases
- add a new regex to remove secret in `snmp-server host` commands
Closes issue #3080
> feat: remove and enhance removal of secrets in nxos model

- lib/oxidized/model/vyatta.rb
The patch hide secrets of WireGuard interfaces in vyatta / vyos :
I was not able to try Rubocop and rake test. I'm not used to these tools and didn't manage to use them.
I tried this patch on our instance of Oxidized and the patch produce this change on VyOS 1.5 :
```diff
-set interfaces wireguard wg0 peer mypeer preshared-key 'DFpH6vrTlXczS/eHFUt+rddmE7zRaeQ1oCiprVGwzXs='
+set interfaces wireguard wg0 peer mypeer preshared-key <secret removed>
set interfaces wireguard wg0 peer mypeer public-key 'qu3a1Dus/jaE4QM6qIUWaF/Jdktg8+FyMssicDMsu1Y='
set interfaces wireguard wg0 port '43521'
-set interfaces wireguard wg0 private-key 'SCcDxY9eldGfQKlncqtPifGw0JHtedszS89V5BpTQWM='
+set interfaces wireguard wg0 private-key <secret removed>
```
> model vyatta: hide wireguard private-key and preshared-key

- README.md
- docs/Troubleshooting.md
- examples/podman-compose/Makefile
- examples/podman-compose/README.md
- examples/podman-compose/docker-compose.yml
- examples/podman-compose/model-simulation/Dockerfile-model
- examples/podman-compose/model-simulation/asternos.sh
- examples/podman-compose/oxidized-config/.gitignore
- examples/podman-compose/oxidized-config/config
- examples/podman-compose/oxidized-config/router.db
- examples/podman-compose/oxidized-ssh/README.md
Added an example how to run oxidized within a podman container with podman-container.
This PR also documents an closes Issue #2753
> Example of running oxidized with podman-container

- lib/oxidized/input/ssh.rb
> Fix wrong regexp to get ride of \r

- CHANGELOG.md
- lib/oxidized/model/h3c.rb
If you enter system-view on a comware switch the prompt changes from <> to [].
This isn't an issue in oxidized as it doesn't enter system-view to get data, but it might be needed when using oxidized-script, depending on what you're doing.
> Edit h3c model prompt to support the square brackets in system-view.

- CHANGELOG.md
- lib/oxidized/model/vyatta.rb
matches prompt ending with '>' which corresponds to non-privileged accounts. 
allows oxidized to use a non or low-privileged account to login to a VyOS device.
see related issue for detail
Closes issue #3111
> vyatta/vyos: update prompt matcher to account for non-privileged users

- README.md
> Fix document to generate config to correct volume directory

- CHANGELOG.md
- lib/oxidized/model/xos.rb
Hide radius and user secrets for XOS (Extreme Networks)
> Hide radius and user secrets for XOS

- spec/input/ssh_spec.rb
Close #3145
The A-record of example.com was changed from 93.184.216.34 to 93.184.215.14, so our test failed.
I updated the IP-Adress in the ssh-test.
I could have added an automatic resolution in the test, but I don't think the IP of example.com will change too often, so I kept it simple. A comment should help to find the problem quickly next time.
I'm not documenting this in CHANGELOG.md as it is only relevant for developpers and not for our users.
> Update ip of example.com in ssh-test

- CHANGELOG.md
- lib/oxidized/model/eos.rb
Hide radius and snmp secrets for Arista EOS
> Hide radius and snmp secrets for Arista EOS

- lib/oxidized/model/audiocodes.rb
Added missing NewLine characters. Without it the commands do not work.
Tested with Audiocodes SBC.
Closes issue #2006
> [Fix]Add missing NewLine Characters for Audiocodes config

- CHANGELOG.md
- lib/oxidized/model/dlink.rb
Added function to start privileged mode before pulling the configuration. Tested on DGS-3120-24SC.
> models/dlink.rb Add privileged mode (enable)

- CHANGELOG.md
- lib/oxidized/model/aoscx.rb
Fix #3142. The ArubaOS-CX switches with the new **L**ong **S**upport **R**elease (LSR) Version FL.10.1**3**.xxxx introduce a new sub-command `show environment power-consumption`. This displays current power consumption values for all switches in the stack. This is a fix, to exclude all actual power consumption values from the output.
> Fix arubaOS-CX power-consumption changes logged

- CHANGELOG.md
- lib/oxidized/output/git.rb
- spec/output/git_spec.rb
oxidized-web was getting "version not found" when fetching a version from git and no group was defined. The issue was that group was an empty string. As oxidized-web produces group=nil AND group='', we handle both in oxidized.
Added a minitest to validate the correct behaviour.
Closes #2222
> Fix version not found in oxidized-web

- CHANGELOG.md
- docs/Outputs.md
- docs/Troubleshooting.md
documentation: run Git garbage collection to address performance issues.
Closes: #3121
> documentation: run Git garbage collection to address performance issues.

- CHANGELOG.md
- lib/oxidized/config.rb
- lib/oxidized/hook/slackdiff.rb
- Updated slackdiff.rb to use slack_ruby_client instead of slack-api.
- Updated default timeout from 20 to 60. 
Fixes users experiencing the following error:
ERROR -- : Hook slack (#<SlackDiff:0x00005572c9621e20>) failed (#<NameError: uninitialized constant Slack::Client>) for event :post_store #2697
> Fix for slackdiff.

- lib/oxidized/model/aoscx.rb
When masking changing values, we were seeing the whitespace after the regex replace changing when the value being masked changed in length (e.g. fan speed went from 9750 to 10000 rpm). This caused unneccessary commits.
> aoscx.rb: improve regex replacement to avoid whitespace commits

- oxidized.gemspec
We do not need to lock psych to an old version.
There is no need either to enforce a high version, so changing ~> to >.
> Update dependency of psych version

- CHANGELOG.md
- docs/Sources.md
- lib/oxidized/source/csv.rb
- lib/oxidized/source/http.rb
- lib/oxidized/source/jsonfile.rb
- lib/oxidized/source/source.rb
- spec/source/http_spec.rb
With this class we can utilise JSON files directly without the redirection via a HTTP server. This massivly improved our configuration delivery process, because we are able to deliver cached configuration to oxidized without changes on the delivering service, which would have been much more complicated.
Adds an additional source class which is able to process JSON encoded files, like the HTTP source does.
> Add JSON source class.

- lib/oxidized/model/iosxr.rb
Admin mode is being deprecated on some IOS-XR flavors.
On others, `admin show` requires more permissions for the same (or similar) output.
I went for the `show inventory all` instead of `show inventory` according to [zagosch's comment](https://github.com/ytti/oxidized/issues/3166#issuecomment-2178030871) on the ASR9k platform, even though I did not see any output difference on NCS or C8000 series.
This PR :
* Solves #3166
* Reverts https://github.com/ytti/oxidized/pull/2915
> Solve IOS-XR admin mode deprecation on certain platforms

- lib/oxidized/model/aoscx.rb
\h means hex character, not horizontal whitespace, in ruby regex so while it still matched rpm numbers it wasn't actually fixing the problem
> Further tweak to aosxc.rb regex

- CHANGELOG.md
- lib/oxidized/model/rgos.rb
Starting with RGOS/FSOS 12 `show version` also reports `System uptime` for any installed module, e.g.:
```
#show version 
System description      : FS Data Center Switch(N5860-48SC) By FS.COM Inc
System start time       : 2024-07-04 05:43:25
System uptime           : 0:06:26:14
System hardware version : 1.00
System software version : N5860_FSOS 12.5(1)B0506
System patch number     : NA
System serial number    : <redacted>
System boot version     : 1.3.36(Master) 1.3.36(Slave)
System rboot version    : 1.2.8
Module information:
Slot 0 : N5860-48SC
System uptime       : 0:06:26:14
Hardware version    : 1.00
Boot version        : 1.3.36(Master) 1.3.36(Slave)
Rboot version       : 1.2.8
Software version    : N5860_FSOS 12.5(1)B0506
Serial number       : <redacted>
```
This change ensures all …
> rgos: Also strip system uptime from module

- README.md
Lastest oxidized uses at least ruby 3.0, centos 7 is so old you cant install ruby without rvm anymore i think
> Update Readme with centos 7 rvm 

- README.md
This PR updates the `README.md` to clarify the recommendation against running Oxidized as root. It now advises users to switch to the `oxidized` user with `su oxidized` to ensure proper permissions.
No additional tests were added, as this is a documentation change. The change does not require an update to the `CHANGELOG.md` as it does not affect the software's functionality.
> Clarify user permissions recommendation for running Oxidized

- CHANGELOG.md
- lib/oxidized/model/firewareos.rb
- spec/model/firewareos_spec.rb
fix prompt not matching when the node is managed and master
> firewareos: fix prompt not matching when the node is managed and master

- CHANGELOG.md
- lib/oxidized/model/ibos.rb
There's an oversight that does not pass the config back when remove_secret is enabled in IBOS, leading to a crash.
```
~
"10.15.0.3" 18L, 2006B                                                                                                                                             1,1           All
2024-10-16 06:24:52 UTC
undefined method `gsub!' for nil:NilClass
cfg.gsub! /.*uptime is.*/, ''
^^^^^^ [NoMethodError]
--------------------------------------------------
/nix/store/dd3bcw4i4mnr33vr0csiksbd6k7yzyvh-ruby3.1-oxidized-0.29.1/lib/ruby/gems/3.1.0/gems/oxidized-0.29.1/lib/oxidized/model/ibos.rb:28:in `block in <class:IBOS>'
/nix/store/dd3bcw4i4mnr33vr0csiksbd6k7yzyvh-ruby3.1-oxidized-0.29.1/lib/ruby/gems/3.1.0/gems/oxidized-0.29.1/lib/oxidized/model/model.rb:134:in `instance_exec' …
```
> Correctly produce config in cmd :secret for ibos

- CHANGELOG.md
- examples/device-simulation/yaml/iosxe_C9800-L-F-K9_17.06.05.yaml
- lib/oxidized/model/ios.rb
- spec/model/ios_spec.rb
This PR modifies the IOS model to hide secrets from IOS-XE WLCs (C9800). The secrets hidden are:
- WLAN PSK
- AP profile dot1x password
- AP profile mgmtuser password and secret
- RADIUS COA secret
> Remove secrets from IOS-XE WLCs (C9800)

- CHANGELOG.md
- oxidized.gemspec
Enable support for aes(128|256)gcm.
Fixes #3168.
- [-] Tests added or adapted (try `rake test`)
Update net-ssh to 7.3.
Enable support for aes(128|256)gcm.
Fixes #3168.
> Update net-ssh to 7.3

- CHANGELOG.md
- examples/device-simulation/cmdsets/aoscx
- examples/device-simulation/yaml/6400s_10.10.x.yaml
- examples/device-simulation/yaml/aoscx_R0X25A-6410_FL.10.10.1100.yaml
- lib/oxidized/model/aoscx.rb
- spec/model/aoscx_spec.rb
Modified aoscx.rb model to hide changing values such as power and temperature in 6400 switches in firmware 10.10.x
> Fix regex on Aruba 6400 switches

- lib/oxidized/model/ios.rb
- lib/oxidized/model/nxos.rb
IS-IS domain passwords hidden (with or without extra options)
IPSEC PSKs hidden
For IPSEC PSKs the configuration lines have the same issues as here:
https://github.com/ytti/oxidized/blob/b1be800e6d3f66c4cae406d5eb4da7a75f9e250b/lib/oxidized/model/ios.rb#L29
Which means we need to hide everyhing after the first command, there is no part of the command that lets us know that the next word is the actual key.
vrf-aware SNMP communities hidden
radius keys hidden (currently only global keys are hidden, this will hide both global and host-specific keys)
> Added handling of more ios-xe and nxos secrets

- CHANGELOG.md
- examples/device-simulation/yaml/iosxe_C9200L-24P-4G_17.09.04a.yaml
- lib/oxidized/model/ios.rb
Adding a custom SNMP OID means having a different "expression <value>" line each time the config is pulled. Add a rule to remove the expression value.
EEM code to generate the custom SNMP OID is:
event manager applet TotalNatTranslations
event timer watchdog time 300 maxrun 60
action 010 cli command "enable"
action 020 cli command "configure terminal"
action 030 cli command "do-exec show ip nat translations total"
action 040 regexp "^.+\s([0-9]+)" "$_cli_result" match total_translations
action 050 cli command "snmp mib expression owner nat name 1"
action 060 if $_regexp_result eq "1"
action 070  cli command "expression $total_translations"
action 080 else
action 090  cli command "expression 0"
action 100  cli command "exit"
action 110 end
The resulting configuration block is:
snmp mib …
> Remove constantly updating value from custom SNMP OID

- CHANGELOG.md
- lib/oxidized/model/xos.rb
Hide radius accounting secret for Extreme Networks XOS
> Hide radius accounting secret for Extreme Networks XOS

- docs/Hooks.md
Updated the slackdiff documentation to use the slack channel id.
Fixes #3349
> Updated slackdiff document to highlight channel id is required

- CHANGELOG.md
- docs/Model-Notes/FSOS.md
- examples/device-simulation/cmdsets/fsos
- examples/device-simulation/yaml/fsos_S3400-48T4SP_2.0.2J-120538.yaml
- lib/oxidized/model/fsos.rb
- spec/model/fsos_spec.rb
Either unencrypted (0) or encrypted (7) secrets should be hidden
Added multiple cfg.gsub to match every line containing "key ..." to hide unencrypted (`key 0`) or encrypted (`key 7`) secrets.
> feat(fsos): Hiding AAA and SNMP secrets

- CHANGELOG.md
- docs/Supported-OS-Types.md
- lib/oxidized/model/kornfeldos.rb
> New model for KornfeldOS

- CHANGELOG.md
- lib/oxidized/model/arubainstant.rb
- spec/model/data/arubainstant:generic:prompt.yaml
show version prepends a space to prompt when a core file is present.
Fixes #3398
> arubainstant: fix prompt

- CHANGELOG.md
- lib/oxidized/model/powerconnect.rb
We make the lazy assumption that when you can't turn off pagination with something like "terminal length 0", that Dell always puts an undesirable blank line before the --More-- prompt. :-)
This will make diffs fail between TFTPd and oxidized copies of the same config.
Perhaps Closes #3413 ?
> Simple solution to issue #3413 Removing inserted blank lines from pagnated output

- CHANGELOG.md
- docs/Troubleshooting.md
- lib/oxidized/output/git.rb
- spec/output/git_helper.rb
- spec/output/git_spec.rb
In order to address the performance issues observed in oxidzed-web when listing the versions of a node, this PR caches git log into memory. At the first time, we still have a slow performance, subsequent calls only need to scan new commits and are *very* much faster.
Closes #3121
> Cache git logs to accelerate displaying  the versions of a node in oxidized-web

- CHANGELOG.md
- docs/Supported-OS-Types.md
- lib/oxidized/model/unifiap.rb
Here is a new model for several Ubiquiti devices. Probably if it has /tmp/system.cfg, and /etc/board_info it has a decent chance of working. The hardest part was duplicating the output of the "info" command that is seemingly an internal command in the shell, or just not available in the AIrOS versions I tried.
Clif
Suggested model for issue #3430
> New Model for Unifi APs, switches, and AirOS APs

- CHANGELOG.md
- lib/oxidized/input/http.rb
With this PR the password string used for digest authentication gets automatically url encoded which is needed if you have special characters in your password. 
If you don't do this you just get a `URI::InvalidComponentError with msg "bad password component"` error.
> HTTP Digest Auth password encoding

- CHANGELOG.md
- lib/oxidized/model/powerconnect.rb
This makes it more clear (at least to me ;-) which commands are waiting for a prompt and which ones are not, (sends). I looked for documentation on post_login, and pre_logout but didn't find anything.
Also, I'm pretty sure the cli logout command needs to come after the last exit, not before. So I switched the order there, and added a little delay just for good luck. Lastly I added a comment on filtering out a timeout.
Re: #3437
> 3437 clean up login logout code for powerconnect.rb

- CHANGELOG.md
- lib/oxidized/model/aos7.rb
When `show hardware-info` runs slow on alcatel-lucent devices. An extra 'Please Wait'- and a newline is printed. This should not appear in the saved configuration.
> aos7: remove extra lines when hw-info runs slow

- CHANGELOG.md
- lib/oxidized/model/srosmd.rb
Somewhere between version `B-23.7.R2` and `B-23.10.R2` on the Nokia 7750 SR, a field for 64-bit system uptime was added. Before this didn't get filtered, so this PR fixes that.
The system information now includes both system uptime fields like this:
```
...
System Up Time         : 1 days, 01:01:01.11 (hr:min:sec)
System Up Time (64-bit): 1 days, 01:01:01.11 (hr:min:sec)
...
```
> srosmd: add ignore regex for 64-bit system up time

- CHANGELOG.md
- lib/oxidized/model/netgear.rb
Add pager handler to workaround an issue on some Netgear models that disabling the pager does not work for config dumps.
> netgear handle pager

- CHANGELOG.md
- docs/Configuration.md
- lib/oxidized/config.rb
- lib/oxidized/core.rb
- oxidized.gemspec
This Pull Request cannot be merged into master until the PR https://github.com/ytti/oxidized-web/pull/325 has been released into oxidized-web, because it depends on oxidized-web understanding the new configuration passed to it.
This pull request changes the configuration of oxidized-web, so that we can pass more arguments than just the interface to bind to, the port and an URL prefix.
This PR will close #3340 .
> Change oxidized-web configuration

- CHANGELOG.md
- lib/oxidized/model/ios.rb
- spec/model/data/ios:C9200L-24P-4G_17.09.04a:output.txt
- spec/model/data/ios:C9200L-24P-4G_17.09.04a:simulation.yaml
Remove secret for aaa server
Config could look like this
```
aaa server radius dynamic-author
client 10.10.10.10 server-key keytobehidden
client 10.10.20.20 server-key 7 0709285E4B1E18091B5C0814
```
> ios: Hide aaa server-key

- CHANGELOG.md
- lib/oxidized/model/nxos.rb
Some Cisco nexus devices occasionally run into a [Bug](https://bst.cisco.com/quickview/bug/CSCvz71586) where the bootflash size is  displayed as 0 kB and a warning message appears, which results in a lot of logged changes. This PR migitates the problem by just ignoring the bootflash lines and the warning.
> nxos: ignore bootflash size and errors

- CHANGELOG.md
- lib/oxidized/hook/githubrepo.rb
Fixes: #3464
I hope that if we explicitly tell that Rugged isn't installed with ssh support, it will help out users to find the problem.
Closes #3464
> Explicitly tell when Rugged isn't installed with ssh support

- CHANGELOG.md
- Dockerfile
- Rakefile
While removing the building environment, the Dockerfile wrongly removed git.
This also fixes the rake task `task :build_container` when the branch contains a `/`
Fixes #3482
> docker: do not remove git

- CHANGELOG.md
- lib/oxidized/model/aosw.rb
- In some cases, whitespaces are appended on the end of a line of config. We now catch these.
- VRRP Passphrases and AP Console Passwords are now catched too
- The regex matching `user ...` produces a lot of false positives, for example in ACL lists. It is now removed.
Tested on Aruba 9240 Gateways and Mobility Conductors
> aosw: fix secret parsing

- CHANGELOG.md
- lib/oxidized/model/nxos.rb
"show inventory all" provides additional module details, such as optics.
Additional inventory information can be seen with "show inventory all", such as optics, and various other modules.
> Support for complete inventory

- CHANGELOG.md
- lib/oxidized/model/acos.rb
This removes the amount of free storage from the show version output, because it can fluctuate, e.g. due to log files getting created and cleaned up.
Closes #2291
> Updated acos.rb to fix #2291

- lib/oxidized/model/aos7.rb
Follow-UP to #3445.
The `Please wait` lines are now removed for more commands.
> aos7: remove more lines occuring when commands run slow

- CHANGELOG.md
- lib/oxidized/model/awplus.rb
- #3494 introduced a bug where there is no return character when an enable password is supplied. The ssh session just hangs and times out.
- Test on `x610-5.4.5-3.7` with enable password supplied and on `x210-5.4.6-1.2` with enable = true.
> awplus: fix bug with enable password when supplied

- CHANGELOG.md
- lib/oxidized/model/quantaos.rb
- spec/model/data/quantaos:snippets:output.txt
- spec/model/data/quantaos:snippets:simulation.yaml
Working on Issue #3513
Fixes code scanning alerts https://github.com/ytti/oxidized/security/code-scanning/9 and https://github.com/ytti/oxidized/security/code-scanning/10 for quantaos
Adds a model unit test (only snippets) to avoid regressions.
> quantaos: remove inefficient regular expression

- CHANGELOG.md
- lib/oxidized/model/fabricos.rb
Some Brocade Fibre Channel switches report the power supply input voltage in the output of `chassisShow`. This pull request removes lines containing `PS Voltage input` because voltage fluctuations are unavoidable and would cause unnecessary backup changes.
This is an example line from a Brocade G630: `PS Voltage input:	231.00 V`
~I didn't run the tests or rubocop but~ I built the docker image with this change and tested it against the actual device.
> fabricos: remove input voltage from chassisShow

- lib/oxidized/model/routeros.rb
- spec/model/data/routeros:CHR_7.10.1:output.txt
- spec/model/data/routeros:CHR_7.10.1:simulation.yaml
- spec/model/data/routeros:CHR_7.16:output.txt
- spec/model/data/routeros:CHR_7.16:simulation.yaml
- spec/model/data/routeros:L009UiGS_7.15.2:output.txt
Update RouterOS Model with the following:
- Remove trailing whitespace from config. -> Issue in the Routerboard info section, as it causes frequent changes as sometimes trailing whitespace changes.
> Problem:
- Remove temporary comment on ipv6 changes. -> `# ipv6 neighbor configuration has changed, please restart the device in order to apply the new settings`
> Update RouterOS model

- lib/oxidized/model/aoscx.rb
In the case of a PSU showing N/A instead of speed, this fix will replace it into 'speed'
> Update aoscx.rb fix issue #3537

- CHANGELOG.md
- lib/oxidized/node.rb
- spec/model/apc_aos_spec.rb
- spec/node_spec.rb
> log an error when no suitable input is found for a node

- CHANGELOG.md
- lib/oxidized/model/vyatta.rb
Pull request #3547 changes vyatta.rb instead of edgeos.rb. This pull request fixed this fault.
See https://github.com/ytti/oxidized/pull/3547#issuecomment-3044689710
> undo edgerouter changes in vyatta.rb (from #3547)

- CHANGELOG.md
- lib/oxidized/model/zynos.rb
code scanning  alert 19 / See Issue #3513
> zynos: fix overly permissive regular expression range

- CHANGELOG.md
- lib/oxidized/input/ssh.rb
Revert to the log level of 0.33.0 for Net::SSH (:fatal, which is the default level of Net::SSH).
I could have disabled the use of ssh-agent with use_agent = false, but I'm not sure if someone uses an ssh-agent with oxidized. If we want to see the errors of Net::SSH when input.debug = false, we'll have to test if an agent is configured before opening a connection.
Fixes: #3574
> input/ssh: hide Net::SSH errors

- CHANGELOG.md
- docs/Hooks.md
- lib/oxidized/hook/slackdiff.rb
- slackdiff has no existing tests at the moment, and the fact that the hook heavily leans on other infrastructure (slack, a HTTP proxy) I don't think my skills as someone touching Ruby for the second time in their life are quite up to the task of figuring out the required mocks/scaffolding.
The new slack file upload API introduced by commit b92e6208365fdb6983dc69f50810b27a3ef1e206 to replace the deprecated API which was not available to new users (see issue #3189) introduced a new HTTP call that was not using the provided proxy configuration and broke environments where a proxy was necessary.
This commit fixes the regression reported in the issue #3534 by using the same proxy setting for the new HTTP POST request to `https://files.slack.com/`
Closes issue #3534 
A minor related change:
I …
> Slackdiff: Make Slack file upload respect a configured HTTP proxy
